import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {unzipSync,strFromU8} from 'fflate';
test.use({baseURL:process.env.ANIMATION_TEST_URL??'http://127.0.0.1:4358'});
test('multi-object timing, teaching steps, reopen and standalone export',async({page,context})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'动画步骤独立验证',width:1600,height:900,slides:[{id:'first',name:'动画',sourcePath:'first.html',html:'<!doctype html><html><body><main id="stage" data-notale-id="stage" style="width:1600px;height:900px"><h1 data-notale-id="one">第一对象</h1><h2 data-notale-id="two">第二对象</h2></main></body></html>'}]}});
 expect(response.status(),await response.text()).toBe(201);
 const ready=()=>page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const slide=()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0]);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await ready();
 await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany(['one','two']));
 await page.locator('[data-tool="animation"]').click();
 await page.locator('#animation-sequence').selectOption('after');
 await page.locator('[data-animation-effect="fade-in"]').click();
 await expect.poll(async()=>(await slide()).animations.length).toBe(2);await ready();
 expect((await slide()).animations.map((a:any)=>a.trigger)).toEqual(['click','after-previous']);
 await page.frameLocator('#canvas').locator('body').evaluate(()=>{
  const original=Element.prototype.animate;(window as any).__previewCalls=[];
  Element.prototype.animate=function(...args:Parameters<Element['animate']>){(window as any).__previewCalls.push({id:this.getAttribute('data-notale-id'),timing:args[1]});return original.apply(this,args);};
 });
 await page.locator('#preview-selected-animation').click();
 await expect.poll(()=>page.frameLocator('#canvas').locator('body').evaluate(()=>(window as any).__previewCalls.map((c:any)=>c.id))).toEqual(['one','two']);
 await page.locator('[data-cue-id]').last().locator('.animation-object').click();
 await page.locator('#duration').fill('1.2');await page.locator('#duration').press('Tab');
 await expect.poll(async()=>(await slide()).animations[1].duration).toBe(1200);
 await page.locator('#delay').fill('0.3');await page.locator('#delay').press('Tab');
 await expect.poll(async()=>(await slide()).animations[1].delay).toBe(300);
 await page.locator('#trigger').selectOption('click');
 await expect.poll(async()=>(await slide()).animations.map((a:any)=>a.step)).toEqual([1,2]);
 await page.locator('[data-up-animation]').last().click();await ready();
 expect((await slide()).animations.map((a:any)=>a.target)).toEqual(['two','one']);
 expect((await slide()).animations.map((a:any)=>a.step)).toEqual([1,2]);
 await page.locator('.animation-step-details > summary').click();
 await page.locator('#teaching-initialize').click();await ready();
 await page.locator('[data-step-id]').nth(1).click();
 await page.locator('#teaching-name').fill('解释概念');
 await page.locator('#teaching-advance').fill('1.5');
 await page.locator('#teaching-save').click();await ready();
 expect((await slide()).steps[1].advanceAfter).toBe(1500);
 await page.locator('#teaching-duplicate').click();await ready();
 expect((await slide()).steps.length).toBe(4);
 await page.locator('#teaching-down').click();await ready();
 await page.locator('#teaching-remove').click();await ready();
 const saved=await slide();
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await ready();
 expect(await slide()).toEqual(saved);
 const exported=await page.request.get('/api/documents/'+id+'/export');expect(exported.ok()).toBe(true);
 const files=unzipSync(new Uint8Array(await exported.body()));
 expect(JSON.parse(strFromU8(files['notale-project.json'])).document.slides[0]).toEqual(saved);
 const player=await context.newPage();
 await player.route('http://animation-export.test/**',route=>{
  const name=new URL(route.request().url()).pathname.slice(1)||'index.html';
  return route.fulfill({status:files[name]?200:404,contentType:'text/html',body:files[name]?Buffer.from(files[name]):''});
 });
 await player.goto('http://animation-export.test/first.html',{waitUntil:'domcontentloaded'});
 await player.waitForFunction(()=>(window as any).NotaleBridge);
 await player.evaluate(()=>(window as any).NotaleBridge.seek(1,true));
 await expect.poll(()=>player.locator('[data-notale-id="two"]').evaluate(e=>e.getAnimations().map(a=>a.effect?.getTiming().duration))).toContain(1200);
 expect(errors).toEqual([]);
 console.log('Animation fixture:',id);
});
