import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:'http://127.0.0.1:4399'});
test('animation keyboard selection follows focus and custom keyframes cancel without saving',async({page})=>{
 const id=randomUUID();const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'动画键盘',width:1600,height:900,slides:[{id:'page',name:'页面',sourcePath:'page.html',html:'<html><body><h1 data-notale-id="heading">标题</h1></body></html>',animations:[{id:'first',target:'heading',trigger:'click',effect:'fade-in',step:1,duration:300},{id:'second',target:'heading',trigger:'click',effect:'pulse',step:1,duration:700},{id:'third',target:'heading',trigger:'click',effect:'custom',step:1,duration:900,keyframes:[{opacity:0,offset:0},{opacity:1,offset:1}]}]}]}});expect(response.ok(),await response.text()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(async()=>{await (window as any).NotaleWorkbench.whenReady();(window as any).NotaleWorkbench.select('heading');});await page.locator('[data-tool="animation"]').click();
 const row=(id:string)=>page.locator(`.animation-object[data-edit-animation="${id}"]`);
 await row('first').click();await row('first').press('ArrowDown');await expect(row('second')).toBeFocused();await expect(row('second')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#duration')).toHaveValue('0.7');
 await row('second').press('End');await expect(row('third')).toHaveAttribute('aria-pressed','true');await row('third').press('Home');await expect(row('first')).toHaveAttribute('aria-pressed','true');await row('first').press('End');
 await page.locator('#animation-custom summary').click();const input=page.locator('#keyframes'),before=await input.inputValue();
 const version=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);
 await input.fill('invalid');await input.press('Escape');await expect(input).toHaveValue(before);expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(version);
 await input.fill('invalid draft');await page.evaluate(async()=>{const w=(window as any).NotaleWorkbench,current=w.getSnapshot().document.slides[0].animations.find((a:any)=>a.id==='third');await w.commands([{type:'animation.set',slideId:'page',animation:{...current,delay:250}}]);});await input.press('Tab');await expect(input).toHaveValue('invalid draft');
 await input.fill('[{"opacity":0.2,"offset":0},{"opacity":1,"offset":1}]');await input.press('Control+Enter');await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations.find((a:any)=>a.id==='third').keyframes[0].opacity)).toBe(.2);
});

test('focused animation form preserves newer delay and easing when duration is submitted',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'动画字段合并',width:1600,height:900,slides:[{id:'page',name:'页面',sourcePath:'page.html',html:'<html><body><h1 data-notale-id="heading">标题</h1></body></html>',animations:[{id:'cue',target:'heading',trigger:'click',effect:'fade-in',step:1,duration:600}]}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(async()=>{await (window as any).NotaleWorkbench.whenReady();(window as any).NotaleWorkbench.select('heading');});await page.locator('[data-tool="animation"]').click();await page.locator('.animation-object[data-edit-animation="cue"]').click();const duration=page.locator('#duration');await duration.focus();
 await page.evaluate(async()=>{const w=(window as any).NotaleWorkbench,current=w.getSnapshot().document.slides[0].animations[0];await w.commands([{type:'animation.set',slideId:'page',animation:{...current,delay:1250,easing:'linear'}}]);});
 await expect(page.locator('#delay')).toHaveValue('1.25');await expect(page.locator('#easing')).toHaveValue('linear');await expect(duration).toBeFocused();
 await duration.fill('2');await duration.press('Tab');await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations[0].duration)).toBe(2000);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].animations[0]).toMatchObject({duration:2000,delay:1250,easing:'linear'});
 await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations[0])).toMatchObject({duration:2000,delay:1250,easing:'linear'});
});

test('motion coordinate Escape cancels and Enter commits without consuming composition keys',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'路径坐标',width:1600,height:900,slides:[{id:'page',name:'页面',sourcePath:'page.html',html:'<html><body><h1 data-notale-id="heading">标题</h1></body></html>',animations:[{id:'cue',target:'heading',trigger:'click',effect:'motion',step:1,duration:600,path:[{x:0,y:0},{x:200,y:0}]}]}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(async()=>{await (window as any).NotaleWorkbench.whenReady();(window as any).NotaleWorkbench.select('heading');});await page.locator('[data-tool="animation"]').click();await page.locator('.animation-object[data-edit-animation="cue"]').click();await page.locator('#animation-path summary').click();
 const x=page.locator('[data-axis="x"][data-index="1"]');const version=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);await page.locator('.motion-path-canvas [data-point="1"]').click();await x.fill('200');await x.press('Enter');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(version);await x.fill('350');await x.dispatchEvent('keydown',{key:'Enter',isComposing:true});await expect(x).toBeFocused();await x.press('Escape');await expect(x).toHaveValue('200');expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations[0].path[1].x)).toBe(200);
 await x.fill('350');await x.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations[0].path[1].x)).toBe(350);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
});
