import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ANIMATION_TEST_URL??'http://127.0.0.1:4318'});
test('sidebar animation authoring: effects, timing, stacking, paths, preview and reopen',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const original=await page.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4').then(r=>r.json());
 const doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Animation sidebar acceptance';doc.slides=[doc.slides[6]];doc.slides[0].animations=[];
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
 await page.goto('/?document='+doc.id);
 await page.waitForFunction(()=>(window as any).NotaleWorkbench);
 const ready=()=>page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const animations=()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].animations);
 await ready();
 const target=await page.frameLocator('#canvas').locator('h1').getAttribute('data-notale-id');
 await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),target);
 await page.locator('[data-tool="animation"]').click();
 await page.frameLocator('#canvas').locator('body').evaluate(()=>{(window as any).__animationEditorSentinel=123;});
 await page.locator('[data-animation-effect="wipe-in"]').click();
 await expect.poll(async()=>(await animations()).length).toBe(1);await ready();
 await expect(page.locator('#property-panel')).toBeVisible();
 await page.locator('#duration').fill('0.8');await page.locator('#duration').press('Tab');
 await expect.poll(async()=>(await animations())[0].duration).toBe(800);
 await page.locator('.animation-advanced > summary').click();
 await page.locator('#animation-repeat').fill('2');await page.locator('#animation-repeat').press('Tab');
 await expect.poll(async()=>(await animations())[0].repeat).toBe(2);
 await page.locator('#animation-reverse').check();await expect.poll(async()=>(await animations())[0].autoReverse).toBe(true);
 await page.locator('#effect-direction').selectOption('up');await expect.poll(async()=>(await animations())[0].effectDirection).toBe('up');
 await page.locator('#new-animation').click();await page.locator('[data-animation-category="emphasis"]').click();await page.locator('[data-animation-effect="spin"]').click();
 await expect.poll(async()=>(await animations()).length).toBe(2);
 await page.locator('#trigger').selectOption('after-previous');
 await expect.poll(async()=>(await animations())[1].trigger).toBe('after-previous');
 expect((await animations())[1].step).toBe((await animations())[0].step);
 await page.locator('[data-cue-id]').first().locator('.animation-object').click();
 await expect(page.locator('#property-panel')).toBeVisible();
 await page.locator('[data-animation-effect="fade-in"]').click();await expect.poll(async()=>(await animations())[0].effect).toBe('fade-in');expect((await animations()).length).toBe(2);
 await page.locator('#new-animation').click();await page.locator('[data-animation-category="motion"]').click();await page.locator('[data-animation-effect="motion"]').click();await expect.poll(async()=>(await animations()).length).toBe(3);
 await page.locator('#animation-path > summary').click();await page.locator('[data-path-preset]').selectOption('arc');await expect.poll(async()=>(await animations())[2].path?.length).toBe(5);
 await page.locator('[data-path-points] input[data-index="2"][data-axis="y"]').fill('-120');await page.locator('[data-path-points] input[data-index="2"][data-axis="y"]').press('Tab');await expect.poll(async()=>(await animations())[2].path[2].y).toBe(-120);
 const ordered=await animations();
 await page.locator('[data-up-animation]').last().click();await expect.poll(async()=>(await animations())[1].id).toBe(ordered[2].id);
 await page.locator('#undo').click();await expect.poll(async()=>(await animations()).map((a:any)=>a.id)).toEqual(ordered.map((a:any)=>a.id));
 const other=await page.frameLocator('#canvas').locator('button[data-notale-id]').first().getAttribute('data-notale-id');
 await page.evaluate(ids=>(window as any).NotaleWorkbench.selectMany(ids),[target,other]);
 await page.locator('#new-animation').click();await page.locator('[data-animation-category="entrance"]').click();await page.locator('[data-animation-effect="appear"]').click();
 await expect.poll(async()=>(await animations()).length).toBe(5);
 expect((await animations()).slice(-2).map((a:any)=>a.target).sort()).toEqual([target,other].sort());
 await page.locator('#undo').click();await expect.poll(async()=>(await animations()).length).toBe(3);
 await page.locator('[data-cue-id]').last().locator('.animation-object').click();
 await ready();const version=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);
 await page.locator('#preview-selected-animation').click();
 await expect.poll(()=>page.frameLocator('#canvas').locator('h1').evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0);
 await page.locator('#stop-animation-preview').click();await expect.poll(()=>page.frameLocator('#canvas').locator('h1').evaluate(e=>e.getAnimations().length)).toBe(0);
 expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(version);
 expect(await page.frameLocator('#canvas').locator('body').evaluate(()=>(window as any).__animationEditorSentinel)).toBe(123);
 await page.locator('#property-panel').evaluate(e=>e.scrollTop=0);
 await page.screenshot({path:'.local/animation-sidebar.png'});
 await page.locator('#preview-animation').click();
 await expect(page.locator('#preview-next')).toBeEnabled();
 await page.locator('#preview-next').click();
 await expect.poll(()=>page.frameLocator('#preview-canvas').locator('h1').evaluate(e=>e.getAnimations().some(a=>a.effect?.getTiming().iterations===4))).toBe(true);
 await page.locator('#preview-close').click();
 await page.locator('#clear-object-animations').click();await expect.poll(async()=>(await animations()).length).toBe(0);
 await page.locator('#undo').click();await expect.poll(async()=>(await animations()).length).toBe(3);
 const saved=await animations();await page.reload();await ready();expect(await animations()).toEqual(saved);
 expect(errors).toEqual([]);
});
test('animation list keyboard stays scoped and canvas input stops temporary preview',async({page})=>{
 const original=await page.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4').then(r=>r.json());
 const doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Animation keyboard acceptance';doc.slides=[doc.slides[6]];doc.slides[0].animations=[];
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);await page.goto('/?document='+doc.id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const target=await page.frameLocator('#canvas').locator('h1').getAttribute('data-notale-id');
 await page.evaluate(async({target,slideId,id})=>{const w=(window as any).NotaleWorkbench;w.select(target);await w.commands([{type:'animation.set',slideId,animation:{id,target,step:1,effect:'pulse',trigger:'click',duration:1000,repeat:20}}]);},{target,slideId:doc.slides[0].id,id:randomUUID()});
 await page.locator('[data-tool="animation"]').click();await page.locator('.animation-object').first().click();
 await page.locator('.animation-object').first().press('Control+d');await expect(page.locator('[data-cue-id]')).toHaveCount(2);
 await page.locator('.animation-object').last().click();await page.locator('.animation-object').last().press('Delete');await expect(page.locator('[data-cue-id]')).toHaveCount(1);
 await expect(page.frameLocator('#canvas').locator('h1')).toBeVisible();
 await page.locator('.animation-object').first().click();await page.locator('#preview-selected-animation').click();
 await expect.poll(()=>page.frameLocator('#canvas').locator('h1').evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0);
 await page.frameLocator('#canvas').locator('body').dispatchEvent('pointerdown');
 await expect.poll(()=>page.frameLocator('#canvas').locator('h1').evaluate(e=>e.getAnimations().length)).toBe(0);
 await page.locator('.animation-object').first().press('Delete');await expect(page.locator('[data-cue-id]')).toHaveCount(0);
 await page.locator('#animations').press('Delete');await expect(page.frameLocator('#canvas').locator('h1')).toBeVisible();

});
