import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {reveal} from './harness/format-panel';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React appearance edits paint and gestures with undo and selection isolation',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'外观编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:'<html><body><div data-notale-id="a" style="position:absolute;left:100px;top:100px;width:200px;height:100px;background-color:#112233">A</div><div data-notale-id="b" style="position:absolute;left:400px;top:100px;width:200px;height:100px;background-color:#abcdef">B</div></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('a'));await expect(page.locator('#appearance-fill')).toHaveValue('#112233');const a=page.frameLocator('#canvas').locator('[data-notale-id="a"]');await page.locator('#appearance-fill').fill('#654321');await page.locator('#appearance-fill').blur();await expect(a).toHaveCSS('background-color','rgb(101, 67, 33)');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('background-color','rgb(17, 34, 51)');await expect(page.locator('#appearance-fill')).toHaveValue('#112233');
 await reveal(page,'#appearance-opacity');await page.locator('#appearance-opacity').fill('40');await page.locator('#appearance-opacity').blur();await expect(a).toHaveCSS('opacity','0.4');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('opacity','1');await expect(page.locator('#appearance-opacity')).toHaveValue('100');
 await reveal(page,'#appearance-radius');await page.locator('#appearance-radius').focus();await page.locator('#appearance-radius').evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,'30');el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#appearance-radius').press('Escape');await expect(page.locator('#appearance-radius')).toHaveValue('0');await expect(a).toHaveCSS('border-radius','0px');
 await page.locator('#appearance-radius').fill('15');await page.locator('#appearance-radius').press('Enter');await expect(a).toHaveCSS('border-radius','15px');await page.locator('#appearance-fill-none').check();await expect(a).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await page.evaluate(()=>(window as any).NotaleWorkbench.select('b'));await expect(page.locator('#appearance-fill')).toHaveValue('#abcdef');await expect(page.locator('#appearance-fill-none')).not.toBeChecked();await page.locator('#appearance-gradient').check();await page.locator('#appearance-gradient-color').fill('#123456');await page.locator('#appearance-gradient-color').blur();await expect(page.frameLocator('#canvas').locator('[data-notale-id="b"]')).toHaveCSS('background-image',/linear-gradient/);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
});

test('mixed appearance values stay distinct when only stroke width is edited and undo restores both',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'多选外观',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><div data-notale-id="a" style="position:absolute;left:100px;top:100px;width:200px;height:100px;background:#112233;border:2px dashed #ff0000">A</div><div data-notale-id="b" style="position:absolute;left:400px;top:100px;width:200px;height:100px;background:#abcdef;border:6px solid #0000ff;opacity:.4;border-radius:12px">B</div></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany(['a','b']));
 const width=page.locator('#appearance-stroke-width'),a=page.frameLocator('#canvas').locator('[data-notale-id="a"]'),b=page.frameLocator('#canvas').locator('[data-notale-id="b"]');
 await expect(width).toHaveValue('');await expect(width).toHaveAttribute('placeholder','—');await expect(page.locator('#appearance-fill')).toHaveAttribute('data-mixed','true');await expect(page.locator('#appearance-opacity-value')).toHaveText('—');
 await width.focus();await width.evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,'10');el.dispatchEvent(new Event('input',{bubbles:true}));});await width.press('Escape');await expect(width).toHaveValue('');await expect(a).toHaveCSS('border-top-width','2px');await expect(b).toHaveCSS('border-top-width','6px');
 await width.fill('8');await width.press('Enter');await width.blur();
 await expect(a).toHaveCSS('border-top-width','8px');await expect(b).toHaveCSS('border-top-width','8px');await expect(a).toHaveCSS('border-top-color','rgb(255, 0, 0)');await expect(b).toHaveCSS('border-top-color','rgb(0, 0, 255)');await expect(a).toHaveCSS('border-top-style','dashed');await expect(b).toHaveCSS('opacity','0.4');await expect(b).toHaveCSS('border-radius','12px');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('border-top-width','2px');await expect(b).toHaveCSS('border-top-width','6px');await expect(width).toHaveValue('');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(a).toHaveCSS('border-top-width','2px');await expect(b).toHaveCSS('border-top-width','6px');
});

test('autofit works after explicit logical sizes for horizontal and vertical text',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'文字框自动适应',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><p data-notale-id="h" style="position:absolute;left:50px;top:50px;width:600px;height:100px;inline-size:600px;block-size:100px;margin:0;font:24px Arial">Short</p><p data-notale-id="v" style="position:absolute;left:800px;top:50px;writing-mode:vertical-rl;width:100px;height:600px;inline-size:600px;block-size:100px;margin:0;font:24px Arial">Short</p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 for(const target of ['h','v']){
  await page.evaluate(target=>(window as any).NotaleWorkbench.select(target),target);const element=page.frameLocator('#canvas').locator('[data-notale-id="'+target+'"]');await reveal(page,'#appearance-fit');const field=page.locator('#appearance-fit');
  await field.selectOption('both');await expect.poll(()=>element.evaluate(node=>parseFloat(getComputedStyle(node).inlineSize))).toBeLessThan(200);await expect(field).toHaveValue('both');
  await field.selectOption('fixed');await expect(field).toHaveValue('fixed');await expect.poll(()=>element.evaluate(node=>node.style.getPropertyValue('inline-size').endsWith('px'))).toBe(true);
 }
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 for(const target of ['h','v'])await expect.poll(()=>page.frameLocator('#canvas').locator('[data-notale-id="'+target+'"]').evaluate(node=>parseFloat(getComputedStyle(node).inlineSize))).toBeLessThan(200);
});

test('stroke width and gradient angle retain unedited paint transparency',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'透明颜色保留',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><div data-notale-id="a" style="position:absolute;left:100px;top:100px;width:200px;height:100px;background-color:rgba(255,0,0,.3);background-image:linear-gradient(90deg,rgba(255,0,0,.3),rgba(0,0,255,.6));border:2px solid rgba(10,20,30,.4)">A</div></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('a'));const a=page.frameLocator('#canvas').locator('[data-notale-id="a"]');
 await expect(page.locator('#appearance-stroke-width')).toHaveValue('2');await page.locator('#appearance-stroke-width').fill('8');await page.locator('#appearance-stroke-width').press('Enter');await page.locator('#appearance-stroke-width').blur();await expect(a).toHaveCSS('border-top-width','8px');await expect(a).toHaveCSS('border-top-color','rgba(10, 20, 30, 0.4)');
 await page.locator('#appearance-gradient-angle').fill('45');await page.locator('#appearance-gradient-angle').press('Enter');await page.locator('#appearance-gradient-angle').blur();await expect(a).toHaveCSS('background-image','linear-gradient(45deg, rgba(255, 0, 0, 0.3), rgba(0, 0, 255, 0.6))');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(a).toHaveCSS('border-top-color','rgba(10, 20, 30, 0.4)');await expect(a).toHaveCSS('background-image','linear-gradient(45deg, rgba(255, 0, 0, 0.3), rgba(0, 0, 255, 0.6))');
});
