import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React connector and arrangement controls save geometry and layer edits',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',cause=>errors.push(cause.message));
 const html='<html><body style="margin:0"><main id="stage" data-notale-id="stage" style="position:absolute;width:1600px;height:900px">'+['a','b','c'].map((id,index)=>`<div data-notale-id="${id}" style="position:absolute;left:${100+index*250}px;top:${100+index*80}px;width:120px;height:80px;background:purple">${id}</div>`).join('')+'</main></body></html>';
 const created=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Arrangement controls',width:1600,height:900,slides:[{id:'first',name:'Page',sourcePath:'first.html',html}]}});expect(created.ok(),await created.text()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await page.evaluate(async()=>{await (window as any).NotaleWorkbench.commands([{type:'connector.set',slideId:'first',connector:{id:'line',start:{target:'a'},end:{target:'b'}}}]);await (window as any).NotaleWorkbench.whenSynchronized();});
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('line'));await expect(page.locator('#connector-panel')).toBeVisible();await page.locator('#connector-color').fill('#123456');await page.locator('#connector-width').fill('4');await page.locator('#connector-end').selectOption('');await expect(page.locator('#connector-end-point')).toBeVisible();await page.locator('#connector-end-x').fill('750');await page.locator('#connector-end-y').fill('400');await page.locator('#save-connector').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].connectors[0]).toMatchObject({color:'#123456',width:4,end:{point:{x:750,y:400}}});
 await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany(['a','b','c']));await page.locator('#property-arrange > summary').click();await expect(page.locator('#arrange-distribute-x')).toBeEnabled();await page.locator('#arrange-top').click();await expect.poll(()=>page.frameLocator('#canvas').locator('[data-notale-id="a"],[data-notale-id="b"],[data-notale-id="c"]').evaluateAll(nodes=>{const ys=nodes.map(node=>node.getBoundingClientRect().y);return Math.max(...ys)-Math.min(...ys);})).toBeLessThan(.1);
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('b'));await expect(page.locator('#arrange-distribute-x')).toBeDisabled();const version=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);await page.locator('#front').click();await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getConfirmedSnapshot().version)).toBeGreaterThan(version);expect(errors).toEqual([]);
});
