import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React asset library searches, inserts and replaces an existing image',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',cause=>errors.push(cause.message));
 expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Asset library',width:1600,height:900,slides:[{id:'first',name:'Blank',sourcePath:'first.html',html:'<html><body><main data-notale-id="stage" style="width:1600px;height:900px"></main></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const data=await page.evaluateHandle(()=>{const data=new DataTransfer(),bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='),c=>c.charCodeAt(0));data.items.add(new File([bytes],'sample.png',{type:'image/png'}));return data;});
 await page.locator('#canvas-viewport').evaluate((el,data)=>el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data})),data);
 const images=page.frameLocator('#canvas').locator('img');await expect(images).toHaveCount(1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const open=async()=>{if(await page.locator('[data-tool="insert"]').getAttribute('aria-pressed')!=='true')await page.locator('[data-tool="insert"]').click();const section=page.locator('[data-insert-category="media"]');if(await section.getAttribute('open')===null)await section.locator('summary').click();};
 await open();await expect(page.locator('.asset-card')).toHaveCount(1);await expect.poll(()=>page.locator('.asset-card img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);await expect(page.locator('#media-asset-kind')).toBeVisible();await page.locator('#media-asset-kind').selectOption('video');await expect(page.locator('#media-asset-empty')).toBeVisible();await page.locator('#media-asset-kind').selectOption('image');await page.locator('.asset-card img').dispatchEvent('error');await expect(page.locator('.asset-load-error')).toBeVisible();await page.locator('.asset-card').click();await expect(page.locator('.asset-load-error')).toHaveCount(0);await page.locator('#media-asset-search').fill('no-match');await expect(page.locator('#media-asset-empty')).toBeVisible();await page.locator('#media-asset-search').fill('');await page.locator('.asset-card').click();await page.locator('.asset-card').press('Enter');await expect(images).toHaveCount(2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 await expect(images.nth(1)).toHaveCSS('z-index','50');expect(await images.nth(1).evaluate(el=>(el as HTMLElement).style.left)).not.toBe('120px');
 const target=await images.first().getAttribute('data-notale-id');await page.evaluate(target=>(window as any).NotaleWorkbench.select(target),target);await open();await page.locator('.asset-card').click();await expect(page.locator('#media-asset-replace')).toBeEnabled();const before=await images.first().getAttribute('style');await page.locator('#media-asset-replace').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await expect(images).toHaveCount(2);expect(await images.first().getAttribute('style')).toBe(before);expect(errors).toEqual([]);
});
