import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://localhost:4399'});
test('canvas root decoration removal saves atomically and undoes',async({page})=>{
 const id=randomUUID();const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'画布文字装饰',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><p data-notale-id="text" style="position:absolute;left:100px;top:100px;font-size:36px;text-decoration:underline line-through">Hello world</p></body></html>'}]}});expect(response.ok(),await response.text()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const object=page.frameLocator('#canvas').locator('[data-notale-id="text"]');await object.dblclick();await expect(object).toHaveAttribute('contenteditable','true');
 await object.evaluate(async el=>{const r=document.createRange();r.setStart(el.firstChild!,0);r.setEnd(el.firstChild!,5);getSelection()!.removeAllRanges();getSelection()!.addRange(r);document.dispatchEvent(new Event('selectionchange'));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});
 await object.press('Control+u');await expect(object).toHaveCSS('text-decoration-line','none');await expect(object.locator('span').first()).toHaveCSS('text-decoration-line','line-through');await expect(object.locator('span').last()).toHaveCSS('text-decoration-line','underline line-through');await expect(object).toHaveText('Hello world');
 await object.press('Escape');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await expect(object).toHaveCSS('text-decoration-line','underline line-through');await page.locator('#redo').click();await expect(object).toHaveCSS('text-decoration-line','none');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(object).toHaveCSS('text-decoration-line','none');await expect(object.locator('span').first()).toHaveCSS('text-decoration-line','line-through');await expect(object.locator('span').last()).toHaveCSS('text-decoration-line','underline line-through');
});
