import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {newChart} from '@notale/editor/browser';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React ECharts type and import dialogs save to the selected chart',async({page})=>{
 const id=randomUUID();const created=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'图表弹窗验证',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:'<html><body><div data-notale-id="text">Text</div></body></html>'}]}});expect(created.ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await page.evaluate(model=>(window as any).NotaleWorkbench.commands([{type:'native-chart.create',slideId:'first',target:'chart',model,x:100,y:100,width:900,height:520}]),newChart('column'));
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('chart'));
 const properties=page.locator('#echarts-inspector');
 const title=properties.getByRole('textbox',{name:'标题',exact:true});
 const original=await title.inputValue();await title.fill('取消标题');await title.press('Escape');await expect(title).toHaveValue(original);await title.fill('第一版');await title.press('Enter');await title.fill('第二版');await title.press('Enter');
 const font=properties.getByRole('spinbutton',{name:'字号',exact:true});const originalSize=await font.inputValue();await font.fill('99');await font.press('Escape');await expect(font).toHaveValue(originalSize);await font.fill('22');await font.press('Enter');
 await properties.getByLabel('文字颜色',{exact:true}).fill('#123456');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const styled=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(styled.document.slides[0].nativeCharts.chart.authoring.appearance).toMatchObject({title:'第二版',fontSize:22,textColor:'#123456'});
 await page.evaluate(async()=>{const w=(window as any).NotaleWorkbench;const before=w.getSnapshot().document.slides[0].nativeCharts.chart.authoring;const model=structuredClone(before);model.appearance.title='外部更新';await w.commands([{type:'native-chart.edit',slideId:'first',target:'chart',before,model}]);});
 await expect(title).toHaveValue('外部更新');
 await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.lock',slideId:'first',target:'chart',locked:true}]));
 await expect(title).toBeDisabled();
 await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.lock',slideId:'first',target:'chart',locked:false}]));
 await expect(title).toBeEnabled();
 await page.locator('#echarts-inspector').getByRole('button',{name:'更改类型',exact:true}).click();
 await expect(page.locator('#chart-type-gallery')).toBeVisible();await page.locator('#chart-type-gallery').getByRole('button',{name:'折线图',exact:true}).click();await expect(page.locator('#chart-type-gallery')).toHaveCount(0);
 await page.locator('#echarts-inspector').getByRole('button',{name:'编辑数据',exact:true}).click();
 const fileChooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入表格',exact:true}).click();
 await (await fileChooser).setFiles({name:'data.csv',mimeType:'text/csv',buffer:Buffer.from('分类,训练,验证\nA,10,20\nB,30,40')});
 const dialog=page.getByRole('dialog',{name:'导入图表数据'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('textbox',{name:'表格内容'})).toHaveValue(/训练/);
 await expect(dialog.getByRole('textbox',{name:'表格内容'})).toBeFocused();await dialog.getByRole('textbox',{name:'表格内容'}).press('Control+Enter');await expect(dialog).toHaveCount(0);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());const chart=saved.document.slides[0].nativeCharts.chart.authoring;
 expect(chart.kind).toBe('line');expect(chart.rows).toHaveLength(2);expect(chart.series.map((series:any)=>series.name)).toEqual(['训练','验证']);
 const grid=page.locator('#chart-data-dock revo-grid');
 await grid.evaluate(el=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:500,clientY:400})));
 const menu=page.getByRole('menu');await expect(menu).toBeVisible();
 await expect(menu.getByRole('menuitem').first()).toBeFocused();await page.keyboard.press('ArrowDown');await expect(menu.getByRole('menuitem',{name:'删除当前行',exact:true})).toBeFocused();
 await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);
 await grid.evaluate(el=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:500,clientY:400})));await menu.getByRole('menuitem',{name:'在下方插入行',exact:true}).click();await expect(menu).toHaveCount(0);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const changed=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(changed.document.slides[0].nativeCharts.chart.authoring.rows).toHaveLength(3);
 await page.locator('.chart-data-actions').getByRole('button',{name:'＋ 系列',exact:true}).click();
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const expanded=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(expanded.document.slides[0].nativeCharts.chart.authoring.series).toHaveLength(3);
 const columns=expanded.document.slides[0].nativeCharts.chart.authoring.columns;
 await page.locator('.chart-data-bindings').getByRole('combobox',{name:'分类',exact:true}).selectOption(columns[1].id);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const bound=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(bound.document.slides[0].nativeCharts.chart.authoring.bindings.label).toBe(columns[1].id);
 await grid.evaluate(el=>el.dispatchEvent(new CustomEvent('beforecellfocusinit',{detail:{rowIndex:0,colIndex:1}})));
 await grid.evaluate(el=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:500,clientY:400})));
 await page.getByRole('menuitem',{name:'重命名当前列',exact:true}).click();
 const rename=page.locator('.chart-data-bindings').getByRole('textbox',{name:'列名称',exact:true});await rename.fill('重命名系列');await rename.press('Enter');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const renamed=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(renamed.document.slides[0].nativeCharts.chart.authoring.series[0].name).toBe('重命名系列');
 const dock=page.locator('#chart-data-dock'),resizer=dock.getByRole('separator');
 const height=await dock.evaluate(el=>el.getBoundingClientRect().height);await resizer.focus();await resizer.press('ArrowUp');await expect.poll(()=>dock.evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(height);
 await dock.getByRole('button',{name:'收起图表数据',exact:true}).click();await expect(dock).toBeHidden();
 await page.locator('#echarts-inspector').getByRole('button',{name:'编辑数据',exact:true}).click();await expect(dock).toBeVisible();await expect(dock.locator('revo-grid')).toHaveCount(1);
 await page.evaluate(()=>(window as any).NotaleWorkbench.dispose());await expect(page.locator('#chart-data-dock')).toBeHidden();await expect(page.locator('#echarts-inspector')).toBeHidden();
});
