import {test,expect} from '@playwright/test';
import {reveal} from './harness/format-panel';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React component form authors states, publishes a shared instance and returns from its source',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',cause=>errors.push(cause.message));
 const slides=[{id:'first',name:'Source',sourcePath:'first.html',html:'<html><body><section data-notale-id="root" style="position:absolute;left:150px;top:180px;width:500px;height:300px;background:white"><button data-notale-id="toggle">切换说明</button><p data-notale-id="answer">解释内容</p></section></body></html>'},{id:'second',name:'Instance',sourcePath:'second.html',html:'<html><body><p data-notale-id="marker">第二页</p></body></html>'}];
 expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Component form',width:1600,height:900,slides}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const select=async(id:string)=>{await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),id);await reveal(page,'#property-components');if(await page.locator('#property-components').getAttribute('open')===null)await page.locator('#property-components > summary').click();};
 const run=async(id:string)=>{await page.locator('#'+id).click();await expect(page.locator('#author-components')).toHaveAttribute('aria-busy','false');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await expect(page.locator('#author-components [role="alert"]')).toHaveCount(0);};
 await select('root');await run('author-component-create');await expect(page.locator('#author-text-enabled')).toBeDisabled();await page.locator('#author-component-name').fill('我的共享组件');await page.locator('#author-target').selectOption('answer');await page.locator('#author-visible').selectOption('false');await run('author-patch-save');await expect(page.locator('#author-component-name')).toHaveValue('我的共享组件');await run('author-behavior-save');
 await run('author-state-add');const open=await page.locator('#author-state').inputValue();expect(open).not.toBe('base');await page.locator('#author-state-name').fill('展开');await page.locator('#author-visible').selectOption('true');await page.locator('#author-background-color').fill('#fff4cc');await run('author-patch-save');await page.locator('#author-target').selectOption('toggle');await page.locator('#author-from').selectOption('base');await run('author-event-add');await run('author-library-publish');
 await expect(page.locator('#author-style')).toBeHidden();await expect(page.locator('#author-layout-save')).toBeHidden();
 await page.evaluate(()=>(window as any).NotaleWorkbench.showSlide('second'));await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await select('marker');await run('author-library-insert');const instance=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[1].components[0]);await select(instance.root);await expect(page.locator('#author-library-publish')).toBeDisabled();await page.locator('#author-state').selectOption(open);await page.locator('#author-target').selectOption(instance.instance.objects.answer);await page.locator('#author-background-color').fill('#ffccdd');await run('author-patch-save');
 await run('author-library-edit');await expect(page.locator('#author-source-return')).toBeVisible();await run('author-source-return');await page.locator('#author-state').selectOption(open);await run('author-state-preview');await expect(page.frameLocator('#canvas').locator(`[data-notale-id="${instance.instance.objects.answer}"]`)).toHaveCSS('background-color','rgb(255, 204, 221)');
 const saved=await page.request.get('/api/documents/'+id).then(response=>response.json());expect(saved.document.componentLibrary).toHaveLength(1);expect(saved.document.slides).toHaveLength(2);expect(saved.document.slides[1].components[0].instance.stateOverrides[open].answer.style['background-color']).toBe('#ffccdd');expect(errors).toEqual([]);
});
