import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:'http://127.0.0.1:4318'});
test('context format preserves selected text, saved HTML and live canvas',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const original=await page.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4').then(r=>r.json());
 const doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Context formatting acceptance';doc.slides=[doc.slides[6]];doc.slides[0].animations=[];
 doc.slides[0].html=doc.slides[0].html.replace(/(<h1[^>]*>)[\s\S]*?(<\/h1>)/,'$1交互文字 <b data-notale-id="context-bold">原有粗体</b> <a data-notale-id="context-link" href="https://example.com">链接</a>$2');
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
 await page.goto('/?document='+doc.id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const heading=page.frameLocator('#canvas').locator('h1');await heading.click({button:'right'});
 await expect(page.locator('.object-mini-toolbar')).toBeVisible();await expect(page.locator('[data-action="arrange"]')).toBeVisible();
 await page.keyboard.press('Escape');await heading.dblclick();await expect(heading).toHaveAttribute('contenteditable','true');
 await heading.evaluate(el=>{(window as any).__contextSentinel=77;const text=document.createTreeWalker(el,NodeFilter.SHOW_TEXT).nextNode()!;const range=document.createRange();range.setStart(text,0);range.setEnd(text,2);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));});
 await heading.evaluate(el=>{el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:300,clientY:200}));});
 await expect(page.locator('[data-action="clear-format"]')).toBeVisible();await expect(page.locator('[data-action="delete"]')).toHaveCount(0);
 await page.locator('[data-format="color"]').fill('#dd2244');await page.locator('[data-format="color"]').dispatchEvent('change');
 await expect.poll(()=>heading.innerHTML()).toContain('color: rgb(221, 34, 68)');
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBeGreaterThan(1);
 expect(await heading.locator('[data-notale-id="context-bold"]').textContent()).toBe('原有粗体');
 expect(await heading.locator('[data-notale-id="context-link"]').getAttribute('href')).toBe('https://example.com');
 expect(await heading.evaluate(()=>(window as any).__contextSentinel)).toBe(77);
 await page.keyboard.press('Escape');await heading.press('End');await page.keyboard.insertText('继续输入');
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html)).toContain('继续输入');
 await heading.press('Escape');await page.reload();await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await expect(heading).toContainText('继续输入');expect(await heading.innerHTML()).toContain('color: rgb(221, 34, 68)');
 await heading.click({button:'right'});await page.screenshot({path:'.local/context-format.png'});
 await page.locator('[data-action="lock"]').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].locked.length)).toBe(1);
 await heading.click({button:'right'});await expect(page.locator('[data-action="delete"]')).toBeDisabled();await page.locator('[data-action="lock"]').click();
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].locked.length)).toBe(0);
 expect(errors).toEqual([]);
});
test('text outbox survives delayed acknowledgements, undo and a tab closing during composition',async({page,context})=>{
 const original=await page.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4').then(r=>r.json());const doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Text outbox acceptance';doc.slides=[doc.slides[6]];doc.slides[0].animations=[];
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
 await page.goto('/?document='+doc.id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const heading=page.frameLocator('#canvas').locator('h1');await heading.dblclick();await expect(heading).toHaveAttribute('contenteditable','true');
 const before=await heading.textContent();await heading.press('End');await page.keyboard.insertText('撤销样本');await heading.press('Control+z');await expect(heading).toHaveText(before!);
 await heading.press('Control+Shift+z');await expect(heading).toContainText('撤销样本');await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html.includes('撤销样本'))).toBe(true);
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let held=false;
 await page.route('**/sync',async route=>{if(held){await route.continue();return;}held=true;const response=await route.fetch();await gate;await route.fulfill({response});});
 await heading.press('End');await page.keyboard.insertText('慢确认');await expect.poll(()=>held).toBe(true);
 await page.keyboard.insertText('新输入');release();await expect(heading).toContainText('慢确认新输入');await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html.includes('慢确认新输入'))).toBe(true);
 await heading.press('Escape');await page.locator('#undo').click();await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html.includes('新输入'))).toBe(false);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.locator('#redo').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(heading).toContainText('新输入');
 await heading.dblclick();await expect(heading).toHaveAttribute('contenteditable','true');await heading.press('End');
 await heading.dispatchEvent('compositionstart',{data:''});await page.keyboard.insertText('竖排中文草稿');
 const pending=()=>page.evaluate(async()=>{const names=await indexedDB.databases();const name=names.find(n=>n.name?.startsWith('notale-sync-v1:'))!.name!;return new Promise<any[]>(resolve=>{const req=indexedDB.open(name);req.onsuccess=()=>{const db=req.result;const r=db.transaction('operations').objectStore('operations').getAll();r.onsuccess=()=>{resolve(r.result);db.close();};};});});
 await expect.poll(async()=>(await pending()).some(e=>e.staged&&e.draftTask.request.commands[0].patch.richText.includes('竖排中文草稿'))).toBe(true);
 await page.close();const reopened=await context.newPage();await reopened.goto('/?document='+doc.id);await reopened.waitForFunction(()=>(window as any).NotaleWorkbench);await reopened.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await expect.poll(()=>reopened.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html.includes('竖排中文草稿'))).toBe(true);
 await expect(reopened.frameLocator('#canvas').locator('h1')).toContainText('竖排中文草稿');
});
