import {test,expect} from '@playwright/test';
import {reveal} from './harness/format-panel';
import {randomUUID} from 'node:crypto';
import {importHtml} from '@notale/editor';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React document settings preserve drafts and require confirmation before restoring history',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'文档设置',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:importHtml('<html><body><main id="stage">文档设置</main></body></html>').html}]}});expect(response.ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length>0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const doc=()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document);
 await page.locator('[data-tool="style"]').click();await reveal(page,'#deck-width');await page.locator('#deck-width').fill('1300');await page.locator('#deck-width').press('Escape');await expect(page.locator('#deck-width')).toHaveValue('1600');await page.locator('#deck-width').fill('1400');await page.locator('#deck-width').press('Enter');await expect.poll(async()=>(await doc()).width).toBe(1400);
 await page.locator('#deck-height').fill('850');await page.locator('#save-deck-size').click();await expect.poll(async()=>(await doc()).height).toBe(850);
 await page.locator('#deck-width').fill('1500');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'deck.update',width:1450}]));await page.locator('#deck-width').press('Enter');await expect(page.locator('#deck-size-status')).toContainText('Esc');await expect(page.locator('#deck-width')).toHaveValue('1500');await page.locator('#deck-width').press('Escape');await expect(page.locator('#deck-width')).toHaveValue('1450');expect((await doc()).width).toBe(1450);
 await reveal(page,'#open-theme-settings');await page.locator('#open-theme-settings').click();await page.locator('#theme-json').fill('{"--text":"#123456"}');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'deck.update',title:'无关修改'}]));await page.locator('#theme-settings-dialog button[type="submit"]').click();await expect(page.locator('#theme-settings-dialog')).toHaveCount(0);expect((await doc()).theme['--text']).toBe('#123456');
 await page.locator('#open-theme-settings').click();await page.locator('#theme-json').fill('{"--x":1}');await page.locator('#theme-settings-dialog button[type="submit"]').click();await expect(page.locator('#theme-settings-dialog [role="status"]')).toContainText('字符串值');
 await page.locator('#theme-json').fill('{"--x":"保留草稿"}');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'deck.update',theme:{'--text':'#654321'}}]));await page.locator('#theme-settings-dialog button[type="submit"]').click();await expect(page.locator('#theme-settings-dialog [role="status"]')).toContainText('主题已变化');await expect(page.locator('#theme-json')).toHaveValue('{"--x":"保留草稿"}');await page.locator('#theme-settings-dialog [data-close]').click();
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());let failedHistory=false;await page.route('**/api/documents/'+id+'/history',route=>{if(!failedHistory){failedHistory=true;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'历史暂不可用'})});}return route.continue();});await page.locator('#file-menu-trigger').click();await page.locator('[data-file="history"]').click();await page.getByRole('button',{name:'重新加载历史版本',exact:true}).click();await expect(page.locator('#history option')).not.toHaveCount(0);await page.locator('#history').selectOption('1');await expect(page.locator('#restore')).toBeDisabled();await page.locator('#history-confirm').check();await page.locator('#restore').click();await expect(page.locator('#history-dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 expect((await doc()).width).toBe(1600);expect((await doc()).height).toBe(900);expect((await doc()).theme).toEqual({});expect((await doc()).title).toBe('文档设置');await expect(page.locator('#deck-width')).toHaveValue('1600');expect(errors).toEqual([]);
});
