import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {importHtml} from '@notale/editor';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4393'});
test('React navigation and bounded canvas reuse preserve edits and invalidate old revisions',async({page})=>{
  const id=randomUUID();
  const slides=Array.from({length:10},(_,index)=>({id:'p'+index,name:'页面 '+index,sourcePath:`p${index}.html`,html:importHtml(`<html><body><main id="stage" style="width:1600px;height:900px"><h1 data-notale-id="title">页面 ${index}</h1></main></body></html>`).html}));
  const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'架构迁移验证',width:1600,height:900,slides}});expect(response.ok()).toBe(true);
  await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===10);
  await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
  await expect(page.locator('.slide-card')).toHaveCount(10);
  await page.frameLocator('#canvas').locator('#stage').evaluate(()=>{(window as any).__cacheMarker='retained';});
  const show=(id:string)=>page.evaluate(id=>(window as any).NotaleWorkbench.showSlide(id),id);
  await show('p1');await show('p0');
  expect(await page.frameLocator('#canvas').locator('#stage').evaluate(()=>(window as any).__cacheMarker)).toBe('retained');
  await show('p2');await show('p3');await show('p4');await expect(page.locator('#canvas-host iframe')).toHaveCount(3);
  await show('p0');expect(await page.frameLocator('#canvas').locator('#stage').evaluate(()=>(window as any).__cacheMarker)).toBeUndefined();
  await page.locator('[data-tool="pages"]').click();
  await page.locator('#slide-search').fill('页面 7');await expect(page.locator('.slide-card:visible')).toHaveCount(1);
  await page.locator('#slide-search').fill('');await page.locator('#overview').click();await expect(page.locator('.slide-card:visible')).toHaveCount(8);
  await page.locator('#overview-next').click();await expect(page.locator('.slide-card:visible')).toHaveCount(2);await page.locator('#overview-close').click();
  await page.locator('[data-slide="p0"]').focus();await page.keyboard.press('Alt+ArrowDown');
  await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[1].id)).toBe('p0');
  await page.evaluate(async()=>{const w=(window as any).NotaleWorkbench;await w.commands([{type:'slide.update',slideId:'p0',patch:{name:'已保存标题'}}]);await w.whenSynchronized();});
  await expect(page.locator('[data-slide="p0"] .name')).toHaveText('已保存标题');
  await page.frameLocator('#canvas').locator('#stage').evaluate(()=>{(window as any).__cacheMarker='old-revision';});
  await show('p1');await show('p0');expect(await page.frameLocator('#canvas').locator('#stage').evaluate(()=>(window as any).__cacheMarker)).toBeUndefined();
  const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides.find((s:any)=>s.id==='p0').name).toBe('已保存标题');
});
