import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React crop drag keyboard save and reopen preserve image geometry',async({page})=>{
 const id=randomUUID(),src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'裁剪编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:`<html><body><img data-notale-id="image" src="${src}" style="position:absolute;left:100px;top:100px;width:200px;height:600px"></body></html>`}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('image'));await page.locator('#open-image-crop').click();await expect(page.locator('#crop-preview')).toBeVisible();
 const stage=await page.locator('#crop-stage').boundingBox(),handle=await page.locator('[data-crop-edge="left"]').boundingBox();expect(stage!.width/stage!.height).toBeCloseTo(1/3,2);await page.mouse.move(handle!.x+handle!.width/2,handle!.y+handle!.height/2);await page.mouse.down();await page.mouse.move(handle!.x+handle!.width/2+stage!.width*.1,handle!.y+handle!.height/2,{steps:3});await expect(page.locator('[data-crop-edge="left"]')).toHaveAttribute('aria-valuenow','10');await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('#image-crop-dialog')).toBeVisible();await expect(page.locator('[data-crop-edge="left"]')).toHaveAttribute('aria-valuenow','0');await page.mouse.move(handle!.x+handle!.width/2,handle!.y+handle!.height/2);await page.mouse.down();await page.mouse.move(handle!.x+handle!.width/2+stage!.width*.2,handle!.y+handle!.height/2,{steps:4});await page.mouse.up();await expect(page.locator('[data-crop-edge="left"]')).toHaveAttribute('aria-valuenow','20');await page.locator('[data-crop-edge="top"]').press('Shift+ArrowDown');await page.locator('#crop-fit').selectOption('cover');await page.locator('#crop-focus-x').fill('75');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'deck.update',title:'裁剪期间更新标题'}]));await page.locator('#crop-focus-x').press('Control+Enter');await expect(page.locator('#image-crop-dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const image=page.frameLocator('#canvas').locator('[data-notale-id="image"]');const metadata=JSON.parse((await image.getAttribute('data-notale-media'))!);expect(metadata.crop.left).toBeCloseTo(20,0);expect(metadata.crop.top).toBe(10);expect(metadata.positionX).toBe(75);await expect(image).toHaveAttribute('src',src);expect(await image.evaluate(el=>[getComputedStyle(el).width,getComputedStyle(el).height])).toEqual(['200px','600px']);
 await page.locator('#open-image-crop').click();await expect(page.locator('[data-crop-edge="left"]')).toHaveAttribute('aria-valuenow','20');await page.locator('#reset-image-crop').click();await expect(page.locator('[data-crop-edge="left"]')).toHaveAttribute('aria-valuenow','0');await page.locator('#close-image-crop').click();expect(JSON.parse((await image.getAttribute('data-notale-media'))!)).toEqual(metadata);const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).toContain('data-notale-media');
});
