import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React insertion catalog searches, inserts and drags while keeping extension slots intact',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',cause=>errors.push(cause.message));const created=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Insert catalog',width:1600,height:900,slides:[{id:'first',name:'Blank',sourcePath:'first.html',html:'<html><body style="margin:0"><main id="stage" data-notale-id="stage" style="position:absolute;width:1600px;height:900px"></main></body></html>'}]}});expect(created.ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.locator('[data-tool="insert"]').click();
 await page.locator('[data-insert-category="icons"] > summary').click();await page.locator('#icon-search').fill('calendar');await expect(page.locator('#icon-gallery button:visible')).toHaveCount(1);await page.locator('#icon-gallery button:visible').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 if(await page.locator('[data-tool="insert"]').getAttribute('aria-pressed')!=='true')await page.locator('[data-tool="insert"]').click();
 const canvas=(await page.locator('#canvas').boundingBox())!,target={x:canvas.x+canvas.width*.3,y:canvas.y+canvas.height*.7},transfer=await page.evaluateHandle(()=>new DataTransfer());
 await page.locator('[data-insert="shape:diamond"]').dispatchEvent('dragstart',{dataTransfer:transfer});await expect(page.locator('#insert-drop-overlay')).toBeVisible();await page.locator('#insert-drop-overlay').dispatchEvent('drop',{dataTransfer:transfer,clientX:target.x,clientY:target.y});await expect(page.locator('#insert-drop-overlay')).toBeHidden();const diamond=page.frameLocator('#canvas').locator('[data-notale-shape="diamond"]');await expect(diamond).toHaveCount(1);const position=await diamond.evaluate(node=>({x:parseFloat((node as HTMLElement).style.left),y:parseFloat((node as HTMLElement).style.top)}));expect(Math.abs(position.x-330)).toBeLessThanOrEqual(4);expect(Math.abs(position.y-550)).toBeLessThanOrEqual(4);
 if(await page.locator('[data-tool="insert"]').getAttribute('aria-pressed')!=='true')await page.locator('[data-tool="insert"]').click();await page.locator('[data-insert-category="diagrams"] > summary').click();await expect.poll(()=>page.locator('[data-diagram-template]').count()).toBeGreaterThan(0);await page.locator('#icon-search').fill('');await expect.poll(()=>page.locator('#icon-gallery button:visible').count()).toBeGreaterThan(1);expect(await page.locator('[data-diagram-template]').count()).toBeGreaterThan(0);
 await page.locator('[data-insert-category="media"] > summary').click();await expect(page.locator('#media-asset-library')).toBeVisible();expect(errors).toEqual([]);
});
