import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EditorKernel} from '../src/editor-kernel';
import type {Pending} from '../src/pending-journal';
function fixture(){
 const queue:Pending[]=[];let failCancel=false,failEnqueue=false;
 const kernel=new EditorKernel({operations:()=>queue,owner:()=> 'owner',stage:async()=>{},finalize:async()=>{},enqueue:async task=>{if(failEnqueue)throw Error('storage failed');queue.push(task);},cancel:async id=>{if(failCancel)throw Error('cancel failed');const index=queue.findIndex(t=>t.request.mutationId===id);if(index<0)return false;queue.splice(index,1);return true;},prepare:async()=>{throw Error('unexpected preparation');},barrier:async()=>{},changed:()=>{},preview:()=>{},error:()=>{}});
 kernel.load({version:1,document:{id:'doc',schemaVersion:1,title:'Before',width:1600,height:900,slides:[]}} as any);
 return {kernel,queue,setCancel:(value:boolean)=>failCancel=value,setEnqueue:(value:boolean)=>failEnqueue=value};
}
test('failed local undo preserves history for retry',async()=>{const f=fixture();await f.kernel.execute([{type:'deck.update',title:'After'}]);f.setCancel(true);await assert.rejects(f.kernel.undo(),/cancel failed/);assert.equal(f.kernel.canUndo,true);assert.equal(f.kernel.canRedo,false);f.setCancel(false);await f.kernel.undo();assert.equal(f.kernel.current.document.title,'Before');assert.equal(f.kernel.canRedo,true);});
test('failed inverse enqueue preserves acknowledged undo for retry',async()=>{const f=fixture();await f.kernel.execute([{type:'deck.update',title:'After'}]);f.kernel.acknowledge(f.queue[0].request.mutationId,2);f.setEnqueue(true);await assert.rejects(f.kernel.undo(),/storage failed/);assert.equal(f.kernel.canUndo,true);assert.equal(f.kernel.canRedo,false);f.setEnqueue(false);await f.kernel.undo();assert.equal(f.kernel.canRedo,true);});
test('failed redo preserves history for retry',async()=>{const f=fixture();await f.kernel.execute([{type:'deck.update',title:'After'}]);await f.kernel.undo();f.setEnqueue(true);await assert.rejects(f.kernel.redo(),/storage failed/);assert.equal(f.kernel.canRedo,true);assert.equal(f.kernel.canUndo,false);f.setEnqueue(false);await f.kernel.redo();assert.equal(f.kernel.current.document.title,'After');assert.equal(f.kernel.canUndo,true);});
test('rapid undo and redo follow command admission order',async()=>{const f=fixture();const first=f.kernel.execute([{type:'deck.update',title:'First'}]);const second=f.kernel.execute([{type:'deck.update',title:'Second'}]);const undo1=f.kernel.undo(),undo2=f.kernel.undo();await Promise.all([first,second,undo1,undo2]);assert.equal(f.kernel.current.document.title,'Before');await Promise.all([f.kernel.redo(),f.kernel.redo()]);assert.equal(f.kernel.current.document.title,'Second');});
test('failed inverse redo keeps its target for retry',async()=>{const f=fixture();await f.kernel.execute([{type:'deck.update',title:'After'}]);f.kernel.acknowledge(f.queue[0].request.mutationId,2);await f.kernel.undo();const inverse=f.queue.at(-1)!.request.mutationId;f.setEnqueue(true);await assert.rejects(f.kernel.redo(),/storage failed/);assert.equal(f.kernel.canRedo,true);f.setEnqueue(false);await f.kernel.redo();assert.equal(f.queue.at(-1)!.historyAction,'redo');assert.equal(f.queue.at(-1)!.inverseMutationId,inverse);});
