import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {importHtml} from '@notale/editor';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React layers preserve row identity across edits and support search, multi-selection and page changes',async({page})=>{
 const id=randomUUID(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'图层列表',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:importHtml('<html><body><main id="stage" data-notale-id="stage"><h1 data-notale-id="a">Alpha</h1><p data-notale-id="b">Beta</p></main></body></html>').html},{id:'second',name:'第二页',sourcePath:'second.html',html:importHtml('<html><body><main id="stage" data-notale-id="stage"><p data-notale-id="c">Gamma</p></main></body></html>').html}]}});expect(response.ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await page.locator('[data-tool="objects"]').click();await expect(page.locator('[data-object="a"]')).toBeVisible();await page.locator('[data-object="a"]').evaluate(node=>{(window as any).__layerNode=node;});
 await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target:'a',patch:{text:'Alpha updated'}}]));await expect(page.locator('[data-object="a"]')).toContainText('Alpha updated');expect(await page.locator('[data-object="a"]').evaluate(node=>node===(window as any).__layerNode)).toBe(true);
 await page.locator('#object-search').fill('no-such-object');await expect(page.getByRole('status').filter({hasText:'没有匹配的对象'})).toBeVisible();await page.locator('#object-search').press('Escape');await expect(page.locator('#object-search')).toHaveValue('');await page.locator('#object-search').fill('beta');await expect(page.locator('#objects button')).toHaveCount(1);await expect(page.locator('[data-object="b"]')).toBeVisible();await page.locator('#object-search').press('Enter');await expect(page.locator('[data-object="b"]')).toBeFocused();await page.locator('#object-search').fill('');
 await page.locator('[data-object="a"]').click();expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSelection())).toEqual(['a']);await expect(page.locator('[data-object="a"]')).toBeVisible();await page.locator('[data-object="a"]').press('ArrowDown');await expect(page.locator('[data-object="b"]')).toBeFocused();await page.locator('[data-object="b"]').press('Home');await expect(page.locator('[data-object="a"]')).toHaveAttribute('aria-pressed','true');await page.locator('[data-object="b"]').click({modifiers:['Shift']});expect((await page.evaluate(()=>(window as any).NotaleWorkbench.getSelection())).sort()).toEqual(['a','b']);
 await page.locator('[data-object="a"]').click();await page.locator('[data-object="a"]').press('F2');const name=page.getByRole('textbox',{name:'图层名称',exact:true});await expect(name).toBeFocused();await name.fill('取消的名称');await name.press('Escape');await expect(page.locator('[data-object="a"]')).toContainText('Alpha updated');await page.locator('[data-object="a"]').dblclick();await name.fill('主要标题');await name.press('Enter');await expect(page.locator('[data-object="a"]')).toContainText('主要标题');await expect(page.locator('[data-object="a"]')).toBeFocused();await page.locator('[data-object="a"]').press('F2');await name.fill('重命名标题');await page.locator('#object-search').click();await expect(page.locator('[data-object="a"]')).toContainText('重命名标题');await expect(page.locator('#object-search')).toBeFocused();
 await page.evaluate(()=>(window as any).NotaleWorkbench.showSlide('second'));await expect(page.locator('[data-object="c"]')).toBeVisible();await expect(page.locator('[data-object="a"]')).toHaveCount(0);await expect(page.locator('[data-object="b"]')).toHaveCount(0);expect(errors).toEqual([]);
});
