import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React links insert, preserve conflicting drafts and remove only link attributes',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'链接编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'chapter/first.html',html:'<html><body><main data-notale-id="stage" style="width:1600px;height:900px"><a data-notale-id="link" href="https://example.com"><span data-notale-id="label">保留文字</span></a></main></body></html>'},{id:'second',name:'第二页',sourcePath:'second.html',html:'<html><body>第二页</body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.locator('[data-tool="insert"]').click();await page.locator('[data-insert-category="interactive"] > summary').click();await page.locator('#open-link-insert').click();await expect(page.locator('#link-insert-dialog')).toBeVisible();await page.locator('#link-page').selectOption('second');await page.locator('#link-label').fill('下一段');await page.locator('#insert-link').click();await expect(page.locator('#link-insert-dialog')).toHaveCount(0);await expect(page.frameLocator('#canvas').getByText('下一段',{exact:true})).toHaveAttribute('href',/\/second\.html$/);
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('label'));await expect(page.locator('#link-editor')).toBeVisible();await page.locator('#link-url').fill('example.org/updated');await page.locator('#link-url').press('Enter');const anchor=page.frameLocator('#canvas').locator('[data-notale-id="link"]');await expect(anchor).toHaveAttribute('href','https://example.org/updated');
 await page.locator('#link-url').fill('https://example.org/draft');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target:'link',patch:{attributes:{href:'https://example.net/remote'}}}]));await page.locator('#update-link').click();await expect(page.locator('#link-status')).toContainText('链接已变化');await expect(page.locator('#link-url')).toHaveValue('https://example.org/draft');
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('stage'));await page.evaluate(()=>(window as any).NotaleWorkbench.select('label'));await page.locator('#remove-link').click();await expect(anchor).not.toHaveAttribute('href',/.+/);await expect(anchor).toHaveText('保留文字');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).toContain('下一段');expect(saved.document.slides[0].html).toContain('../second.html');expect(saved.document.slides[0].html).not.toContain('https://example.net/remote');
});
