import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React file picker replaces media and rejects an upload that finishes after switching pages',async({page})=>{
 const id=randomUUID(),png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9V8AAAAASUVORK5CYII=';
 expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Picker',width:1600,height:900,slides:['first','second'].map(id=>({id,name:id,sourcePath:id+'.html',html:`<html><body><picture data-notale-id="picture"><source data-notale-id="source" type="image/png" srcset="data:image/png;base64,${png}"><img data-notale-id="photo" src="data:image/png;base64,${png}" style="width:100px;height:100px"></picture></body></html>`}))}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('photo'));
 const choose=async()=>{const choosing=page.waitForEvent('filechooser');await page.locator('#replace-media').click();await (await choosing).setFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});};
 await choose();await expect.poll(async()=>Object.keys((await page.request.get('/api/documents/'+id).then(r=>r.json())).document.assets).length).toBe(1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const displayed=page.frameLocator('#canvas').locator('[data-notale-id="photo"]');await expect.poll(()=>displayed.evaluate(node=>{const image=node as HTMLImageElement;return image.complete&&image.naturalWidth>0&&image.currentSrc===image.src&&!image.currentSrc.startsWith('data:');})).toBe(true);expect(await page.frameLocator('#canvas').locator('[data-notale-id="source"]').getAttribute('srcset')).toBe(await displayed.getAttribute('src'));
 let releaseReplacement!:()=>void,enteredReplacement!:()=>void;const replacementGate=new Promise<void>(resolve=>releaseReplacement=resolve),replacementStarted=new Promise<void>(resolve=>enteredReplacement=resolve);
 await page.route('**/api/assets',async route=>{enteredReplacement();await replacementGate;await route.continue();});
 try{await choose();await replacementStarted;await page.evaluate(png=> (window as any).NotaleWorkbench.commands([{type:'media.update',slideId:'first',target:'photo',patch:{src:'data:image/png;base64,'+png}}]),png);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const changed=await page.request.get('/api/documents/'+id).then(r=>r.json());releaseReplacement();await expect(page.getByText('目标媒体已变化，未覆盖新的内容，请重新选择文件',{exact:true})).toBeVisible();const unchanged=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(unchanged.version).toBe(changed.version);expect(unchanged.document.slides).toEqual(changed.document.slides);}finally{releaseReplacement();await page.unroute('**/api/assets');}
 const before=await page.request.get('/api/documents/'+id).then(r=>r.json());let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{entered=resolve;});
 await page.route('**/api/assets',async route=>{entered();await gate;await route.continue();});
 try{await choose();await started;await page.evaluate(()=>(window as any).NotaleWorkbench.showSlide('second'));release();await expect(page.getByText('页面已切换，请重新选择媒体',{exact:true})).toBeVisible();const after=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(after.version).toBe(before.version);expect(after.document.slides).toEqual(before.document.slides);}finally{release();}
});
