import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';

test.use({baseURL:process.env.NEXT_TEST_URL??'http://127.0.0.1:4312'});
test('React shell preserves canvas editing, shortcuts and persistence',async({page})=>{
  const id=randomUUID(),faults:string[]=[];
  page.on('pageerror',e=>faults.push(e.message));
  const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Next.js 迁移验证',width:1600,height:900,slides:[{id:'first',name:'验证',sourcePath:'first.html',html:'<!doctype html><html><body style="margin:0"><main id="stage" data-notale-id="stage" style="position:absolute;width:1600px;height:900px"><h1 data-notale-id="heading" style="position:absolute;left:180px;top:180px;width:500px;height:80px;margin:0;font-size:40px">迁移前后的编辑体验</h1></main></body></html>'}]}});
  expect(response.status(),await response.text()).toBe(201);
  await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());
  const ready=()=>page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
  await ready();
  if(!process.env.NEXT_COMPARE_LEGACY)expect(await page.locator('script[src*="/_next/"]').count()).toBeGreaterThan(0);
  const heading=page.frameLocator('#canvas').locator('[data-notale-id="heading"]');
  const r=await heading.evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,v:innerWidth};});
  const f=await page.locator('#canvas').boundingBox();expect(f).not.toBeNull();
  const scale=f!.width/r.v,x=f!.x+(r.x+r.w/2)*scale,y=f!.y+(r.y+r.h/2)*scale;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+50,y+30,{steps:5});await page.mouse.up();
  await expect.poll(()=>heading.evaluate(e=>e.getBoundingClientRect().x)).toBeGreaterThan(r.x+20);
  await page.evaluate(()=>(window as any).NotaleWorkbench.whenEditsIdle());
  await page.locator('#undo').click();
  await expect.poll(()=>heading.evaluate(e=>e.getBoundingClientRect().x)).toBeCloseTo(r.x,0);
  await page.locator('#redo').click();
  await expect.poll(()=>heading.evaluate(e=>e.getBoundingClientRect().x)).toBeGreaterThan(r.x+20);
  await page.keyboard.press('Control+d');
  await expect(page.frameLocator('#canvas').locator('h1')).toHaveCount(2);
  await ready();await page.keyboard.press('Control+z');
  await expect(page.frameLocator('#canvas').locator('h1')).toHaveCount(1);
  await ready();await page.keyboard.press('Control+Shift+z');
  await expect(page.frameLocator('#canvas').locator('h1')).toHaveCount(2);
  await ready();
  await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target:'heading',patch:{text:'Next.js 保存验证'}}]));
  await ready();await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await ready();
  await expect(heading).toHaveText('Next.js 保存验证');
  expect(await heading.evaluate(e=>e.getBoundingClientRect().x)).toBeGreaterThan(r.x+20);
  await page.keyboard.press('Control+z');
  await expect(heading).toHaveText('迁移前后的编辑体验');await ready();
  await page.keyboard.press('Control+Shift+z');
  await expect(heading).toHaveText('Next.js 保存验证');await ready();
  await page.locator('[data-tool="insert"]').click();await expect(page.locator('#insert-drawer')).toBeVisible();
  await page.locator('[data-tool="templates"]').click();await expect(page.locator('.template-card')).toHaveCount(8);
  expect(faults).toEqual([]);
});
