import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('context format preserves selected text, saved HTML and live canvas',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const doc={schemaVersion:1,id:randomUUID(),title:'Context formatting acceptance',width:1600,height:900,slides:[{id:'page',name:'Page',sourcePath:'page.html',animations:[],html:'<html><body><h1 data-notale-id="heading" style="position:absolute;left:100px;top:100px;width:1000px;height:100px;font-size:48px">Text</h1></body></html>'}]};
 doc.slides[0].html=doc.slides[0].html.replace(/(<h1[^>]*>)[\s\S]*?(<\/h1>)/,'$1交互文字 <b data-notale-id="context-bold">原有粗体</b> <a data-notale-id="context-link" href="https://example.com">链接</a>$2');
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
 await page.goto('/?document='+doc.id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const heading=page.frameLocator('#canvas').locator('h1');await heading.click({button:'right',position:{x:40,y:25}});
 await expect(page.locator('.object-mini-toolbar')).toBeVisible();await expect(page.locator('[data-action="arrange"]')).toBeVisible();await page.locator('[data-action="arrange"]').focus();await page.keyboard.press('Enter');await expect(page.locator('.object-submenu')).toBeVisible();await expect(page.locator('[data-action="arrange"]')).toHaveAttribute('aria-expanded','true');await expect(page.locator('.object-submenu button').first()).toBeFocused();await page.keyboard.press('ArrowLeft');await expect(page.locator('.object-submenu')).toHaveCount(0);await expect(page.locator('[data-action="arrange"]')).toBeFocused();const size=page.locator('.object-mini-toolbar input[type="number"]').first();const original=await size.inputValue();await size.fill('99');await size.press('Escape');await expect(size).toHaveValue(original);await expect(page.locator('#object-context-menu')).toBeVisible();await size.blur();await expect(heading).toHaveCSS('font-size','48px');
 await page.keyboard.press('Escape');await heading.dblclick({position:{x:40,y:25}});await expect(heading).toHaveAttribute('contenteditable','true');
 await heading.evaluate(el=>{(window as any).__contextSentinel=77;const text=document.createTreeWalker(el,NodeFilter.SHOW_TEXT).nextNode()!;const range=document.createRange();range.setStart(text,0);range.setEnd(text,2);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));});
 await heading.evaluate(el=>{el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:300,clientY:200}));});
 await expect(page.locator('[data-action="clear-format"]')).toBeVisible();await expect(page.locator('[data-action="delete"]')).toHaveCount(0);
 await page.locator('[data-format="color"]').fill('#dd2244');await page.locator('[data-format="color"]').dispatchEvent('change');
 await expect.poll(()=>heading.innerHTML()).toContain('color: rgb(221, 34, 68)');
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBeGreaterThan(1);
 expect(await heading.locator('[data-notale-id="context-bold"]').textContent()).toBe('原有粗体');
 expect(await heading.locator('[data-notale-id="context-link"]').getAttribute('href')).toBe('https://example.com');
 expect(await heading.evaluate(()=>(window as any).__contextSentinel)).toBe(77);
 await page.keyboard.press('Escape');await heading.press('End');await page.keyboard.insertText('继续输入');
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].html)).toContain('继续输入');
 await heading.press('Escape');await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await expect(heading).toContainText('继续输入');expect(await heading.innerHTML()).toContain('color: rgb(221, 34, 68)');
 await heading.click({button:'right',position:{x:40,y:25}});
 await page.locator('[data-action="lock"]').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].locked.length)).toBe(1);
 await heading.click({button:'right',position:{x:40,y:25}});await expect(page.locator('[data-action="delete"]')).toBeDisabled();await page.locator('[data-action="lock"]').click();
 await expect.poll(()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0].locked.length)).toBe(0);
 expect(errors).toEqual([]);
});
