import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React page settings save timing, preserve conflicts and apply a master',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'页面设置',width:1600,height:900,layouts:[{id:'master',name:'页脚母版',html:'<footer data-notale-placeholder="footer">页脚</footer><img data-notale-image-placeholder="photo">',css:''}],slides:[{id:'first',name:'原页',sourcePath:'first.html',html:'<html><body><main data-notale-id="stage">原页</main></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await page.locator('[data-tool="pages"]').click();const card=page.locator('[data-slide="first"]');await card.focus();await page.keyboard.press('F2');const dialog=page.locator('#page-settings-dialog');await expect(dialog).toBeVisible();await page.locator('#page-settings-name').fill('章节开场');await page.locator('#page-settings-section').fill('第一章');await dialog.locator('summary').filter({hasText:'切换与计时'}).click();await page.locator('#page-settings-transition').selectOption('fade');await page.locator('#page-settings-auto').check();await page.locator('#page-settings-seconds').fill('2.5');await page.locator('#save-page-settings').click();await expect(dialog).not.toBeVisible();
 const snapshot=()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().document.slides[0]);await expect.poll(async()=>(await snapshot()).advanceAfter).toBe(2500);expect((await snapshot()).transition).toBe('fade');expect((await snapshot()).section).toBe('第一章');
 await card.click({button:'right'});await page.locator('#page-settings-name').fill('保留输入');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'slide.update',slideId:'first',patch:{name:'外部更新'}}]));await page.locator('#save-page-settings').click();await expect(page.locator('#page-settings-status')).toContainText('已被更新');await expect(page.locator('#page-settings-name')).toHaveValue('保留输入');await page.locator('#close-page-settings').click();
 await page.locator('#open-page-settings').click();await page.locator('#page-master-settings summary').click();await page.locator('#page-master-choice').selectOption('master');await page.locator('#page-master-apply').click();await expect.poll(async()=>(await snapshot()).layoutId).toBe('master');await expect(page.locator('#layout-values')).toBeVisible();
 const text=page.locator('#layout-values textarea[data-key="footer"]');await text.fill('本页页脚');await page.locator('#save-layout-values').click();await expect.poll(async()=>(await snapshot()).layoutValues?.master?.footer).toBe('本页页脚');
 await text.fill('保留草稿');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'layout.values',slideId:'first',id:'master',values:{footer:'远端页脚'}}]));await page.locator('#save-layout-values').click();await expect(page.locator('#layout-values [role="status"]')).toContainText('已变化');await expect(text).toHaveValue('保留草稿');await page.locator('#close-page-settings').click();await page.locator('#open-page-settings').click();await expect(text).toHaveValue('远端页脚');await page.locator('#reset-layout-values').click();await expect(text).toHaveValue('页脚');
 await page.locator('[data-image-key="photo"]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9V8AAAAASUVORK5CYII=','base64')});await expect.poll(async()=>(await snapshot()).layoutImages?.master?.photo?.path).toMatch(/^media\//);await page.locator('[data-reset-image="photo"]').click();await expect.poll(async()=>(await snapshot()).layoutImages?.master?.photo??null).toBeNull();
 await page.locator('#page-master-detach').click();await expect.poll(async()=>(await snapshot()).layoutId).toBeNull();await page.locator('#close-page-settings').click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].name).toBe('外部更新');expect(saved.document.slides[0].advanceAfter).toBe(2500);
});
