import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {importHtml} from '@notale/editor';
import {newChart,mediaSettingsSchema} from '@notale/editor/browser';
test.use({baseURL:process.env.PRESENT_TEST_URL??'http://127.0.0.1:4362'});
async function ready(page:Page,control='controlling'){await page.waitForFunction(control=>(window as any).NotaleShow?.state().ready&&(window as any).NotaleShow.state().control===control,control);}
const state=(p:Page)=>p.evaluate(()=>(window as any).NotaleShow.state());
const current=(p:Page)=>p.frameLocator('.ps-reveal section.present iframe');
async function clickInSlide(page:Page,selector:string){const item=await current(page).locator(selector).evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,width:innerWidth};});const frame=(await page.locator('.ps-reveal section.present iframe').boundingBox())!;await page.mouse.click(frame.x+item.x*frame.width/item.width,frame.y+item.y*frame.width/item.width);}
const html=(title:string,content:string)=>importHtml(`<!doctype html><html><head><style>body{margin:0;font-family:Arial,sans-serif;background:#f5f3ef;color:#242731}#stage{position:relative;box-sizing:border-box;padding:80px;width:1600px;height:900px}h1{font-size:64px;margin:15px 0 30px}p{font-size:26px;line-height:1.6}button{padding:15px 28px;font-size:24px;border:0;border-radius:10px;background:#7054c8;color:white}input{width:350px}canvas{background:white}</style></head><body><main id="stage" data-notale-id="stage"><p style="font-size:18px;letter-spacing:4px;color:#887ba4">NOTALE / 互动讲授</p><h1>${title}</h1>${content}</main></body></html>`).html;
async function fixture(page:Page){
 const id=randomUUID();const model=newChart('bar');
 const wav=Buffer.alloc(44+8000);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(8000,28);wav.writeUInt16LE(1,32);wav.writeUInt16LE(8,34);wav.write('data',36);wav.writeUInt32LE(8000,40);wav.fill(128,44);
 const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'让复杂知识，看得见',width:1600,height:900,slides:[
 {id:'first',name:'先观察，再理解',sourcePath:'first.html',notes:'今天我们从一个问题开始：为什么多个模型一起判断，结果会更稳定？\n\n先让大家观察图表，再用滑块改变条件。留一点时间，让学生说出自己的猜想。',steps:[{id:'start',name:'引入问题'},{id:'compare',name:'揭示关键观察',notes:'提醒大家关注结果之间的差异，而不是单个数值。'}],animations:[{id:'intro',target:'detail',step:1,trigger:'click',effect:'fade-in'}],html:html('先观察，再理解','<p>把课堂里的“如果……”变成一次可以亲手尝试的实验。</p><div data-notale-id="detail" style="margin-top:65px;padding:45px;border-radius:18px;background:#e6e0f1;font-size:40px">改变一个条件，发现新的规律。</div>')},
 {id:'charts',name:'用数据解释变化',sourcePath:'charts.html',notes:'拖动参数，让大家观察同步变化。\n图例可以直接点击，比较不同系列。',nativeCharts:{chart:{adapter:'echarts',option:{},authoring:model}},html:html('用数据解释变化','<div data-notale-id="chart" style="width:1200px;height:440px"></div><p><label>参数 <input data-notale-id="range" type="range" min="0" max="100" value="20" oninput="document.getElementById(\'result\').textContent=this.value"></label> <strong data-notale-id="result" id="result">20</strong></p>')},
 {id:'simulation',name:'相同结果，一起看见',sourcePath:'simulation.html',notes:'这个例子只在老师的窗口生成随机结果。观众收到完全相同的状态。',html:html('相同结果，一起看见',`<div data-notale-id="simulation"><canvas data-notale-id="plot" id="plot" width="1100" height="320"></canvas><p data-notale-id="sample" id="sample">0</p><button data-notale-id="resample" id="resample">重新采样</button></div><audio data-notale-id="audio" controls data-notale-media='${JSON.stringify(mediaSettingsSchema.parse({controls:true}))}' src="data:audio/wav;base64,${wav.toString('base64')}"></audio><script>let sample={value:0};function draw(){document.getElementById('sample').textContent=String(sample.value);const c=document.getElementById('plot').getContext('2d');c.clearRect(0,0,1100,320);c.fillStyle='#7054c8';c.fillRect(60,60,100+sample.value,180);}document.getElementById('resample').onclick=()=>{sample.value=1+Math.floor(Math.random()*799);draw();};window.__NOTALE_PRESENTATION_ADAPTERS__={simulation:{capture:()=>({...sample}),apply:value=>{sample={...value};draw();}}};draw();</script>`)}
 ]}});expect(response.status(),await response.text()).toBe(201);return id;
}
test('presenter workspace keeps private controls and synchronizes interactions',async({page})=>{
 const id=await fixture(page);const before=await page.request.get('/api/documents/'+id).then(r=>r.json());
 await page.goto('/present?document='+id+'&speaker=1',{waitUntil:'domcontentloaded'});await ready(page);
 await expect(page.locator('#speaker-panel')).toBeVisible();await expect(page.locator('#notes')).toContainText('为什么多个模型');
 await current(page).locator('#stage').evaluate(()=>{(window as any).__retained={};(window as any).__marker=(window as any).__retained;});
 await expect(page.frameLocator('#next-preview').locator('[data-notale-id="detail"]')).toHaveCSS('opacity','1');
 await page.getByText('显示选项',{exact:true}).click();await page.locator('#audience').focus();await page.keyboard.press('Escape');await expect(page.locator('.ps-display-menu')).not.toHaveAttribute('open','');await expect(page.locator('.ps-display-menu summary')).toBeFocused();expect((await state(page)).slideId).toBe('first');await page.getByText('显示选项',{exact:true}).click();await page.locator('.ps-title').click();await expect(page.locator('.ps-display-menu')).not.toHaveAttribute('open','');await page.getByText('显示选项',{exact:true}).click();const opened=page.waitForEvent('popup');await page.locator('#audience').click();const audience=await opened;await ready(audience,'audience');
 await expect(audience.locator('#speaker-panel')).toHaveCount(0);await expect(audience.locator('.ps-floating-controls')).toHaveCount(0);
 await page.locator('#next').click();await expect.poll(async()=>(await state(audience)).step).toBe(1);
 await page.locator('#blank').click();await expect(audience.locator('.ps-blackout')).toBeVisible();await expect(page.locator('.ps-blackout')).toHaveCount(0);
 await page.locator('#blank').click();await page.getByRole('button',{name:'暂停计时',exact:true}).click();expect((await state(page)).timer.runningSince).toBeNull();
 expect(await current(page).locator('#stage').evaluate(()=>(window as any).__retained===(window as any).__marker)).toBe(true);
 await page.locator('#next').click();await expect.poll(async()=>(await state(page)).slideId).toBe('charts');await expect.poll(async()=>(await state(audience)).slideId).toBe('charts');
 await expect(current(page).locator('[data-notale-id="chart"] canvas')).toHaveCount(1);
 await current(page).locator('[data-notale-id="range"]').evaluate((input:HTMLInputElement)=>{input.value='73';input.dispatchEvent(new Event('input',{bubbles:true}));});await expect(current(audience).locator('#result')).toHaveText('73');expect((await state(page)).slideId).toBe('charts');
 await current(page).locator('[data-notale-id="chart"]').evaluate((el:HTMLElement)=>{const engine=(window as any).__NOTALE_CHART_ENGINE__??(window as any).echarts;engine.getInstanceByDom(el).dispatchAction({type:'legendUnSelect',name:engine.getInstanceByDom(el).getOption().series[0].name});});
 await expect.poll(async()=>JSON.stringify((await state(audience)).runtime.charts?.charts)).toBe(JSON.stringify((await state(page)).runtime.charts?.charts));
 await page.getByRole('button',{name:'激光笔 · L',exact:true}).click();const surface=page.locator('.ps-current .ps-ink');await expect(surface).toHaveClass(/ps-tool-laser/);const bounds=(await surface.boundingBox())!;await page.bringToFront();await page.mouse.move(bounds.x+bounds.width*.4,bounds.y+bounds.height*.4,{steps:3});await expect(page.locator('.ps-current .ps-laser')).toBeVisible();await expect(audience.locator('.ps-laser')).toBeVisible();
 await page.getByRole('button',{name:'画笔 · P',exact:true}).click();await page.mouse.move(bounds.x+80,bounds.y+80);await page.mouse.down();await page.mouse.move(bounds.x+150,bounds.y+120,{steps:3});await page.mouse.up();await expect.poll(async()=>Object.values((await state(audience)).annotations).join('').length).toBeGreaterThan(20);
 await page.getByRole('button',{name:'指针 · 操作互动内容',exact:true}).click();await page.locator('#overview').click();await expect.poll(async()=>(await state(audience)).slideId).toBe('charts');await page.getByRole('button',{name:'3 相同结果，一起看见'}).click();await expect.poll(async()=>(await state(audience)).slideId).toBe('simulation');
 await current(page).locator('#resample').focus();await current(page).locator('#resample').press('Space');expect((await state(page)).ended).toBe(false);expect((await state(page)).slideId).toBe('simulation');await expect(current(page).locator('#sample')).not.toHaveText('0');await expect.poll(async()=>await current(audience).locator('#sample').textContent()).toBe(await current(page).locator('#sample').textContent());
 await current(page).locator('audio').evaluate((el:HTMLMediaElement)=>{el.pause();el.volume=.35;});await expect.poll(()=>current(audience).locator('audio').evaluate((el:HTMLMediaElement)=>el.volume)).toBe(.35);expect(await current(audience).locator('audio').evaluate((el:HTMLMediaElement)=>el.paused)).toBe(true);
 await audience.getByRole('button',{name:'仅启用声音',exact:true}).click();
 await current(page).locator('audio').evaluate((el:HTMLMediaElement)=>el.play());await expect.poll(()=>current(audience).locator('audio').evaluate((el:HTMLMediaElement)=>el.muted)).toBe(false);expect(await current(page).locator('audio').evaluate((el:HTMLMediaElement)=>el.muted)).toBe(true);
 await audience.reload({waitUntil:'domcontentloaded'});await ready(audience,'audience');await expect(current(audience).locator('#sample')).toHaveText(await current(page).locator('#sample').textContent()??'');
 await page.setViewportSize({width:1366,height:768});await page.screenshot({path:'.local/presenter-workspace.png'});
 expect(await page.request.get('/api/documents/'+id).then(r=>r.json())).toEqual(before);await audience.close();
});
