import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:'http://127.0.0.1:4399'});
test('attribute-only source updates reach audience without changing the document',async({page})=>{
 await page.context().addInitScript(()=>{const original=BroadcastChannel.prototype.postMessage;BroadcastChannel.prototype.postMessage=function(value:any){if(value?.kind==='apply-status'&&value.failed===true&&!(window as any).__droppedApplyStatus){(window as any).__droppedApplyStatus=true;return;}return original.call(this,value);};});
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'属性同步',width:1600,height:900,slides:[{id:'page',name:'页面',sourcePath:'page.html',html:'<html><body><svg data-notale-id="chart" width="500" height="300"><circle data-notale-id="dot" cx="50" cy="50" r="20" fill="red"/></svg></body></html>'}]}})).ok()).toBe(true);
 const before=await page.request.get('/api/documents/'+id).then(r=>r.json());
 await page.goto('/present?document='+id+'&speaker=1');await page.waitForFunction(()=>(window as any).NotaleShow?.state().ready&&(window as any).NotaleShow.state().control==='controlling');await page.getByText('显示选项',{exact:true}).click();const popup=page.waitForEvent('popup');await page.locator('#audience').click();const audience=await popup;await audience.waitForFunction(()=>(window as any).NotaleShow?.state().ready&&(window as any).NotaleShow.state().control==='audience');
 const current=(p:typeof page)=>p.frameLocator('.ps-reveal section.present iframe').locator('[data-notale-id="dot"]');await current(page).evaluate(node=>{node.setAttribute('fill','blue');node.setAttribute('cx','120');node.setAttribute('style','opacity:0.5');});await expect(current(audience)).toHaveAttribute('fill','blue');await expect(current(audience)).toHaveAttribute('cx','120');await expect(current(audience)).toHaveAttribute('style','opacity:0.5');await current(audience).evaluate(node=>{(window as any).__originalDot=node;});await current(page).evaluate(node=>node.parentElement!.setAttribute('style','visibility:hidden;transform:translateX(15px)'));await expect(current(audience).locator('..')).toHaveAttribute('style','visibility:hidden;transform:translateX(15px)');await current(page).evaluate(node=>node.parentElement!.removeAttribute('style'));await expect(current(audience).locator('..')).not.toHaveAttribute('style');expect(await current(audience).evaluate(node=>(window as any).__originalDot===node)).toBe(true);expect(await page.request.get('/api/documents/'+id).then(r=>r.json())).toEqual(before);await current(audience).evaluate(()=>{(window as any).__NOTALE_CHART_ENGINE__={getInstanceByDom:(el:Element)=>el.getAttribute('data-notale-id')==='chart'?{getOption:()=>({series:[]}),setOption:()=>{}}:undefined};});await current(page).evaluate(node=>{
 const w=window as any;w.__chartSubscriptions=[];
 w.__makeChart=()=>{const calls={on:0,off:0};w.__chartSubscriptions.push(calls);return {getOption:()=>({series:[]}),on:()=>calls.on++,off:()=>calls.off++};};
 w.__lateChart=w.__makeChart();w.__NOTALE_CHART_ENGINE__={getInstanceByDom:(el:Element)=>el.getAttribute('data-notale-id')==='chart'?w.__lateChart:undefined};node.setAttribute('fill','green');
});await expect.poll(()=>current(page).evaluate(()=>(window as any).__chartSubscriptions[0].on)).toBe(4);
await current(page).evaluate(node=>{const w=window as any;w.__lateChart=w.__makeChart();node.setAttribute('fill','orange');});await expect.poll(()=>current(page).evaluate(()=>(window as any).__chartSubscriptions.map((v:any)=>[v.on,v.off]))).toEqual([[4,4],[4,0]]);
await current(page).evaluate(node=>{(window as any).__lateChart=undefined;node.setAttribute('fill','purple');});await expect.poll(()=>current(page).evaluate(()=>(window as any).__chartSubscriptions[1].off)).toBe(4);
await current(audience).evaluate(()=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__={broken:{capture:()=>({}),apply:()=>{}}};});await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__={broken:{capture:()=>({}),apply:()=>{},subscribe:()=>{throw Error('broken subscription');}}};node.setAttribute('fill','cyan');});await expect(current(audience)).toHaveAttribute('fill','cyan');await expect(page.locator('body')).toContainText('部分互动内容的状态监听暂不可用');await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__={};node.setAttribute('fill','pink');});await expect(current(audience)).toHaveAttribute('fill','pink');await expect(page.locator('body')).not.toContainText('部分互动内容的状态监听暂不可用');
await current(audience).evaluate(()=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__={failing:{capture:()=>0,apply:()=>{throw Error('restore failed');}}};});await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__={failing:{capture:()=>1,apply:()=>{}}};node.setAttribute('fill','gold');});await expect(current(audience)).toHaveAttribute('fill','gold');await expect(page.locator('body')).toContainText('部分互动内容未能更新');expect(await audience.evaluate(()=>(window as any).__droppedApplyStatus)).toBe(true);await page.getByRole('button',{name:'关闭提示',exact:true}).click();await current(page).evaluate(node=>node.setAttribute('cx','130'));await expect(current(audience)).toHaveAttribute('cx','130');await expect(page.locator('body')).not.toContainText('部分互动内容未能更新');await current(audience).evaluate(()=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing.apply=()=>{};});await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing.capture=()=>2;node.setAttribute('fill','silver');});await expect(current(audience)).toHaveAttribute('fill','silver');await expect(page.locator('body')).not.toContainText('部分互动内容未能更新');
await current(audience).evaluate(()=>{delete (window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing;});await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing.capture=()=>3;node.setAttribute('fill','tan');});await expect(current(audience)).toHaveAttribute('fill','tan');await expect(page.locator('body')).toContainText('部分互动内容未能更新');await current(audience).evaluate(()=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing={capture:()=>0,apply:(value:unknown)=>{(window as any).__recoveredValue=value;}};});await expect.poll(()=>current(audience).evaluate(()=>(window as any).__recoveredValue)).toBe(3);await expect(page.locator('body')).not.toContainText('部分互动内容未能更新');await current(audience).evaluate(()=>{delete (window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing;});await current(page).evaluate(node=>{(window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing.capture=()=>4;node.setAttribute('fill','navy');});await expect(page.locator('body')).toContainText('部分互动内容未能更新');await current(page).evaluate(node=>{delete (window as any).__NOTALE_PRESENTATION_ADAPTERS__.failing;node.setAttribute('fill','lime');});await expect(current(audience)).toHaveAttribute('fill','lime');await expect.poll(()=>audience.evaluate(()=>(window as any).NotaleShow.state().runtime.page.scenes.failing)).toBeUndefined();await expect(page.locator('body')).not.toContainText('部分互动内容未能更新');await audience.close();
});
