import { test, expect, type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
const original='f5d596d1-0584-4de4-ada6-ecf918147cd4';
const ready=(page:Page)=>page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
const snapshot=(page:Page)=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot());
async function setup(page:Page) {
  const baseline=await (await page.request.get('/api/documents/'+original)).json();
  const doc=structuredClone(baseline.document);doc.id=randomUUID();doc.title='Preview dock acceptance';doc.slides=[doc.slides[6],doc.slides[19]];
  expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
  await page.goto('/?document='+doc.id);await ready(page);return {baseline,doc};
}
test('floating preview preserves editing view, native interaction, steps and origin isolation',async({page})=>{
  const {baseline}=await setup(page);
  const faults:string[]=[];page.on('pageerror',e=>faults.push(e.message));
  await page.route(/:431[01]\//,r=>r.abort());
  await page.locator('[data-tool="objects"]').click();
  await page.locator('#canvas-zoom').selectOption('1');
  await page.locator('#canvas-viewport').evaluate(el=>el.scrollTo(70,40));
  await page.evaluate(()=>{const w=(window as any).NotaleWorkbench;w.select(w.getObjects().find((o:any)=>o.tag==='h1').id);});
  const state=await page.evaluate(()=>({selection:(window as any).NotaleWorkbench.getSelection(),scroll:[document.getElementById('canvas-viewport')!.scrollLeft,document.getElementById('canvas-viewport')!.scrollTop],src:(document.getElementById('canvas') as HTMLIFrameElement).src}));
  const before=await snapshot(page);
  await page.locator('#interact').click();
  await expect(page.locator('#preview-overlay')).toBeVisible();
  await expect(page.locator('#preview-loading')).toBeHidden();
  const frame=page.frameLocator('#preview-canvas');
  const canvas=frame.locator('#matrix-canvas');
  const pixels=await canvas.evaluate((el:HTMLCanvasElement)=>el.toDataURL());
  await frame.locator('#m-slider').fill('31');
  await expect(frame.locator('#m-val')).toHaveText('31');
  await expect.poll(()=>canvas.evaluate((el:HTMLCanvasElement)=>el.toDataURL())).not.toBe(pixels);
  expect(await frame.locator('body').evaluate(()=>{try{return !!parent.document;}catch{return false;}})).toBe(false);
  await page.screenshot({path:'.local/preview-overlay-desktop.png'});
  await page.locator('#preview-next').click();
  await expect(page.locator('#preview-position')).toHaveText('2 / 2 · 0 / 2');
  await page.locator('#preview-next').click();await page.locator('#preview-next').click();
  await expect(page.locator('#preview-position')).toHaveText('2 / 2 · 2 / 2');
  await expect(frame.locator('[data-step="2"]').first()).toHaveCSS('opacity','1');
  await page.locator('#preview-edit-toggle').click();
  await expect(page.locator('#preview-overlay')).toBeHidden();
  expect(await snapshot(page)).toEqual(before);
  expect(await page.evaluate(()=>({selection:(window as any).NotaleWorkbench.getSelection(),scroll:[document.getElementById('canvas-viewport')!.scrollLeft,document.getElementById('canvas-viewport')!.scrollTop],src:(document.getElementById('canvas') as HTMLIFrameElement).src}))).toEqual(state);
  await expect(page.locator('#property-panel')).toBeVisible();
  await page.screenshot({path:'.local/reference-floating-dock.png'});
  await page.locator('#interact').click();await expect(page.locator('#preview-loading')).toBeHidden();
  await page.keyboard.press('Escape');await expect(page.locator('#preview-overlay')).toBeHidden();
  expect(faults).toEqual([]);
  expect(await (await page.request.get('/api/documents/'+original)).json()).toEqual(baseline);
});
test('dock page commands, notes, preview failure recovery and narrow layout',async({page})=>{
  await setup(page);
  const initial=await snapshot(page);
  await page.locator('#dock-add-page').click();
  await expect.poll(async()=>(await snapshot(page)).document.slides.length).toBe(3);await ready(page);
  await page.locator('#dock-delete-page').click();
  await expect.poll(async()=>(await snapshot(page)).document.slides.length).toBe(2);await ready(page);
  await page.keyboard.press('Control+z');
  await expect.poll(async()=>(await snapshot(page)).document.slides.length).toBe(3);await ready(page);
  await page.keyboard.press('Control+z');
  await expect.poll(async()=>(await snapshot(page)).document.slides.length).toBe(2);await ready(page);
  await page.evaluate(() => { const w=(window as any).NotaleWorkbench; return w.showSlide(w.getSnapshot().document.slides[0].id); });
  await page.locator('#dock-next-page').click();await ready(page);
  await expect(page.locator('#page-position')).toHaveText('2 / 2');
  await page.locator('#dock-previous-page').click();await ready(page);
  await expect(page.locator('#page-position')).toHaveText('1 / 2');
  await page.locator('#toggle-notes').click();await page.locator('#notes').fill('预览底栏讲稿');await page.locator('#save-notes').click();
  await expect.poll(async()=>(await snapshot(page)).document.slides[0].notes).toBe('预览底栏讲稿');await ready(page);
  await page.locator('#toggle-notes').click();
  let block=true;await page.route('**/api/documents/*/preview?*',r=>block?r.fulfill({status:503,body:'unavailable'}):r.continue());
  await page.locator('#interact').click();await expect(page.locator('#preview-retry')).toBeVisible();
  block=false;await page.locator('#preview-retry').click();await expect(page.locator('#preview-loading')).toBeHidden();
  await page.locator('#preview-close').click();
  await page.route('**/api/documents/*/commits', r=>r.fulfill({status:503,body:'unavailable'}));
  const failedVersion=(await snapshot(page)).version;
  await page.evaluate(async()=>{const w=(window as any).NotaleWorkbench;try {await w.commands([{type:'slide.update',slideId:w.getSnapshot().document.slides[0].id,patch:{notes:'恢复保存后预览'}}]);}catch{}});
  await page.locator('#interact').click();
  await expect(page.locator('#preview-overlay')).toBeHidden();
  expect((await snapshot(page)).version).toBe(failedVersion);
  await page.unroute('**/api/documents/*/commits');await page.locator('#retry-save').click();
  await expect.poll(async()=>(await snapshot(page)).version).toBe(failedVersion+1);await ready(page);
  await page.setViewportSize({width:390,height:844});
  const dock=(await page.locator('.viewbar').boundingBox())!,toggle=(await page.locator('#interact').boundingBox())!;
  expect(dock.x).toBeGreaterThanOrEqual(0);expect(dock.x+dock.width).toBeLessThanOrEqual(390);expect(dock.y+dock.height).toBeLessThanOrEqual(toggle.y);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'.local/reference-floating-dock-mobile.png'});
  await page.locator('#interact').click();await expect(page.locator('#preview-loading')).toBeHidden();
  await page.screenshot({path:'.local/preview-overlay-mobile.png'});
  await page.locator('#preview-edit-toggle').click();
  expect((await snapshot(page)).document.id).toBe(initial.document.id);
});
