import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React rich text saves formatting and preserves conflicting input',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'富文本编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:'<html><body><p data-notale-id="text" style="position:absolute;left:100px;top:100px;font-style:italic;white-space:pre-wrap">原有文字 <a data-notale-id="link" href="https://example.com" target="_blank">链接</a></p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('text'));
 await page.locator('#open-rich-editor').click();const surface=page.locator('#rich-surface');await expect(surface).toContainText('原有文字');await expect(surface).toHaveCSS('font-style','italic');await expect(surface).toHaveCSS('white-space','pre-wrap');
 await surface.press('Control+Home');await surface.press('Control+Shift+End');await page.locator('[data-rich-command="bold"]').click();await expect(page.locator('[data-rich-command="bold"]')).toHaveAttribute('aria-pressed','true');await page.locator('[data-rich-command="justifyRight"]').click();await expect(page.locator('[data-rich-command="justifyRight"]')).toHaveAttribute('aria-pressed','true');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'deck.update',title:'无关标题修改'}]));await surface.press('Control+Enter');await expect(page.locator('#rich-editor-dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 let saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).toMatch(/font-weight:\s*(bold|700)/);expect(saved.document.slides[0].html).toContain('https://example.com');await expect(page.frameLocator('#canvas').locator('[data-notale-id="text"]')).toHaveText('原有文字 链接');await expect(page.frameLocator('#canvas').locator('[data-notale-id="text"]')).toHaveCSS('text-align','right');
 await page.locator('#open-rich-editor').click();await surface.fill('保留本地草稿');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target:'text',patch:{text:'远端内容'}}]));await page.locator('#rich-save').click();await expect(page.locator('#rich-editor-status')).toContainText('文字对象已变化');await expect(surface).toHaveText('保留本地草稿');await page.locator('#rich-discard').click();
 await page.locator('#open-rich-editor').click();await expect(surface).toHaveText('远端内容');await surface.press('Control+a');await surface.evaluate(node=>{const data=new DataTransfer();data.setData('text/plain','最终内容\n第二行 <文字>');node.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});await expect(surface.locator('p')).toHaveCount(0);await surface.press('Control+s');await expect(page.locator('#rich-editor-dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).toContain('最终内容');await expect(page.frameLocator('#canvas').locator('[data-notale-id="text"]')).toHaveText('最终内容第二行 <文字>');await expect(page.frameLocator('#canvas').locator('[data-notale-id="text"] br')).toHaveCount(1);
});
