import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.SETTINGS_TEST_URL??'http://127.0.0.1:4318'});
test('settings follow selection, save to the intended scope and keep navigation quiet',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const original=await page.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4').then(r=>r.json());const doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Settings navigation acceptance';doc.slides=doc.slides.slice(6,8);doc.layouts=[];for(const s of doc.slides){s.animations=[];s.layoutId=null;s.layoutSourceId=undefined;}
 expect((await page.request.post('/api/documents',{data:doc})).status()).toBe(201);
 await page.goto('/?document='+doc.id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);const ready=()=>page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await ready();
 const snapshot=()=>page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot());const version=async()=>(await snapshot()).version;
 await expect(page.locator('[data-tool="document"]')).toHaveCount(0);await page.locator('[data-tool="style"]').click();await expect(page.locator('#global-style')).toBeVisible();
 const target=await page.frameLocator('#canvas').locator('h1').getAttribute('data-notale-id');await page.frameLocator('#canvas').locator('body').evaluate(()=>{(window as any).__settingsSentinel=42;});
 await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),target);await expect(page.locator('#object-style')).toBeVisible();await expect(page.locator('#global-style')).toBeHidden();
 await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany([]));await expect(page.locator('#global-style')).toBeVisible();
 await page.locator('[data-tool="animation"]').click();await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),target);await expect(page.locator('[data-panel="animation"]')).toBeVisible();expect(await version()).toBe(1);expect(await page.frameLocator('#canvas').locator('body').evaluate(()=>(window as any).__settingsSentinel)).toBe(42);
 await page.locator('[data-tool="pages"]').click();await page.locator(`[data-slide="${doc.slides[1].id}"]`).click({button:'right'});await page.locator('#page-settings-name').fill('第二页单独设置');await page.locator('#page-settings-dialog summary').filter({hasText:'切换与计时'}).click();await page.locator('#page-settings-transition').selectOption('zoom');await page.locator('#page-settings-auto').check();await page.locator('#page-settings-seconds').fill('3.5');await page.locator('#save-page-settings').click();await expect(page.locator('#page-settings-dialog')).toBeHidden();await ready();expect((await snapshot()).document.slides[0].advanceAfter).toBe(doc.slides[0].advanceAfter);expect((await snapshot()).document.slides[1].advanceAfter).toBe(3500);
 await page.locator('#file-menu-trigger').click();await page.locator('[data-file="rename"]').click();await page.locator('#deck-title').fill('文件名称独立修改');await page.locator('#deck-title').press('Enter');await expect(page.locator('#file-title')).toHaveText('文件名称独立修改');await ready();
 await page.locator('.canvas-settings-menu summary').click();const before=await version();await page.locator('#rulers-visible').check();expect(await version()).toBe(before);await page.locator('#open-guide-settings').click();await page.locator('#guide-position').fill('125');await page.locator('#add-guide').click();await expect.poll(async()=>(await snapshot()).document.slides[0].guides.length).toBeGreaterThan(doc.slides[0].guides.length);await page.locator('#view-settings-dialog [data-close]').click();await ready();
 await page.locator('[data-tool="style"]').click();await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany([]));await page.locator('#deck-width').fill('1500');await page.locator('#save-deck-size').click();await expect.poll(async()=>(await snapshot()).document.width).toBe(1500);await ready();expect((await snapshot()).document.title).toBe('文件名称独立修改');
 await page.locator('#open-theme-settings').click();await page.locator('#theme-json').fill('{"--text":"#123456"}');await page.locator('#theme-settings-dialog button[type="submit"]').click();await expect(page.locator('#theme-settings-dialog')).toBeHidden();await ready();
 await page.locator('#visual-layout-name').fill('共用页脚');await page.locator('#create-visual-layout').click();await expect(page.locator('#master-edit-banner')).toBeVisible();await ready();await page.locator('#publish-master-return').click();await expect(page.locator('#master-edit-banner')).toBeHidden();await ready();
 const master=(await snapshot()).document.layouts[0];await page.locator('#shared-layout').selectOption(master.id);await page.locator('#apply-layout-all').click();await expect.poll(async()=>(await snapshot()).document.slides.filter((s:any)=>!s.layoutSourceId&&s.layoutId===master.id).length).toBe(2);await ready();
 await page.locator('[data-tool="pages"]').click();await page.locator(`[data-slide="${doc.slides[1].id}"]`).click({button:'right'});await page.locator('#page-master-settings summary').click();await expect(page.locator('#layout-values')).toBeVisible();await page.locator('#layout-value-fields textarea').first().fill('仅第二页的页脚');await page.locator('#save-layout-values').click();await expect.poll(async()=>JSON.stringify((await snapshot()).document.slides[1].layoutValues)).toContain('仅第二页的页脚');expect(JSON.stringify((await snapshot()).document.slides[0].layoutValues??{})).not.toContain('仅第二页的页脚');await page.locator('#close-page-settings').click();
 await page.locator('#file-menu-trigger').click();await page.locator('[data-file="history"]').click();await expect(page.locator('#history option')).not.toHaveCount(0);await page.locator('#history').selectOption('1');await page.locator('#history-confirm').check();await page.locator('#restore').click();await expect(page.locator('#history-dialog')).toBeHidden();await ready();expect((await snapshot()).document.title).toBe(doc.title);expect((await snapshot()).version).toBeGreaterThan(1);
 await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await ready();await page.locator('[data-tool="style"]').click();await expect(page.locator('#global-style')).toBeVisible();await page.screenshot({path:'.local/settings-navigation.png'});expect(errors).toEqual([]);
});
