import {test,expect} from '@playwright/test';
import {reveal} from './harness/format-panel';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React smart diagram controls duplicate cards and resize cycles without losing labels',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Smart diagrams',width:1600,height:900,slides:[{id:'first',name:'Blank',sourcePath:'first.html',html:'<html><body><main data-notale-id="stage" style="position:absolute;width:1600px;height:900px"></main></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 const insert=async(kind:string)=>{if(await page.locator('[data-tool="insert"]').getAttribute('aria-pressed')!=='true')await page.locator('[data-tool="insert"]').click();const section=page.locator('[data-insert-category="diagrams"]');if(await section.getAttribute('open')===null)await section.locator('summary').click();await page.locator(`[data-insert="smart:${kind}"]`).click();await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());};
 await insert('process');const frame=page.frameLocator('#canvas'),process=frame.locator('[data-notale-smart="process"]');const card=await process.locator('> *').first().getAttribute('data-notale-id');await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),card);await reveal(page,'#layout-item-tools');await expect(page.locator('#layout-item-tools')).toBeVisible();await page.locator('#layout-item-duplicate').click();await expect(process.locator('> *')).toHaveCount(4);await page.locator('#layout-item-delete').click();await expect(process.locator('> *')).toHaveCount(3);
 await insert('cycle');const cycle=frame.locator('[data-notale-smart="cycle"]'),root=await cycle.getAttribute('data-notale-id'),label=await cycle.locator('p').first().getAttribute('data-notale-id');await page.evaluate(async target=>{await(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target,patch:{text:'保留这个标签'}}]);},label);await page.evaluate(id=>(window as any).NotaleWorkbench.select(id),root);
 await reveal(page,'#cycle-count');await page.locator('#cycle-count').fill('5');await page.locator('#cycle-count').press('Tab');await expect(cycle.locator('p')).toHaveCount(5);await expect(cycle.locator('p').first()).toHaveText('保留这个标签');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(cycle.locator('p')).toHaveCount(5);
});
