import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {chartSvg} from '@notale/editor/browser';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React static chart edits tables, imports data and retains conflicting input',async({page})=>{
 let nodeId=0;
 const id=randomUUID(),svg=chartSvg({kind:'bar',title:'数据',labels:['A','B'],values:[10,20]} as any).replace(/<([a-zA-Z][\w:-]*)(?=[\s>])/g,(_tag,name)=>`<${name} data-notale-id="${nodeId++===0?'chart':'chart-'+nodeId}"`);
 const created=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'图表验证',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:`<html><body>${svg}</body></html>`}]}});expect(created.ok(),await created.text()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('chart'));
 await page.locator('#open-chart-editor').click();await expect(page.locator('#visual-chart-title')).toBeFocused();
 await page.locator('[data-chart-value="0:0"]').fill('');await expect(page.locator('#save-chart-editor')).toBeDisabled();await page.locator('[data-chart-value="0:0"]').press('Control+Enter');await expect(page.locator('#chart-editor-dialog')).toBeVisible();
 await page.locator('[data-chart-value="0:0"]').fill('25');
 await page.locator('#chart-add-row').click();await page.locator('#chart-add-series').click();
 await expect(page.locator('[data-chart-label]')).toHaveCount(3);await expect(page.locator('[data-series-name]')).toHaveCount(2);
 await page.locator('#chart-paste-panel summary').click();
 await page.locator('#chart-paste-data').fill('分类\t训练\t验证\nC\t30\t40\nD\t50\t60');await page.locator('#chart-paste-apply').click();
 await expect(page.locator('#chart-paste-status')).toContainText('2 个分类、2 个系列');
 await page.locator('#visual-chart-kind').selectOption('line');await page.locator('#visual-chart-title').press('Control+Enter');
 await expect(page.locator('#chart-editor-dialog')).toHaveCount(0);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 await page.locator('#open-chart-editor').click();await expect(page.locator('[data-series-name="0"]')).toHaveValue('训练');
 await page.locator('#visual-chart-title').fill('local draft');
 await page.evaluate(()=>{const api=(window as any).NotaleWorkbench;const item=api.getObjects().find((item:any)=>item.id==='chart');const data=JSON.parse(item.attributes['data-notale-chart']);return api.commands([{type:'chart.update',slideId:'first',target:'chart',data:{...data,title:'remote'}}]);});
 await page.locator('#save-chart-editor').click();await expect(page.locator('#chart-editor-status')).toContainText('数据已变化');await expect(page.locator('#visual-chart-title')).toHaveValue('local draft');
 await page.locator('#close-chart-editor').click();await page.locator('#open-chart-editor').click();await expect(page.locator('#visual-chart-title')).toHaveValue('remote');
 await page.locator('[data-remove-series="1"]').click();await page.locator('#visual-chart-kind').selectOption('doughnut');await page.locator('#visual-chart-title').press('Control+s');
 await expect(page.locator('#chart-editor-dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const raw=await page.frameLocator('#canvas').locator('[data-notale-id="chart"]').getAttribute('data-notale-chart');const saved=JSON.parse(raw!);expect(saved.kind).toBe('doughnut');expect(saved.series[0].values).toEqual([30,50]);
});
