import {test,expect,type Page} from '@playwright/test';import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.SYNC_TEST_URL??'http://127.0.0.1:4316'});
const ready=(p:Page)=>p.evaluate(()=>(window as any).NotaleWorkbench.whenReady());const state=(p:Page)=>p.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot());
async function setup(p:Page){const r=await p.request.get('/api/documents/f5d596d1-0584-4de4-ada6-ecf918147cd4');const original=await r.json(),doc=structuredClone(original.document);doc.id=randomUUID();doc.title='Sync acceptance';doc.slides=[doc.slides[6]];expect((await p.request.post('/api/documents',{data:doc})).status()).toBe(201);await p.goto('/?document='+doc.id);await ready(p);return doc;}
async function drag(p:Page,dx:number){const r=await p.frameLocator('#canvas').locator('h1').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+120,y:r.y+r.height/2,width:innerWidth};}),f=await p.locator('#canvas').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width};}),z=f.width/r.width;await p.mouse.move(f.x+r.x*z,f.y+r.y*z);await p.mouse.down();await p.mouse.move(f.x+r.x*z+dx,f.y+r.y*z+15,{steps:4});await p.mouse.up();}
async function command(p:Page,style:Record<string,string>){const target=await p.frameLocator('#canvas').locator('h1').getAttribute('data-notale-id'),doc=await state(p);return p.evaluate(({target,slideId,style})=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId,target,patch:{style}}]),{target,slideId:doc.document.slides[0].id,style});}
test('unified queue: mixed edits while slow save, no self conflict and stable reopen',async({page})=>{await setup(page);let release!:()=>void;const gate=new Promise<void>(r=>release=r);let count=0;await page.route('**/sync',async r=>{if(++count===1)await gate;await r.continue();});await drag(page,30);await expect.poll(()=>count).toBe(1);const normal=command(page,{color:'#123456'});await drag(page,35);release();await normal;await expect.poll(async()=>(await state(page)).version).toBe(4);await expect(page.locator('#save-status')).toContainText('已保存');await ready(page);const transform=await page.frameLocator('#canvas').locator('h1').evaluate(e=>getComputedStyle(e).transform);await page.reload();await ready(page);expect(await page.frameLocator('#canvas').locator('h1').evaluate(e=>getComputedStyle(e).transform)).toBe(transform);expect(await page.frameLocator('#canvas').locator('h1').evaluate(e=>getComputedStyle(e).color)).toBe('rgb(18, 52, 86)');});
test('closed tab: full queued draft automatically resumes and exact retry is idempotent',async({page,context})=>{const doc=await setup(page);await context.route('**/sync',r=>r.fulfill({status:503,body:'offline'}));await drag(page,30);await expect(page.locator('#save-status')).toContainText('本机');await drag(page,35);await expect.poll(async()=>page.evaluate(async()=>{const databases=await indexedDB.databases();return databases.some(d=>d.name?.startsWith('notale-sync-v1:'));})).toBe(true);await page.close({runBeforeUnload:false});await context.unroute('**/sync');const next=await context.newPage();await next.goto('/?document='+doc.id);await ready(next);await expect.poll(async()=>(await state(next)).version).toBe(3);let lost=true;const requests:string[]=[];await next.route('**/sync',async route=>{requests.push(route.request().postData()!);if(lost){lost=false;await route.fetch();await route.abort();}else await route.continue();});await drag(next,25);await expect(next.locator('#save-status')).toContainText('已保存',{timeout:10000});await expect.poll(()=>requests.length).toBeGreaterThanOrEqual(2);expect(requests[0]).toBe(requests[1]);expect((await next.request.get('/api/documents/'+doc.id).then(r=>r.json())).version).toBe(4);});
test('two windows: merge different properties and undo only own transaction',async({page,context})=>{const doc=await setup(page),other=await context.newPage();await other.goto('/?document='+doc.id);await ready(other);await command(page,{color:'#123456'});await command(other,{'font-size':'46px'});await expect.poll(async()=>(await state(page)).version).toBe(3);await page.locator('#undo').click();await expect.poll(async()=>(await state(page)).version).toBe(4);const current=await page.request.get('/api/documents/'+doc.id).then(r=>r.json());expect(current.document.slides[0].html).toContain('46px');expect(current.document.slides[0].html).not.toContain('#123456');await other.close();});

test('deleted target retains an exportable draft and opens a recovery copy',async({page,context})=>{const doc=await setup(page),target=await page.frameLocator('#canvas').locator('h1').getAttribute('data-notale-id');await page.request.post('/api/documents/'+doc.id+'/sync',{data:{baseVersion:1,mutationId:randomUUID(),commands:[{type:'element.delete',slideId:doc.slides[0].id,target}]}});await drag(page,30);await expect(page.locator('#recovery-panel')).toBeVisible();await page.locator('#recovery-panel > summary').click();const opened=context.waitForEvent('page');await page.getByRole('button',{name:'打开恢复副本'}).click();const copy=await opened;await copy.waitForLoadState();await ready(copy);expect((await state(copy)).document.id).not.toBe(doc.id);await expect(copy.frameLocator('#canvas').locator('h1')).toBeVisible();expect((await page.request.get('/api/documents/'+doc.id).then(r=>r.json())).version).toBe(2);});
test('local persistence failure never reports the edit as saved',async({page})=>{await setup(page);let requests=0;page.on('request',r=>{if(r.url().endsWith('/sync'))requests++;});await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){if(this.name==='operations')throw new DOMException('full','QuotaExceededError');return original.apply(this,args as any);};});await drag(page,30);await expect(page.locator('#save-status')).toContainText('本机保存失败');await expect(page.locator('#export-draft')).toBeVisible();expect(requests).toBe(0);});
