import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React table edits ranges structure and preserves conflicting text drafts',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'表格编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:'<html><body><table data-notale-id="table"><tbody data-notale-id="body"><tr data-notale-id="row1"><td data-notale-id="a">A</td><td data-notale-id="b">B</td></tr><tr data-notale-id="row2"><td data-notale-id="c">C</td><td data-notale-id="d">D</td></tr></tbody></table></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('a'));await expect(page.locator('#visual-table-panel')).toBeVisible();await expect(page.locator('#object-text')).not.toBeVisible();await expect(page.locator('#save-table-cell')).toBeDisabled();const initialVersion=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);await page.locator('#table-cell-text').press('Control+Enter');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(initialVersion);await page.locator('#table-cell-text').fill('保存文字');await page.locator('#table-cell-text').press('Control+Enter');await expect(page.locator('[data-table-cell="a"]')).toHaveText('保存文字');
 await page.locator('#table-cell-text').fill('本地草稿');await page.evaluate(()=>(window as any).NotaleWorkbench.commands([{type:'element.patch',slideId:'first',target:'a',patch:{text:'远端文字'}}]));await page.locator('#save-table-cell').click();await expect(page.locator('#table-cell-status')).toContainText('表格已变化');await expect(page.locator('#table-cell-text')).toHaveValue('本地草稿');await page.locator('#table-cell-text').press('Escape');await expect(page.locator('#table-cell-text')).toHaveValue('远端文字');await expect(page.locator('#table-cell-status')).not.toContainText('表格已变化');
 await page.locator('[data-table-cell="b"]').click({modifiers:['Shift']});await expect(page.locator('#table-cell-status')).toContainText('2 个单元格');await page.locator('#table-range-color').fill('#aabbcc');await page.locator('#apply-table-color').click();await expect(page.locator('#visual-table-panel')).toBeEnabled();const a=page.frameLocator('#canvas').locator('[data-notale-id="a"]');await expect(a).toHaveCSS('background-color','rgb(170, 187, 204)');await page.locator('#merge-table-range').click();await expect(a).toHaveAttribute('colspan','2');await page.locator('[data-table-action="unmerge"]').click();await expect(a).not.toHaveAttribute('colspan','2');await expect(page.locator('[data-table-cell]')).toHaveCount(4);
 await page.locator('[data-table-action="insert-row"]').click();await expect(page.frameLocator('#canvas').locator('tr')).toHaveCount(3);await page.locator('[data-table-action="delete-row"]').click();await expect(page.frameLocator('#canvas').locator('tr')).toHaveCount(2);await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).toContain('table');
});
