import {test,expect} from '@playwright/test';import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://localhost:4399'});
test('unchanged text and cancelled composition do not save; composing Escape stays in editor',async({page})=>{
 const id=randomUUID();const response=await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'文字会话边界',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><p data-notale-id="text" style="position:absolute;left:100px;top:100px;font-size:36px"><span style="color:red" data-notale-id="run">Hello</span></p></body></html>'}]}});expect(response.ok(),await response.text()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());const baseline=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);
 const object=page.frameLocator('#canvas').locator('[data-notale-id="text"]');const enter=async()=>{const local=await object.evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,width:innerWidth,height:innerHeight};});const frame=(await page.locator('#canvas').boundingBox())!;await page.mouse.dblclick(frame.x+local.x*frame.width/local.width,frame.y+local.y*frame.height/local.height);};await enter();await expect(object).toHaveAttribute('contenteditable','true');await object.dispatchEvent('compositionstart',{data:''});await object.dispatchEvent('keydown',{key:'Escape',isComposing:true,bubbles:true,cancelable:true});await expect(object).toHaveAttribute('contenteditable','true');await object.dispatchEvent('compositionend',{data:''});await object.press('Escape');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(baseline);
 await enter();await object.press('End');await object.dispatchEvent('compositionstart',{data:''});await page.keyboard.insertText('中文');await object.dispatchEvent('compositionend',{data:'中文'});await expect(object).toContainText('中文');await object.press('Escape');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBeGreaterThan(baseline);
 await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(object).toContainText('中文');
});
