import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React typography supports mixed selection font undo writing mode and reset',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'字体编辑',width:1600,height:900,slides:[{id:'first',name:'第一页',sourcePath:'first.html',html:'<html><body><p data-notale-id="a" style="font-size:20px;font-family:Arial, sans-serif;color:#ff0000">A</p><p data-notale-id="b" style="font-size:30px;font-family:Georgia;color:#0000ff">B</p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot()?.document.slides.length===1);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('a'));const a=page.frameLocator('#canvas').locator('[data-notale-id="a"]');await expect(page.locator('#font-size')).toHaveValue('20');await page.locator('#font-family').fill('Georgia');await page.locator('#font-family').press('Escape');await expect(page.locator('#font-family')).toHaveValue('Arial');await expect(a).toHaveCSS('font-family','Arial, sans-serif');
 const beforeFont=await page.request.get('/api/documents/'+id).then(r=>r.json());await page.locator('#font-family').focus();await page.locator('#font-family').blur();await page.locator('#font-family').fill('Arial');await page.locator('#font-family').press('Enter');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const afterFont=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(typeof afterFont.version).toBe('number');expect(afterFont.version).toBe(beforeFont.version);await expect(a).toHaveCSS('font-family','Arial, sans-serif');await page.locator('#font-size').fill('-10');await page.locator('#font-size').press('Escape');await expect(page.locator('#font-size')).toHaveValue('20');await expect(a).toHaveCSS('font-size','20px');await page.locator('#font-size').fill('42');await page.locator('#font-size').press('Enter');await page.locator('#font-size').blur();await expect(a).toHaveCSS('font-size','42px');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('font-size','20px');await expect(page.locator('#font-size')).toHaveValue('20');
 await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany(['a','b']));await expect(page.locator('#typography-status')).toContainText('混合样式');await expect(page.locator('#font-size')).toHaveValue('');await expect(page.locator('#color')).toHaveAttribute('data-mixed','true');
 await page.locator('#color').fill('#123456');await page.locator('#color').blur();await expect(a).toHaveCSS('color','rgb(18, 52, 86)');await expect(page.frameLocator('#canvas').locator('[data-notale-id="b"]')).toHaveCSS('color','rgb(18, 52, 86)');await expect(a).toHaveCSS('font-family','Arial, sans-serif');await expect(page.frameLocator('#canvas').locator('[data-notale-id="b"]')).toHaveCSS('font-family','Georgia');
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('color','rgb(255, 0, 0)');await expect(page.locator('#color')).toHaveAttribute('data-mixed','true');
 await page.locator('#font-size').fill('36');await page.locator('#font-size').press('Enter');await page.locator('#font-size').blur();await expect(a).toHaveCSS('font-size','36px');await expect(page.frameLocator('#canvas').locator('[data-notale-id="b"]')).toHaveCSS('font-size','36px');await page.locator('#bold').click();await expect(a).toHaveCSS('font-weight','700');await expect(page.locator('#bold')).toHaveAttribute('aria-pressed','true');
 await page.locator('#writing-mode').selectOption('vertical-rl');await expect(a).toHaveCSS('writing-mode','vertical-rl');await expect(a).toHaveCSS('text-orientation','upright');await page.locator('#font-family').fill('Georgia');await page.locator('#font-family').blur();await expect(a).toHaveCSS('font-family','Georgia');await page.locator('#reset-typography').click();await expect(a).toHaveCSS('writing-mode','horizontal-tb');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const saved=await page.request.get('/api/documents/'+id).then(r=>r.json());expect(saved.document.slides[0].html).not.toContain('font-size:36px');expect(saved.document.slides[0].html).not.toContain('vertical-rl');
});

test('direction changes preserve managed fixed boxes and keep autofit intrinsic',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'文字方向与尺寸',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',html:'<html><body><p data-notale-id="a" style="position:absolute;left:50px;top:50px;width:400px;height:100px;inline-size:400px;block-size:100px;margin:0;font:24px Arial">Short</p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.select('a'));
 const a=page.frameLocator('#canvas').locator('[data-notale-id="a"]'),mode=page.locator('#writing-mode');
 await mode.selectOption('vertical-rl');await expect(a).toHaveCSS('writing-mode','vertical-rl');await expect(a).toHaveCSS('width','400px');await expect(a).toHaveCSS('height','100px');
 await mode.selectOption('horizontal-tb');await expect(a).toHaveCSS('width','400px');await expect(a).toHaveCSS('height','100px');
 await page.locator('#appearance-fit').selectOption('both');await mode.selectOption('vertical-rl');await expect(page.locator('#appearance-fit')).toHaveValue('both');await expect.poll(()=>a.evaluate(node=>parseFloat(getComputedStyle(node).inlineSize))).toBeLessThan(200);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.locator('#undo').click();await expect(a).toHaveCSS('writing-mode','horizontal-tb');await expect(page.locator('#appearance-fit')).toHaveValue('both');
 await mode.selectOption('vertical-rl');await page.locator('#reset-typography').click();await expect(a).toHaveCSS('writing-mode','horizontal-tb');await expect(page.locator('#appearance-fit')).toHaveValue('both');await expect.poll(()=>a.evaluate(node=>parseFloat(getComputedStyle(node).width))).toBeLessThan(200);
 await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(a).toHaveCSS('writing-mode','horizontal-tb');await expect.poll(()=>a.evaluate(node=>parseFloat(getComputedStyle(node).width))).toBeLessThan(200);
});

test('mixed locked text selection edits only unlocked objects and all-locked controls stay disabled',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'锁定文字多选',width:1600,height:900,slides:[{id:'first',name:'页面',sourcePath:'first.html',locked:['b'],html:'<html><body><p data-notale-id="a" style="font-size:20px">A</p><p data-notale-id="b" style="font-size:20px">B</p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await page.evaluate(()=>(window as any).NotaleWorkbench.selectMany(['a','b']));const size=page.locator('#font-size'),a=page.frameLocator('#canvas').locator('[data-notale-id="a"]'),b=page.frameLocator('#canvas').locator('[data-notale-id="b"]');
 await expect(size).toBeEnabled();await size.fill('32');await size.press('Enter');await expect(page.locator('#typography-status')).toContainText('混合样式');await expect(size).toHaveValue('32');await size.blur();await expect(size).toHaveValue('');await expect(a).toHaveCSS('font-size','32px');await expect(b).toHaveCSS('font-size','20px');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());
 const opacity=page.locator('#appearance-opacity');await opacity.fill('40');await opacity.press('Enter');await expect(a).toHaveCSS('opacity','0.4');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());await expect(page.locator('#property-appearance')).toHaveAttribute('aria-busy','false');await opacity.blur();await expect(page.locator('#appearance-opacity-value')).toHaveText('—');await expect(b).toHaveCSS('opacity','1');
 await page.evaluate(()=>(window as any).NotaleWorkbench.select('b'));await expect(size).toBeDisabled();await expect(page.locator('#appearance-opacity')).toBeDisabled();
 await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(a).toHaveCSS('font-size','32px');await expect(b).toHaveCSS('font-size','20px');
});

test('formatted heading exposes typography and retains inline nodes after style save',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'带格式标题',width:1600,height:900,slides:[{id:'page',name:'页面',sourcePath:'page.html',html:'<html><body><h1 data-notale-id="heading" style="font-size:40px">第一行<br data-notale-id="break"><strong data-notale-id="bold">第二行</strong></h1></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id);await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(async()=>{await (window as any).NotaleWorkbench.whenReady();(window as any).NotaleWorkbench.select('heading');});await expect(page.locator('#font-size')).toBeVisible();await expect(page.locator('#open-rich-editor')).toBeVisible();await expect(page.locator('#selection-name')).toBeHidden();await page.locator('#font-size').fill('52');await page.locator('#font-size').press('Enter');await page.evaluate(()=>(window as any).NotaleWorkbench.whenSynchronized());const heading=page.frameLocator('#canvas').locator('[data-notale-id="heading"]');await expect(heading).toHaveCSS('font-size','52px');await expect(heading.locator('br')).toHaveCount(1);await expect(heading.locator('strong')).toHaveText('第二行');await page.reload();await page.waitForFunction(()=>(window as any).NotaleWorkbench);await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());await expect(heading).toHaveCSS('font-size','52px');await expect(heading.locator('br')).toHaveCount(1);
});
