import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({baseURL:process.env.ARCHITECTURE_URL??'http://127.0.0.1:4399'});
test('React zoom controls reflect viewport gestures without changing the document or reloading its canvas',async({page})=>{
 const id=randomUUID();expect((await page.request.post('/api/documents',{data:{schemaVersion:1,id,title:'Viewport',width:1600,height:900,slides:[{id:'first',name:'Viewport',sourcePath:'first.html',html:'<html><body><p data-notale-id="text">Viewport</p></body></html>'}]}})).ok()).toBe(true);
 await page.goto('/?document='+id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>(window as any).NotaleWorkbench?.getSnapshot());await page.evaluate(()=>(window as any).NotaleWorkbench.whenReady());const version=await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version);await page.frameLocator('#canvas').locator('body').evaluate(()=>{(window as any).__viewportSentinel=42;});
 await page.locator('#canvas-zoom').selectOption('1');await page.locator('#zoom-in').click();await expect(page.locator('#canvas-zoom')).toHaveValue('1.1');await expect(page.locator('#canvas-zoom [data-current]')).toHaveCount(1);await expect.poll(()=>page.locator('#canvas').evaluate(frame=>new DOMMatrix(getComputedStyle(frame).transform).a)).toBe(1.1);
 await page.locator('#zoom-out').click();await expect(page.locator('#canvas-zoom')).toHaveValue('1');await page.locator('#canvas-zoom').selectOption('2');
 const viewport=page.locator('#canvas-viewport');await viewport.evaluate(node=>{node.scrollTo(200,100);const r=node.getBoundingClientRect();node.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,ctrlKey:true,deltaY:100,clientX:r.x+200,clientY:r.y+150}));});await expect.poll(async()=>Number(await page.locator('#canvas-zoom').inputValue())).toBeLessThan(2);await expect(page.locator('#canvas-zoom [data-current]')).toHaveCount(1);
 await viewport.focus();await page.keyboard.down('Space');await expect(page.locator('#pan-canvas')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#canvas-pan-surface')).not.toHaveAttribute('hidden');await page.keyboard.up('Space');await expect(page.locator('#pan-canvas')).toHaveAttribute('aria-pressed','false');
 await page.locator('#canvas-zoom').selectOption('fit');await expect(page.locator('#canvas-zoom')).toHaveValue('fit');await expect(page.locator('#canvas-zoom [data-current]')).toHaveCount(0);expect(await page.frameLocator('#canvas').locator('body').evaluate(()=>(window as any).__viewportSentinel)).toBe(42);expect(await page.evaluate(()=>(window as any).NotaleWorkbench.getSnapshot().version)).toBe(version);
});
