"""Lossless source crops. Run: python3 references/styles/crop.py /path/to/originals.

Coordinates were inspected per poster, not inferred from five equal strips.
Only derived files below this directory are written; original files are untouched.
Use --contacts-only to rebuild compact, pixel-deduplicated sheets from existing crops.
"""
import argparse
from hashlib import sha256
from pathlib import Path
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent
SOURCES = ['0 (4).png', '0 (5).png', '0 (6).png', '0 (7).png',
           '0.png', '0 (1).png', '0 (2).png', '0 (3).png']
# x bounds and five y intervals, excluding the poster's shared browser chrome.
CROPS = [
    (295, 1022, [(126, 362), (414, 651), (705, 939), (990, 1230), (1275, 1469)]),
    (296, 1021, [(126, 390), (439, 704), (752, 982), (1027, 1258), (1300, 1489)]),
    (295, 1021, [(127, 378), (424, 659), (703, 936), (981, 1221), (1264, 1465)]),
    (296, 1022, [(128, 363), (412, 654), (705, 946), (997, 1221), (1268, 1473)]),
    (293, 1021, [(125, 381), (431, 675), (723, 969), (1017, 1247), (1294, 1478)]),
    (293, 1022, [(125, 378), (424, 681), (724, 971), (1015, 1248), (1290, 1478)]),
    (295, 1022, [(127, 370), (417, 662), (710, 957), (1003, 1245), (1286, 1479)]),
    (296, 1021, [(129, 376), (425, 666), (717, 959), (1008, 1225), (1273, 1477)]),
]


def unique_crops(rows):
    """Deduplicate identical decoded pixels, retaining every style ID as an alias.

    Similar palettes or compositions are not duplicates. Keep source crops intact.
    """
    groups = {}
    for row in rows:
        with Image.open(ROOT / 'shots' / f'{row[0]}.png') as source:
            crop = source.convert('RGBA')
        digest = sha256(str(crop.size).encode() + crop.tobytes()).hexdigest()
        if digest not in groups:
            groups[digest] = {'ids': [], 'image': crop}
        groups[digest]['ids'].append(row[0])
    return list(groups.values())


def contact_sheets(rows):
    """Four references per sheet, two columns; no stretching, recropping or AI edits."""
    groups = unique_crops(rows)
    destination = ROOT / 'contact-sheets'
    destination.mkdir(exist_ok=True)
    font = ImageFont.truetype('DejaVuSans.ttf', 18)
    width, height, margin, gap, line_height = 720, 270, 16, 16, 26
    index = ['# Compact style references', '',
             f'{len(rows)} style IDs; {len(groups)} unique pixel images. '
             'Only pixel-identical crops are merged; all IDs and source crops remain.', '',
             'Generated by `python3 references/styles/crop.py --contacts-only`. '
             'Each sheet has at most four images. This index lists the current sheets; '
             'older unlisted files, if any, are not part of this set.', '']
    for offset in range(0, len(groups), 4):
        batch = groups[offset:offset + 4]
        labels_height = max(len(item['ids']) for item in batch) * line_height + 8
        tile_height = labels_height + height
        row_count = (len(batch) + 1) // 2
        sheet = Image.new('RGB', (2 * width + gap + 2 * margin,
                                 row_count * tile_height + (row_count - 1) * gap + 2 * margin),
                          'white')
        draw = ImageDraw.Draw(sheet)
        for position, item in enumerate(batch):
            x = margin + (position % 2) * (width + gap)
            y = margin + (position // 2) * (tile_height + gap)
            for line, key in enumerate(item['ids']):
                draw.text((x, y + line * line_height), key, fill='black', font=font)
            thumb = item['image'].copy()
            thumb.thumbnail((width, height), Image.Resampling.LANCZOS)
            sheet.paste(thumb, (x + (width - thumb.width) // 2, y + labels_height), thumb)
        name = f'{offset // 4 + 1:02d}.png'
        sheet.save(destination / name)
        ids = [key for item in batch for key in item['ids']]
        index.extend([f'## {name[:-4]} · {", ".join(ids)}', '',
                      f'[Open sheet]({name}) · ' + ' · '.join(
                          f'[{key}](../shots/{key}.png)' for key in ids), '',
                      f'![Style references {name[:-4]}]({name})', ''])
    (destination / 'README.md').write_text('\n'.join(index), encoding='utf-8')
    merged = [item['ids'] for item in groups if len(item['ids']) > 1]
    print(f'{len(rows)} style IDs → {len(groups)} unique images → '
          f'{(len(groups) + 3) // 4} compact sheets; duplicate groups: {merged}')


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('source', type=Path, nargs='?')
    ap.add_argument('--contacts-only', action='store_true',
                    help='Use existing shots; do not rewrite crops or legacy overviews')
    args = ap.parse_args()
    rows = [[x.strip() for x in line.strip('|').split('|')]
            for line in (ROOT / 'INDEX.md').read_text().splitlines() if re.match(r'\| \d{2}-', line)]
    assert len(rows) == 40 and len({r[0] for r in rows}) == 40
    if args.contacts_only:
        contact_sheets(rows)
        return
    if args.source is None:
        ap.error('source is required unless --contacts-only is used')
    (ROOT / 'shots').mkdir(exist_ok=True)
    (ROOT / 'overviews').mkdir(exist_ok=True)
    font = ImageFont.truetype('DejaVuSans.ttf', 18)
    for group, (source, (left, right, bounds)) in enumerate(zip(SOURCES, CROPS), 1):
        with Image.open(args.source / source) as im:
            assert im.size == (1055, 1491), (source, im.size)
            thumbnails = []
            for line, (top, bottom) in enumerate(bounds, 1):
                row = rows[(group - 1) * 5 + line - 1]
                assert row[4] == f'{group:02d}/{line}'
                crop = im.crop((left, top, right, bottom))
                crop.save(ROOT / 'shots' / (row[0] + '.png'))
                thumb = crop.convert('RGB')
                thumb.thumbnail((700, 280), Image.Resampling.LANCZOS)
                thumbnails.append((row[0], thumb))
            sheet = Image.new('RGB', (720, sum(t.height + 42 for _, t in thumbnails) + 10), 'white')
            draw, y = ImageDraw.Draw(sheet), 10
            for label, thumb in thumbnails:
                draw.text((10, y), label, font=font, fill='black')
                sheet.paste(thumb, (10, y + 28))
                y += thumb.height + 42
            sheet.save(ROOT / 'overviews' / f'{group:02d}.png')
    print('40 lossless crops + 8 labelled overviews created; originals unchanged.')
    contact_sheets(rows)


if __name__ == '__main__':
    main()
