import {computePosition,flip,shift,offset} from '@floating-ui/dom';
import type {Command,DeckDocument} from '@notale/editor/browser';
type Revision={version:number;created_at:string};
export function createDocumentUI(context:{document:()=>DeckDocument;version:()=>number;commands:(commands:Command[])=>Promise<unknown>;load:(id:string)=>Promise<unknown>;history:()=>Promise<Revision[]>;restore:(version:number)=>Promise<unknown>;flush:()=>Promise<unknown>;error:(e:unknown)=>void}){
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const panel=document.querySelector<HTMLElement>('[data-panel="format"]')!,object=document.createElement('div');object.id='object-style';while(panel.firstChild)object.append(panel.firstChild);panel.append(object,el('global-style'));
 function dialog(id:string,title:string,body:string){const node=document.createElement('dialog');node.id=id;node.className='settings-dialog';node.setAttribute('aria-label',title);node.innerHTML=`<header><h2>${title}</h2><button type="button" data-close aria-label="关闭">×</button></header>${body}<p class="settings-status" role="status"></p>`;document.body.append(node);node.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>{if(node.dataset.busy!=='true')node.close();};node.addEventListener('cancel',e=>{if(node.dataset.busy==='true')e.preventDefault();});node.addEventListener('keydown',e=>e.stopPropagation());return node;}
 async function run(node:HTMLElement,action:()=>Promise<unknown>){if(node.dataset.busy==='true')return;node.dataset.busy='true';const status=node.querySelector<HTMLElement>('[role="status"]');if(status)status.textContent='';const controls=[...node.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement|HTMLTextAreaElement>('input,button,select,textarea')],disabled=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);try{await action();}catch(e){if(status)status.textContent=e instanceof Error?e.message:String(e);else context.error(e);}finally{node.dataset.busy='false';controls.forEach((c,i)=>c.disabled=disabled[i]);}}
 const theme=dialog('theme-settings-dialog','高级主题设置','<form><label>主题 CSS 变量<textarea id="theme-json" rows="12" spellcheck="false"></textarea></label><p class="hint">只影响使用这些变量的内容，保留页面和母版的独立设置。</p><footer><button type="submit" class="primary">应用主题</button></footer></form>');
 let themeSource:DeckDocument|undefined;
 el('open-theme-settings').onclick=()=>{themeSource=structuredClone(context.document());el<HTMLTextAreaElement>('theme-json').value=JSON.stringify(themeSource.theme,null,2);theme.querySelector<HTMLElement>('[role="status"]')!.textContent='';theme.showModal();};
 theme.querySelector('form')!.onsubmit=e=>{e.preventDefault();void run(theme,async()=>{const doc=context.document();if(!themeSource||themeSource.id!==doc.id||JSON.stringify(themeSource.theme)!==JSON.stringify(doc.theme))throw Error('主题已变化，输入已保留，请核对后重新打开设置');const value=JSON.parse(el<HTMLTextAreaElement>('theme-json').value);if(!value||Array.isArray(value)||typeof value!=='object'||Object.values(value).some(v=>typeof v!=='string'))throw Error('请输入属性名与字符串值组成的 JSON 对象');if(JSON.stringify(value)!==JSON.stringify(doc.theme))await context.commands([{type:'deck.update',theme:value}]);theme.close();});};
 let sizeSource:Pick<DeckDocument,'id'|'width'|'height'>|undefined,sizeDirty=false;
 for(const id of ['deck-width','deck-height'])el(id).addEventListener('input',()=>sizeDirty=true);
 el('save-deck-size').onclick=()=>void run(el('save-deck-size').parentElement!,async()=>{const doc=context.document(),width=Number(el<HTMLInputElement>('deck-width').value),height=Number(el<HTMLInputElement>('deck-height').value);if(!sizeSource||doc.id!==sizeSource.id||doc.width!==sizeSource.width||doc.height!==sizeSource.height)throw Error('页面尺寸已变化，输入已保留；重新打开讲义后可载入最新尺寸');if(![width,height].every(v=>Number.isInteger(v)&&v>=100&&v<=10000))throw Error('宽高须为 100–10000 之间的整数');if(width!==doc.width||height!==doc.height)await context.commands([{type:'deck.update',width,height}]);sizeDirty=false;render();});
 const switcher=dialog('switch-document-dialog','切换讲义','<label>讲义</label>');const documents=el<HTMLSelectElement>('documents');
 const fileButton=document.createElement('button');fileButton.id='file-menu-trigger';fileButton.className='file-title-button';fileButton.setAttribute('aria-haspopup','menu');fileButton.setAttribute('aria-expanded','false');fileButton.title='文件菜单';fileButton.innerHTML='<span id="file-title"></span><span aria-hidden="true">⌄</span>';documents.before(fileButton);switcher.querySelector('label')!.append(documents);
 documents.onchange=()=>void run(switcher,async()=>{await context.flush();try{await context.load(documents.value);switcher.close();}finally{documents.value=context.document().id;}});
 const rename=document.createElement('form');rename.id='rename-document-form';rename.hidden=true;rename.innerHTML='<input id="deck-title" required maxlength="300" aria-label="文件名"><span role="status"></span>';fileButton.after(rename);const closeRename=()=>{rename.hidden=true;fileButton.hidden=false;};rename.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();closeRename();fileButton.focus();}});let titleSource:{id:string;title:string}|undefined;
 function openRename(){titleSource={id:context.document().id,title:context.document().title};el<HTMLInputElement>('deck-title').value=titleSource.title;rename.querySelector<HTMLElement>('[role="status"]')!.textContent='';rename.hidden=false;fileButton.hidden=true;el<HTMLInputElement>('deck-title').focus();el<HTMLInputElement>('deck-title').select();}
 rename.onsubmit=e=>{e.preventDefault();void run(rename,async()=>{const doc=context.document(),title=el<HTMLInputElement>('deck-title').value.trim();if(!title)throw Error('文件名不能为空');if(doc.id!==titleSource?.id||doc.title!==titleSource.title)throw Error('文件名已变化，输入已保留，请核对后重新打开');if(title!==doc.title)await context.commands([{type:'deck.update',title}]);closeRename();});};
 const history=dialog('history-dialog','历史版本','<p class="hint">恢复会创建新版本，已有历史仍会保留。</p><div id="history-controls"></div><p id="history-description"></p><label id="history-confirm-row" hidden><input type="checkbox" id="history-confirm">确认将当前讲义恢复到所选版本</label>');
 const historySelect=el<HTMLSelectElement>('history'),restoreButton=el<HTMLButtonElement>('restore');const historyLabel=historySelect.closest('label')!;historyLabel.removeChild(historySelect);historyLabel.remove();el('history-controls').append(historySelect,restoreButton);restoreButton.textContent='恢复此版本';
 let historyDocument='',historyVersion=0;
 function historyChoice(){const version=Number(historySelect.value);if(!Number.isInteger(version)||version<1){el('history-confirm-row').hidden=true;restoreButton.disabled=true;el('history-description').textContent='历史版本尚未加载';return;}el<HTMLInputElement>('history-confirm').checked=false;el('history-confirm-row').hidden=version===historyVersion;restoreButton.disabled=true;el('history-description').textContent=version===historyVersion?'当前版本':`将恢复到 v${version}。`;}
 historySelect.onchange=historyChoice;el('history-confirm').onchange=()=>restoreButton.disabled=!el<HTMLInputElement>('history-confirm').checked;
 async function openHistory(){historyDocument=context.document().id;historyVersion=context.version();history.showModal();await run(history,async()=>{const rows=await context.history();if(context.document().id!==historyDocument)throw Error('讲义已切换');historySelect.replaceChildren(...rows.map(r=>new Option(`v${r.version}${r.version===historyVersion?' · 当前':''} · ${new Date(r.created_at).toLocaleString()}`,String(r.version))));historySelect.value=String(historyVersion);});historyChoice();}
 restoreButton.onclick=()=>void run(history,async()=>{if(context.document().id!==historyDocument)throw Error('讲义已切换');await context.flush();await context.restore(Number(historySelect.value));history.close();});
 const recovery=dialog('recovery-dialog','恢复修改','<p class="hint">打开恢复副本或导出保留的草稿。</p>');recovery.append(el('recovery-panel'),el('import-recovery').closest('label')!);const empty=document.createElement('p');empty.textContent='没有待恢复的修改';empty.id='recovery-empty';recovery.append(empty);
 function openRecovery(){empty.hidden=!el('recovery-panel').hidden;(el('recovery-panel') as HTMLDetailsElement).open=true;recovery.showModal();}
 const menu=document.createElement('div');menu.id='file-menu';menu.className='editor-popup';menu.hidden=true;menu.setAttribute('role','menu');menu.innerHTML='<button data-file="rename" role="menuitem">重命名</button><button data-file="switch" role="menuitem">切换讲义…</button><hr><button data-file="history" role="menuitem">历史版本…</button><button data-file="recovery" role="menuitem">恢复修改…</button>';document.body.append(menu);
 function closeMenu(){menu.hidden=true;fileButton.setAttribute('aria-expanded','false');}
 fileButton.onclick=()=>{if(!menu.hidden){closeMenu();return;}menu.hidden=false;fileButton.setAttribute('aria-expanded','true');void computePosition(fileButton,menu,{strategy:'fixed',placement:'bottom-start',middleware:[offset(6),flip(),shift({padding:8})]}).then(p=>Object.assign(menu.style,{left:p.x+'px',top:p.y+'px'}));menu.querySelector<HTMLButtonElement>('button')!.focus();};
 fileButton.ondblclick=()=>{closeMenu();openRename();};
 menu.addEventListener('click',e=>{const action=(e.target as HTMLElement).closest<HTMLElement>('[data-file]')?.dataset.file;if(!action)return;closeMenu();if(action==='rename')openRename();if(action==='switch')switcher.showModal();if(action==='history')void openHistory().catch(context.error);if(action==='recovery')openRecovery();});
 menu.addEventListener('keydown',e=>{e.stopPropagation();const buttons=[...menu.querySelectorAll<HTMLButtonElement>('button')],index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(e.key==='Escape'){closeMenu();fileButton.focus();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(e.key==='Tab')closeMenu();});
 document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target as Node)&&!fileButton.contains(e.target as Node))closeMenu();},true);window.addEventListener('resize',closeMenu);window.addEventListener('message',e=>{if(e.source===el<HTMLIFrameElement>('canvas').contentWindow&&e.data?.type==='context-dismiss')closeMenu();});
 const guides=dialog('view-settings-dialog','网格与参考线','');const group=el('guide-settings');group.querySelector('summary')!.remove();const guideBody=document.createElement('div');while(group.firstChild)guideBody.append(group.firstChild);group.replaceWith(guideBody);guides.append(guideBody);
 const view=document.createElement('details');view.className='canvas-settings-menu';view.innerHTML='<summary title="视图设置" aria-label="视图设置"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="m6 9 6 6 6-6"/></svg></summary><div class="editor-popup"><div id="view-preferences"></div><button id="open-guide-settings">网格与参考线…</button></div>';el('canvas-zoom').parentElement!.append(view);
 for(const id of ['rulers-visible','guides-visible','snap-enabled'])el('view-preferences').append(el(id).closest('label')!);
 el('open-guide-settings').onclick=()=>{view.open=false;guides.showModal();};
 document.addEventListener('pointerdown',e=>{if(!view.contains(e.target as Node))view.open=false;},true);view.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){view.open=false;view.querySelector<HTMLElement>('summary')!.focus();}});
 function render(){const doc=context.document();el('file-title').textContent=doc.title;if(!sizeSource||sizeSource.id!==doc.id||!sizeDirty){sizeSource={id:doc.id,width:doc.width,height:doc.height};el<HTMLInputElement>('deck-width').value=String(doc.width);el<HTMLInputElement>('deck-height').value=String(doc.height);sizeDirty=false;}if(rename.hidden)el<HTMLInputElement>('deck-title').value=doc.title;}
 return {render};
}
