import {mediaSettingsSchema,type Command} from '@notale/editor/browser';
type Item={id:string;tag:string;locked:boolean;attributes:Record<string,string>;style:Record<string,string>};
const edges=['top','right','bottom','left'] as const;
type Edge=typeof edges[number];
export function createImageCrop(context:{selected:()=>Item|undefined;key:()=>string;slideId:()=>string;preview:()=>string;capture:(ids:string[])=>Promise<{computedStyles:Record<string,Record<string,string>>}>;commands:(commands:Command[])=>Promise<unknown>}) {
  const trigger=document.createElement('button');trigger.id='open-image-crop';trigger.textContent='可视化裁剪';document.getElementById('media-fit')!.closest('label')!.after(trigger);
  const dialog=document.createElement('dialog');dialog.id='image-crop-dialog';dialog.setAttribute('aria-labelledby','crop-title');
  dialog.innerHTML=`<header><h2 id="crop-title">调整图片取景</h2><button id="close-image-crop" aria-label="关闭图片裁剪">×</button></header><p>拖动边缘裁剪，拖动框内移动选区。方向键可微调边缘。</p><div id="crop-stage"><img id="crop-preview" alt="裁剪预览" draggable="false"><div id="crop-box">${edges.map(edge=>`<button data-crop-edge="${edge}" aria-label="裁剪${({top:'上',right:'右',bottom:'下',left:'左'})[edge]}边" role="slider" aria-valuemin="0" aria-valuemax="99"></button>`).join('')}</div></div><div class="field-grid"><label>水平取景<input id="crop-focus-x" type="range" min="0" max="100"></label><label>垂直取景<input id="crop-focus-y" type="range" min="0" max="100"></label><label>图片适应<select id="crop-fit"><option value="contain">完整适应</option><option value="cover">裁切填充</option><option value="fill">拉伸</option><option value="none">原始尺寸</option><option value="scale-down">仅缩小</option></select></label></div><p id="crop-status" role="status"></p><footer><button id="reset-image-crop">重置裁剪</button><button id="save-image-crop" class="primary">保存裁剪</button></footer>`;document.body.append(dialog);
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>dialog.querySelector<T>('#'+id)!;
  let crop={top:0,right:0,bottom:0,left:0},key='',target='',slideId='',busy=false,generation=0;
  function sizeStage(width:number,height:number){const ratio=width/height;el('crop-stage').style.aspectRatio=String(ratio);el('crop-stage').style.setProperty('--crop-ratio',String(ratio));}
  function paint(){const box=el('crop-box');box.style.inset=`${crop.top}% ${crop.right}% ${crop.bottom}% ${crop.left}%`;for(const edge of edges){const handle=dialog.querySelector(`[data-crop-edge="${edge}"]`)!;handle.setAttribute('aria-valuenow',String(Math.round(crop[edge])));handle.setAttribute('aria-orientation',edge==='top'||edge==='bottom'?'vertical':'horizontal');const opposite={top:'bottom',bottom:'top',left:'right',right:'left'} as const;handle.setAttribute('aria-valuemax',String(99-crop[opposite[edge]]));}const img=el<HTMLImageElement>('crop-preview');img.style.objectFit=el<HTMLSelectElement>('crop-fit').value;img.style.objectPosition=el<HTMLInputElement>('crop-focus-x').value+'% '+el<HTMLInputElement>('crop-focus-y').value+'%';}
  const open=()=>{
    const object=context.selected();if(!object||object.tag!=='img'||object.locked)return;
    const settings=mediaSettingsSchema.parse(object.attributes['data-notale-media']?JSON.parse(object.attributes['data-notale-media']):{fit:object.style['object-fit']??'contain'});
    crop={...settings.crop};key=context.key();target=object.id;slideId=context.slideId();
    el<HTMLInputElement>('crop-focus-x').value=String(settings.positionX);el<HTMLInputElement>('crop-focus-y').value=String(settings.positionY);el<HTMLSelectElement>('crop-fit').value=settings.fit;
    el<HTMLImageElement>('crop-preview').src=new URL(object.attributes.src,context.preview()).href;
    sizeStage(parseFloat(object.style.width)||500,parseFloat(object.style.height)||320);
    el('crop-status').textContent='';paint();dialog.showModal();const request=++generation;
    void context.capture([target]).then(result=>{if(!dialog.open||request!==generation||key!==context.key())return;const styles=result.computedStyles[target];const w=parseFloat(styles?.width),h=parseFloat(styles?.height);if(w>0&&h>0)sizeStage(w,h);}).catch(()=>{});
  };
  trigger.onclick=open;
  let drag:{x:number;y:number;edge?:Edge;crop:typeof crop;width:number;height:number}|undefined;
  el('crop-box').addEventListener('pointerdown',event=>{if(busy)return;const bounds=el('crop-stage').getBoundingClientRect();drag={x:event.clientX,y:event.clientY,edge:(event.target as HTMLElement).dataset.cropEdge as Edge|undefined,crop:{...crop},width:bounds.width,height:bounds.height};el('crop-box').setPointerCapture(event.pointerId);event.preventDefault();});
  el('crop-box').addEventListener('pointermove',event=>{if(!drag)return;const dx=(event.clientX-drag.x)/drag.width*100,dy=(event.clientY-drag.y)/drag.height*100;crop={...drag.crop};if(drag.edge){const opposite={top:'bottom',bottom:'top',left:'right',right:'left'} as const;const delta={top:dy,bottom:-dy,left:dx,right:-dx}[drag.edge];crop[drag.edge]=Math.max(0,Math.min(99-crop[opposite[drag.edge]],crop[drag.edge]+delta));}else{const x=Math.max(-crop.left,Math.min(crop.right,dx)),y=Math.max(-crop.top,Math.min(crop.bottom,dy));crop.left+=x;crop.right-=x;crop.top+=y;crop.bottom-=y;}paint();});
  for(const type of ['pointerup','pointercancel','lostpointercapture'])el('crop-box').addEventListener(type,()=>{drag=undefined;});
  for(const handle of dialog.querySelectorAll<HTMLElement>('[data-crop-edge]'))handle.addEventListener('keydown',event=>{if(busy)return;const edge=handle.dataset.cropEdge as Edge;const vertical=edge==='top'||edge==='bottom';const deltas:Record<string,number>=vertical?{ArrowUp:-1,ArrowDown:1}:{ArrowLeft:-1,ArrowRight:1};const delta=deltas[event.key];if(!delta)return;event.preventDefault();const opposite={top:'bottom',bottom:'top',left:'right',right:'left'} as const;const direction=edge==='right'||edge==='bottom'?-1:1;crop[edge]=Math.max(0,Math.min(99-crop[opposite[edge]],crop[edge]+delta*direction*(event.shiftKey?10:1)));paint();});
  for(const id of ['crop-focus-x','crop-focus-y','crop-fit'])el(id).addEventListener('input',paint);
  el('reset-image-crop').onclick=()=>{crop={top:0,right:0,bottom:0,left:0};el<HTMLInputElement>('crop-focus-x').value='50';el<HTMLInputElement>('crop-focus-y').value='50';paint();};
  el('save-image-crop').onclick=()=>void(async()=>{if(busy)return;if(context.key()!==key){el('crop-status').textContent='页面已变化，请关闭后重新打开裁剪。';return;}busy=true;el<HTMLButtonElement>('save-image-crop').disabled=true;try{await context.commands([{type:'media.update',slideId,target,patch:{settings:{crop,fit:el<HTMLSelectElement>('crop-fit').value as 'cover',positionX:Number(el<HTMLInputElement>('crop-focus-x').value),positionY:Number(el<HTMLInputElement>('crop-focus-y').value)}}}]);dialog.close();}catch(error){el('crop-status').textContent=error instanceof Error?error.message:String(error);}finally{busy=false;el<HTMLButtonElement>('save-image-crop').disabled=false;}})();
  el('close-image-crop').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('keydown',event=>event.stopPropagation());
  return{open,render(){const object=context.selected();trigger.hidden=object?.tag!=='img';trigger.disabled=!!object?.locked;}};
}
