import type {Slide,DeckDocument,Command,Asset} from '@notale/editor/browser';
export interface LayoutValueModel {key:string;value:string;signature:string;documentId:string;pageId:string;layoutId:string|null;author:boolean;texts:{id:string;label:string}[];images:{id:string;label:string;overridden:boolean}[];}
let model:LayoutValueModel|undefined;const listeners=new Set<()=>void>();
export const layoutValueState={getSnapshot:()=>model,getServerSnapshot:()=>undefined,subscribe:(listener:()=>void)=>{listeners.add(listener);return()=>{listeners.delete(listener);};}};
export const layoutValueActions={save:async(_source:LayoutValueModel,_raw:string)=>{},reset:async(_source:LayoutValueModel)=>{},image:async(_source:LayoutValueModel,_id:string,_file:File|null)=>{},placeholder:async(_source:LayoutValueModel,_key:string,_label:string)=>{}};
export function createLayoutValues(context:{slide:()=>Slide;document:()=>DeckDocument;selected:()=>string[];commands:(commands:Command[])=>Promise<unknown>;uploadImage:(file:File)=>Promise<{path:string;asset:Asset}>}){
 let resetVersion=0,last='';
 const signature=()=>{const page=context.slide();return JSON.stringify([page.layoutId,page.layoutValues,page.layoutImages,context.document().layouts.find(layout=>layout.id===page.layoutId)]);};
 const validate=(source:LayoutValueModel)=>{if(source.documentId!==context.document().id||source.pageId!==context.slide().id||source.signature!==signature())throw Error('本页母版内容已变化，输入已保留，请重新打开页面设置后核对');};
 function render(){
  const page=context.slide(),doc=context.document(),layout=doc.layouts.find(layout=>layout.id===page.layoutId),bound=signature(),key=JSON.stringify([doc.id,page.id,page.layoutId,resetVersion]),next=JSON.stringify([key,bound,page.layoutSourceId]);if(next===last)return;last=next;
  const html=new DOMParser().parseFromString(layout?.html??'','text/html'),texts=[...html.querySelectorAll<HTMLElement>('[data-notale-placeholder]')].map(node=>({id:node.dataset.notalePlaceholder!,label:node.dataset.notaleLabel||node.dataset.notalePlaceholder!,value:page.layoutValues?.[layout!.id]?.[node.dataset.notalePlaceholder!]??node.textContent??''})),images=[...html.querySelectorAll<HTMLElement>('[data-notale-image-placeholder]')].map(node=>({id:node.dataset.notaleImagePlaceholder!,label:node.dataset.notaleLabel||node.dataset.notaleImagePlaceholder!,overridden:!!page.layoutImages?.[layout!.id]?.[node.dataset.notaleImagePlaceholder!]}));
  model={key,value:JSON.stringify(Object.fromEntries(texts.map(text=>[text.id,text.value]))),signature:bound,documentId:doc.id,pageId:page.id,layoutId:page.layoutId??null,author:!!page.layoutSourceId,texts:texts.map(({id,label})=>({id,label})),images};for(const listener of listeners)listener();
 }
 layoutValueActions.save=async(source,raw)=>{validate(source);const draft=JSON.parse(raw),before=JSON.parse(source.value),values=Object.fromEntries(source.texts.filter(text=>draft[text.id]!==before[text.id]).map(text=>[text.id,draft[text.id]]));if(Object.values(values).some(value=>typeof value!=='string'))throw Error('请输入文字内容');if(Object.keys(values).length)await context.commands([{type:'layout.values',slideId:source.pageId,id:source.layoutId!,values}]);render();};
 layoutValueActions.reset=async source=>{validate(source);await context.commands([{type:'layout.values',slideId:source.pageId,id:source.layoutId!,values:Object.fromEntries(source.texts.map(text=>[text.id,null]))}]);resetVersion++;render();};
 layoutValueActions.image=async(source,id,file)=>{validate(source);if(!source.images.some(image=>image.id===id))throw Error('图片占位已变化');if(file){const upload=await context.uploadImage(file);validate(source);await context.commands([{type:'asset.put',...upload},{type:'layout.image',slideId:source.pageId,id:source.layoutId!,key:id,image:{path:upload.path,alt:file.name}}]);}else await context.commands([{type:'layout.image',slideId:source.pageId,id:source.layoutId!,key:id,image:null}]);render();};
 layoutValueActions.placeholder=async(source,key,label)=>{if(source.documentId!==context.document().id||source.pageId!==context.slide().id)throw Error('页面已切换');const target=context.selected()[0];if(!target||!context.slide().layoutSourceId)throw Error('请在母版编辑页选中一个文字对象');const node=new DOMParser().parseFromString(context.slide().html,'text/html').querySelector(`[data-notale-id="${CSS.escape(target)}"]`);await context.commands([{type:'element.patch',slideId:source.pageId,target,patch:{attributes:{[node?.tagName==='IMG'?'data-notale-image-placeholder':'data-notale-placeholder']:key,'data-notale-label':label}}}]);render();};
 return {render,reset(){resetVersion++;render();}};
}
