import {computePosition,flip,shift,offset,size} from '@floating-ui/dom';
export type ObjectMenuItem={id?:string;label:string;icon?:string;shortcut?:string;disabled?:boolean;reason?:string;danger?:boolean;separator?:boolean;children?:ObjectMenuItem[];run?:()=>unknown};
export type FormatControl={id:string;label:string;kind:'button'|'select'|'number'|'color';icon?:string;value?:string;mixed?:boolean;checked?:boolean;disabled?:boolean;options?:{value:string;label:string}[];min?:number;max?:number;run:(value:string)=>unknown};
const icons:Record<string,string>={cut:'M5 4l14 16M19 4L5 20M8 17a3 3 0 1 1-4-4M16 17a3 3 0 1 0 4-4',copy:'M8 8h12v12H8zM4 16V4h12',paste:'M8 5H5v16h14V5h-3M8 3h8v5H8z',duplicate:'M4 4h12v12H4zM9 20h11V9M7 10h6M10 7v6',delete:'M4 6h16M9 3h6M7 6l1 15h8l1-15M10 10v7M14 10v7',group:'M3 3h7v7H3zM14 14h7v7h-7zM14 3h7v7M3 14v7h7',lock:'M6 10h12v11H6zM8 10V7a4 4 0 0 1 8 0v3',format:'M5 4h14M12 4v16M8 20h8',bold:'M7 3h6a5 5 0 0 1 0 9H7M7 12h7a5 5 0 0 1 0 9H7V3',italic:'M10 3h10M4 21h10M15 3L9 21',underline:'M6 3v8a6 6 0 0 0 12 0V3M4 21h16',image:'M3 4h18v16H3zM3 16l6-6 5 5 3-3 4 4M16 8h1',crop:'M7 2v15h15M2 7h15v15',link:'M9 15l6-6M8 17l-2 2a4 4 0 0 1-5-5l5-5a4 4 0 0 1 5 0M16 7l2-2a4 4 0 0 1 5 5l-5 5a4 4 0 0 1-5 0',layers:'M3 7l9-5 9 5-9 5zM3 12l9 5 9-5M3 17l9 5 9-5',animation:'M8 4l12 8-12 8z',clear:'M4 15l9-12 8 6-9 12H9zM14 21h8'};
function icon(name?:string){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','2.2');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',icons[name??'']??icons.format);svg.append(path);return svg;}
/** A host-level context surface keeps text ranges inside the isolated editing frame. */
export function createObjectMenu(restoreFocus:()=>void,onError:(error:unknown)=>void=()=>{}){
 const surface=document.createElement('div');surface.id='object-context-surface';surface.hidden=true;document.body.append(surface);
 const toolbar=document.createElement('div');toolbar.className='object-mini-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','快捷格式');
 const menu=document.createElement('div');menu.id='object-context-menu';menu.setAttribute('role','menu');menu.setAttribute('aria-label','对象快捷菜单');surface.append(toolbar,menu);
 const submenu=document.createElement('div');submenu.className='object-submenu';submenu.setAttribute('role','menu');submenu.hidden=true;surface.append(submenu);
 let generation=0,valid=()=>true;
 const act=(fn:()=>unknown)=>{if(!valid()){close();return;}try{Promise.resolve(fn()).catch(onError);}catch(e){onError(e);}};
 function close(focus=false){generation++;if(surface.hidden)return;surface.hidden=true;submenu.hidden=true;if(focus)restoreFocus();}
 function renderItems(host:HTMLElement,items:ObjectMenuItem[]){host.replaceChildren();for(const item of items){if(item.separator){const sep=document.createElement('div');sep.setAttribute('role','separator');host.append(sep);}const b=document.createElement('button');b.type='button';b.setAttribute('role','menuitem');b.disabled=!!item.disabled;b.title=item.reason??'';b.dataset.action=item.id??item.label;b.classList.toggle('danger',!!item.danger);b.append(icon(item.icon));const label=document.createElement('span');label.className='menu-label';label.textContent=item.label;b.append(label);if(item.shortcut||item.children){const key=document.createElement('kbd');key.textContent=item.children?'›':item.shortcut!;b.append(key);}if(item.children){b.setAttribute('aria-haspopup','menu');const show=()=>{if(b.disabled)return;renderItems(submenu,item.children!);submenu.hidden=false;void computePosition(b,submenu,{strategy:'fixed',placement:'right-start',middleware:[offset(5),flip(),shift({padding:8})]}).then(p=>Object.assign(submenu.style,{left:p.x+'px',top:p.y+'px'}));};b.onpointerenter=show;b.onclick=show;b.onkeydown=e=>{if(e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();show();submenu.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();}};}else{b.onpointerenter=()=>{if(host===menu)submenu.hidden=true;};b.onclick=()=>{act(()=>item.run?.());close();};}host.append(b);}}
 function renderControls(controls:FormatControl[]){toolbar.replaceChildren();toolbar.hidden=!controls.length;for(const c of controls){let el:HTMLButtonElement|HTMLInputElement|HTMLSelectElement;
  if(c.kind==='button'){const b=document.createElement('button');b.type='button';b.append(icon(c.icon));b.setAttribute('aria-pressed',c.mixed?'mixed':String(!!c.checked));b.onmousedown=e=>e.preventDefault();b.onclick=()=>act(()=>c.run(''));el=b;}
  else if(c.kind==='select'){const select=document.createElement('select');for(const item of c.options??[])select.add(new Option(item.label,item.value));if(c.mixed)select.add(new Option('多种值',''),0);select.value=c.mixed?'':c.value??'';select.onchange=()=>act(()=>c.run(select.value));el=select;}
  else {const input=document.createElement('input');input.type=c.kind;if(c.min!==undefined)input.min=String(c.min);if(c.max!==undefined)input.max=String(c.max);input.value=c.kind==='color'?c.value??'#000000':c.mixed?'':c.value??'';input.placeholder=c.mixed?'—':'';input.onchange=()=>{if(input.reportValidity()&&input.value)act(()=>c.run(input.value));};el=input;}
  el.dataset.format=c.id;el.title=c.mixed?`${c.label} · 多种值`:c.label;el.setAttribute('aria-label',c.label);el.disabled=!!c.disabled;toolbar.append(el);
 }}
 surface.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();if(!submenu.hidden){submenu.hidden=true;menu.querySelector<HTMLButtonElement>('[aria-haspopup]')?.focus();}else close(true);return;}if(e.key==='Tab'){return;}const host=(e.target as HTMLElement).closest('[role="menu"],[role="toolbar"]') as HTMLElement;if(!host)return;const isToolbar=host===toolbar;if((e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement))return;const keys=isToolbar?['ArrowLeft','ArrowRight']:['ArrowUp','ArrowDown','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const items=[...host.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled)')],index=items.indexOf(document.activeElement as HTMLElement);items[e.key==='Home'?0:e.key==='End'?items.length-1:(index+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+items.length)%items.length]?.focus();});
 surface.addEventListener('focusout',()=>queueMicrotask(()=>{if(!surface.contains(document.activeElement)&&document.activeElement!==document.body)close();}));
 document.addEventListener('pointerdown',e=>{if(!surface.contains(e.target as Node))close();},true);
 window.addEventListener('resize',()=>close());document.addEventListener('scroll',e=>{if(!surface.contains(e.target as Node))close();},true);
 return {close,get opened(){return !surface.hidden;},open(x:number,y:number,items:ObjectMenuItem[],controls:FormatControl[]=[],isValid=()=>true){const token=++generation;valid=isValid;submenu.hidden=true;renderItems(menu,items);renderControls(controls);surface.hidden=false;const anchor={getBoundingClientRect:()=>new DOMRect(x,y,0,0)};void computePosition(anchor,surface,{strategy:'fixed',placement:'bottom-start',middleware:[offset(4),flip(),shift({padding:8}),size({padding:8,apply({availableHeight}){menu.style.maxHeight=Math.max(100,availableHeight-toolbar.offsetHeight-6)+'px';}})]}).then(p=>{if(token===generation)Object.assign(surface.style,{left:p.x+'px',top:p.y+'px'});});menu.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus({preventScroll:true});},refresh(controls:FormatControl[]){if(!surface.hidden&&!toolbar.contains(document.activeElement))renderControls(controls);}};
}
