import type {Command,Slide,DeckDocument} from '@notale/editor/browser';
export function createPageSettings(context:{document:()=>DeckDocument;current:()=>string;commands:(commands:Command[])=>Promise<unknown>;editMaster:(id:string,pageId:string)=>Promise<unknown>}){
 const dialog=document.createElement('dialog');dialog.id='page-settings-dialog';dialog.setAttribute('aria-labelledby','page-settings-title');
 dialog.innerHTML=`<header><h2 id="page-settings-title">页面设置</h2><button type="button" id="close-page-settings" aria-label="关闭页面设置">×</button></header><form id="page-basic-form"><label>页面名称<input id="page-settings-name" required maxlength="300"></label><label>章节<input id="page-settings-section" maxlength="300" placeholder="可选"></label><label class="page-hidden-option"><input id="page-settings-hidden" type="checkbox">放映时跳过此页</label><details class="settings-section"><summary>切换与计时</summary><label>页面转场<select id="page-settings-transition">${Object.entries({none:'无',fade:'淡入淡出',slide:'滑动',convex:'凸面旋转',concave:'凹面旋转',zoom:'缩放'}).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label class="page-hidden-option"><input id="page-settings-auto" type="checkbox">自动翻页</label><label id="page-settings-seconds-label">停留时间（秒）<input id="page-settings-seconds" type="number" min="0.001" step="0.001" value="5"></label></details><p id="page-settings-status" role="status"></p><footer><button id="save-page-settings" type="submit" class="primary">保存页面设置</button></footer></form><details class="settings-section" id="page-master-settings"><summary>母版</summary><label>本页母版<select id="page-master-choice"></select></label><div class="settings-actions"><button id="page-master-apply">应用本页</button><button id="page-master-edit">编辑母版</button><button id="page-master-detach">分离母版</button></div><div id="page-layout-values"></div></details>`;
 document.body.append(dialog);
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>dialog.querySelector<T>('#'+id)!;
 let source:Slide|undefined,documentId='',busy=false;
 const name=el<HTMLInputElement>('page-settings-name'),section=el<HTMLInputElement>('page-settings-section'),hidden=el<HTMLInputElement>('page-settings-hidden'),transition=el<HTMLSelectElement>('page-settings-transition'),auto=el<HTMLInputElement>('page-settings-auto'),seconds=el<HTMLInputElement>('page-settings-seconds'),choice=el<HTMLSelectElement>('page-master-choice');
 let renderValues=()=>{},resetValues=()=>{};
 const target=()=>source&&context.document().id===documentId?context.document().slides.find(p=>p.id===source!.id):undefined;
 function current(){const page=target();if(!page)throw Error('页面已变化，请关闭后重新打开设置');return page;}
 function timing(){seconds.disabled=!auto.checked;el('page-settings-seconds-label').hidden=!auto.checked;}
 function masters(){const page=current();const previous=choice.value;choice.replaceChildren(new Option('不使用母版',''),...context.document().layouts.map(l=>new Option(l.name,l.id)));choice.value=previous&&context.document().layouts.some(l=>l.id===previous)?previous:page.layoutId??'';el<HTMLButtonElement>('page-master-edit').disabled=!choice.value;el<HTMLButtonElement>('page-master-detach').disabled=!page.layoutId;renderValues();}
 function open(id:string){if(busy)return;const page=context.document().slides.find(p=>p.id===id);if(!page||page.layoutSourceId)return;source=structuredClone(page);documentId=context.document().id;name.value=page.name;section.value=page.section;hidden.checked=page.hidden;transition.value=page.transition;auto.checked=page.advanceAfter>0;seconds.value=String(page.advanceAfter? page.advanceAfter/1000:5);timing();choice.value='';resetValues();el('page-settings-status').textContent='';el<HTMLButtonElement>('save-page-settings').disabled=false;masters();dialog.showModal();name.focus();name.select();}
 async function run(action:()=>Promise<unknown>){if(busy)return;busy=true;el('page-settings-status').textContent='';const controls=[...dialog.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement>('input,button,select,textarea')];const disabled=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);try{await action();}catch(e){el('page-settings-status').textContent=e instanceof Error?e.message:String(e);}finally{busy=false;controls.forEach((c,i)=>c.disabled=disabled[i]);timing();if(dialog.open&&target())masters();}}
 el('page-basic-form').onsubmit=e=>{e.preventDefault();void run(async()=>{const page=current(),draft={name:name.value.trim(),section:section.value.trim(),hidden:hidden.checked,transition:transition.value as Slide['transition'],advanceAfter:auto.checked?Math.round(Number(seconds.value)*1000):0};if(!draft.name||auto.checked&&(!Number.isFinite(draft.advanceAfter)||draft.advanceAfter<=0))throw Error('请输入有效的名称和停留时间');const patch:Record<string,unknown>={};for(const key of Object.keys(draft) as (keyof typeof draft)[])if(draft[key]!==source![key]){if(page[key]!==source![key])throw Error('页面设置已被更新，输入已保留，请核对后重新打开设置');patch[key]=draft[key];}if(Object.keys(patch).length)await context.commands([{type:'slide.update',slideId:page.id,patch} as Command]);dialog.close();});};
 el('page-master-apply').onclick=()=>void run(async()=>{const page=current();await context.commands([{type:'slide.update',slideId:page.id,patch:{layoutId:choice.value||null}}]);});
 el('page-master-detach').onclick=()=>void run(async()=>{await context.commands([{type:'layout.detach',slideId:current().id}]);choice.value='';});
 el('page-master-edit').onclick=()=>void run(async()=>{const id=choice.value,page=current();if(!id)return;await context.editMaster(id,page.id);dialog.close();});
 auto.onchange=timing;choice.onchange=()=>{el<HTMLButtonElement>('page-master-edit').disabled=!choice.value;};name.oninput=()=>{el<HTMLButtonElement>('save-page-settings').disabled=!name.value.trim();};
 el('close-page-settings').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('keydown',e=>e.stopPropagation());
 document.getElementById('open-page-settings')!.onclick=()=>open(context.current());const rail=document.getElementById('slides')!;
 rail.addEventListener('contextmenu',e=>{const card=(e.target as Element).closest<HTMLElement>('[data-slide]');if(card){e.preventDefault();open(card.dataset.slide!);}});
 rail.addEventListener('keydown',e=>{if(e.key==='F2'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){const card=(e.target as Element).closest<HTMLElement>('[data-slide]');if(card){e.preventDefault();e.stopPropagation();open(card.dataset.slide!);}}});
 return {open,target,mount:el('page-layout-values'),bindValues(render:()=>void,reset:()=>void){renderValues=render;resetValues=reset;},render(){if(dialog.open&&target())renderValues();}};
}
