import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
type Entry = { version?: string; license?: string; dev?: boolean; optional?: boolean; link?: boolean };
const projects = [ ['frontend', '.'], ['backend', '../notale-editor'] ] as const;
const records: {project:string;path:string;version:string;license:string;development:boolean;optional:boolean}[] = [];
for (const [project, directory] of projects) {
  const lock = JSON.parse(await readFile(resolve(directory, 'package-lock.json'), 'utf8')) as {packages:Record<string,Entry>};
  for (const [path, entry] of Object.entries(lock.packages)) {
    if (!path || entry.link) continue;
    records.push({project,path,version:entry.version ?? 'UNKNOWN',license:entry.license ?? 'UNKNOWN',development:!!entry.dev,optional:!!entry.optional});
  }
}
records.sort((a,b)=>a.project.localeCompare(b.project)||a.path.localeCompare(b.path));
const licenses = [...new Set(records.map(record=>record.license))].sort();
await mkdir('docs/release', {recursive:true});
await writeFile('docs/release/dependency-licenses.json', JSON.stringify({basis:'npm lockfile metadata; not a legal clearance or bundled-asset audit',packages:records},null,2)+'\n');
await writeFile('docs/release/DEPENDENCY-LICENSES.md', `# Dependency license inventory\n\nGenerated by npm run licenses:inventory from both editor lockfiles. Metadata only: package license texts, attribution requirements and bundled assets still need review. Development and optional dependencies remain in the inventory.\n\n| Declared license | Lock entries |\n| --- | ---: |\n${licenses.map(license=>`| ${license} | ${records.filter(record=>record.license===license).length} |`).join('\n')}\n\nUnknown declarations:\n\n${records.filter(record=>record.license==='UNKNOWN').map(record=>`- ${record.project}: ${record.path}@${record.version}`).join('\n')||'None.'}\n`);
console.log(`Inventoried ${records.length} lock entries; ${records.filter(record=>record.license==='UNKNOWN').length} missing license declarations. See docs/release/.`);
