'use client';
import {useSyncExternalStore} from 'react';
import {connectorInspectorState,type ConnectorDraft,type EndpointDraft} from '../state/connector-inspector';
export function ConnectorInspector(){
 const model=useSyncExternalStore(connectorInspectorState.subscribe,connectorInspectorState.getSnapshot,connectorInspectorState.getServerSnapshot),draft=model.draft;
 const select=(key:'kind'|'dash',label:string,options:Record<string,string>)=><label>{label}<select id={'connector-'+key} value={draft?.[key]??''} onChange={e=>model.change?.({[key]:e.target.value})}>{Object.entries(options).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;
 const endpoint=(side:'start'|'end')=>{if(!draft)return null;const value=draft[side],label=side==='start'?'起点':'终点';const change=(patch:Partial<EndpointDraft>)=>model.change?.({[side]:{...value,...patch}});return <div key={side}><div id={`connector-${side}-point`} hidden={!!value.target}>{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<input id={`connector-${side}-${axis}`} type="number" step="any" value={value[axis]} onChange={e=>change({[axis]:e.target.value})}/></label>)}</div><label>{label}对象<select id={'connector-'+side} value={value.target} onChange={e=>change({target:e.target.value})}><option value="">自由端点</option>{model.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>{label}位置<select id={`connector-${side}-anchor`} disabled={!value.target} value={value.anchor} onChange={e=>change({anchor:e.target.value})}>{Object.entries({auto:'自动',top:'上边',right:'右边',bottom:'下边',left:'左边'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>;};
 return <fieldset id="connector-panel" hidden={!draft} disabled={model.busy}><legend>对象连接线</legend>{endpoint('start')}{endpoint('end')}{select('kind','线形',{straight:'直线',elbow:'折线',curve:'曲线'})}<label>颜色<input id="connector-color" value={draft?.color??''} onChange={e=>model.change?.({color:e.target.value})}/></label><label>线宽<input id="connector-width" type="number" min=".5" max="30" step=".5" value={draft?.width??''} onChange={e=>model.change?.({width:e.target.value})}/></label>{select('dash','线条',{solid:'实线',dashed:'虚线',dotted:'点线'})}{(['start','end'] as const).map(side=>{const key=`${side}Arrow` as keyof Pick<ConnectorDraft,'startArrow'|'endArrow'>;return <label key={side}><input id={`connector-${side}-arrow`} type="checkbox" checked={draft?.[key]??false} onChange={e=>model.change?.({[key]:e.target.checked})}/>{side==='start'?'起点':'终点'}箭头</label>;})}<button id="save-connector" onClick={()=>void model.save?.()}>应用连接线</button>{model.error&&<p role="alert">{model.error}</p>}</fieldset>;
}
