'use client';
import {sidebar} from '../state/sidebar';
import {useSyncExternalStore,type ReactNode} from 'react';
import {selectionToolsState} from '../selection-tools';
import {editorActions,editorSession} from '../state/editor-session';
import {useEditorSelector,shallowEqual} from '../state/use-editor-selector';
const icons:Record<string,ReactNode>={plus:<><circle cx="12" cy="12" r="9"/><path d="M7 12h10M12 7v10"/></>,trash:<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>,left:<path d="m14 5-7 7 7 7"/>,right:<path d="m10 5 7 7-7 7"/>,zoomIn:<path d="M5 12h14M12 5v14"/>,zoomOut:<path d="M5 12h14"/>,overview:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,align:<path d="M4 3v18M8 6h12v4H8ZM8 14h8v4H8Z"/>,distribute:<path d="M3 3v18M21 3v18M8 7h8v10H8Z"/>};
export function DockIcon({name}:{name:string}){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>;}
function run(action:()=>unknown){try{void Promise.resolve(action()).catch(editorActions.reportError);}catch(cause){editorActions.reportError(cause);}}
function usePages(){return useEditorSelector(state=>{const pages=state.document?.document.slides.filter(page=>!page.layoutSourceId)??[],index=pages.findIndex(page=>page.id===state.activePageId);return {count:pages.length,index,previous:pages[index-1]?.id,next:pages[index+1]?.id,ready:!!state.document};},shallowEqual);}
export function DockPageActions(){const pages=usePages();return <><button id="dock-add-page" className="icon-button" title="添加页面" aria-label="添加页面" disabled={!pages.ready||pages.index<0} onClick={()=>run(editorActions.addPage)}><DockIcon name="plus"/></button><button id="dock-delete-page" title="删除当前页" aria-label="删除当前页" disabled={pages.index<0||pages.count<=1} onClick={()=>run(editorActions.deletePage)}><DockIcon name="trash"/></button></>;}
export function DockPageNavigation(){const pages=usePages();return <><button id="dock-previous-page" className="icon-button" title="上一页" aria-label="上一页" disabled={!pages.previous} onClick={()=>{if(pages.previous)run(()=>editorActions.showPage(pages.previous!));}}><DockIcon name="left"/></button><span id="page-position" className="page-position">{!pages.ready?'':pages.index<0?'母版编辑':`${pages.index+1} / ${pages.count}`}</span><button id="dock-next-page" className="icon-button" title="下一页" aria-label="下一页" disabled={pages.index<0||!pages.next} onClick={()=>{if(pages.next)run(()=>editorActions.showPage(pages.next!));}}><DockIcon name="right"/></button></>;}
export function PageName(){const name=useEditorSelector(state=>state.document?.document.slides.find(page=>page.id===state.activePageId)?.name??'');return <span id="page-name">{name}</span>;}
export function PageCount(){const count=useEditorSelector(state=>state.document?.document.slides.filter(page=>!page.layoutSourceId).length??0);return <span id="slide-count">{count}</span>;}

export function OverviewButton(){const open=useEditorSelector(state=>state.overview);return <button id="overview" className="icon-button" title="页面总览" aria-label="页面总览" aria-pressed={open} onClick={()=>{sidebar.openPages();editorSession.update({overview:!editorSession.getSnapshot().overview,overviewPage:0});}}><DockIcon name="overview"/></button>;}

export function ObjectLockButton(){const count=useEditorSelector(state=>state.selectedIds.length);return <button id="lock" disabled={!count} onClick={()=>run(editorActions.toggleObjectLock)}>锁定 / 解锁</button>;}

export function SelectionTools(){const tools=useSyncExternalStore(selectionToolsState.subscribe,selectionToolsState.getSnapshot,selectionToolsState.getServerSnapshot);const labels:Record<string,string>={group:'编组',ungroup:'取消编组','align-left':'左对齐',distribute:'水平等距分布'};return <>{tools.length>0&&<i id="selection-tools-separator"/>}{tools.map(tool=><button key={tool.id} id={tool.id} disabled={tool.disabled} title={tool.title||labels[tool.id]} aria-label={labels[tool.id]} className={tool.id==='align-left'||tool.id==='distribute'?'icon-button':undefined} onClick={()=>run(()=>editorActions.selectionTool(tool.id))}>{tool.id==='align-left'?<DockIcon name="align"/>:tool.id==='distribute'?<DockIcon name="distribute"/>:labels[tool.id]}</button>)}</>;}

export function EmptyCanvas(){const message=useEditorSelector(state=>state.emptyMessage);return <div id="empty" hidden={message===null}>{message}</div>;}
