'use client';
import {useState,useSyncExternalStore,Fragment} from 'react';
import {insertCategories,type Item} from '../insert-panel';
import {insertActionsState,runInsert,showInsertionDrop} from '../state/insert-actions';
import {DiagramTemplates,DiagramStatus} from './template-library';
import {templateLibraryActions} from '../state/template-library';
import {AssetLibrary} from './asset-library';
import {RevealInsert} from './reveal-preset';
import {LinkInsertButton} from './link-editor';
function InsertButton({item,hidden=false}:{item:Item;hidden?:boolean}){
 const actions=useSyncExternalStore(insertActionsState.subscribe,insertActionsState.getSnapshot,insertActionsState.getServerSnapshot);
 return <button type="button" hidden={hidden} disabled={!actions} draggable={!!actions} data-insert={item.kind} data-symbol={item.symbol} aria-label={item.title??`插入${item.label}`} title={item.title??`插入${item.label}`} onClick={()=>{if(actions)void runInsert(actions,item.kind,item.symbol);}} onDragStart={event=>{if(!actions){event.preventDefault();return;}event.dataTransfer.setData('application/x-notale-insert',JSON.stringify({kind:item.kind,value:item.symbol}));event.dataTransfer.effectAllowed='copy';showInsertionDrop(actions,true);}} onDragEnd={()=>{if(actions)showInsertionDrop(actions,false);}}><span style={{display:'contents'}} dangerouslySetInnerHTML={{__html:item.preview}}/><span className="insert-item-label">{item.label}</span></button>;
}
function IconGallery({items}:{items:Item[]}){const [query,setQuery]=useState('');const normalized=query.trim().toLocaleLowerCase();return <><input id="icon-search" type="search" placeholder="搜索图标" aria-label="搜索图标" autoComplete="off" value={query} onChange={event=>setQuery(event.target.value)}/><div id="icon-gallery" className="resource-grid icon-grid">{items.map(item=><InsertButton key={item.kind} item={item} hidden={!!normalized&&!((item.title??`插入${item.label}`)+item.kind).toLocaleLowerCase().includes(normalized)}/>)}</div></>;}
export function InsertCatalog(){const [mediaOpen,setMediaOpen]=useState(false);return <>{insertCategories.map(category=><details key={category.key} className="insert-category" data-insert-category={category.key} open={category.open} onToggle={event=>{if(category.key==='media')setMediaOpen(event.currentTarget.open);if(category.key==='diagrams'&&event.currentTarget.open)void templateLibraryActions.ensure();}}><summary>{category.label}</summary><section data-library={category.key}>{category.groups.map((group,index)=><Fragment key={group.id??index}>{group.label&&<h3 className="insert-group-title">{group.label}</h3>}{group.id==='icon-gallery'?<IconGallery items={group.items}/>:<div id={group.id} className={'resource-grid '+(group.className??'')}>{category.key==='diagrams'&&<DiagramTemplates/>}{group.items.map(item=><InsertButton key={item.kind+':'+(item.symbol??'')} item={item}/>)}</div>}</Fragment>)}{category.key==='diagrams'&&<DiagramStatus/>}{category.key==='media'&&<AssetLibrary visible={mediaOpen}/>}{category.key==='interactive'&&<><RevealInsert/><LinkInsertButton/></>}</section></details>)}</>;}
