'use client';
import {unavailableFeature} from '../feature-availability';
import {useState,useSyncExternalStore} from 'react';
import {layoutManagerState} from '../state/layout-manager';
const useLayout=()=>useSyncExternalStore(layoutManagerState.subscribe,layoutManagerState.getSnapshot,layoutManagerState.getServerSnapshot);
export function LayoutManager(){const model=useLayout();const [name,setName]=useState('课程页脚'),[preset,setPreset]=useState('footer');const run=(action:string)=>void model.run?.(action,name,preset);return <section id="global-master-mount">
<section id="layout-manager"><h3>母版</h3><label>名称<input id="visual-layout-name" value={name} onChange={e=>setName(e.target.value)}/></label><label {...unavailableFeature}>起始版式<select disabled id="visual-layout-preset" value={preset} onChange={e=>setPreset(e.target.value)}><option value="footer">页脚与页码</option><option value="title">标题与页脚</option><option value="blank">空白布局</option></select></label><button id="create-visual-layout" disabled={model.busy||!model.run} onClick={()=>run('create')}>创建母版并编辑</button><p id="layout-usage" role="status">{model.usage}</p></section>
<button id="publish-layout-canvas" {...unavailableFeature} disabled onClick={()=>run('publish')}>发布画布修改</button>
<details id="layout-source-controls" {...unavailableFeature}><summary>高级：布局源码</summary><fieldset disabled={model.busy||!model.run}><label>布局名称<input id="layout-name" value={model.draft.name} onChange={e=>model.change?.({...model.draft,name:e.target.value})}/></label><label>布局对象 HTML<textarea id="layout-html" rows={4} value={model.draft.html} onChange={e=>model.change?.({...model.draft,html:e.target.value})}/></label><label>布局 CSS<textarea id="layout-css" rows={3} value={model.draft.css} onChange={e=>model.change?.({...model.draft,css:e.target.value})}/></label><button id="new-layout" onClick={()=>run('new')}>新建页脚母版</button><button id="save-layout" disabled={!model.selected} onClick={()=>run('save')}>更新母版</button></fieldset></details>
<section id="master-library" hidden={!model.layouts.length}><label>选择母版<select id="shared-layout" value={model.selected} disabled={model.busy||model.editing} onChange={e=>model.select?.(e.target.value)}><option value="">选择母版</option>{model.layouts.map(l=><option key={l.id} value={l.id}>{l.name} · {l.count} 页使用</option>)}</select></label><button id="apply-layout-all" disabled={model.busy||!model.selected||model.editing} onClick={()=>run('apply')}>应用全部页面</button><button id="edit-layout-canvas" disabled={model.busy||!model.selected||model.editing} onClick={()=>run('edit')}>画布编辑母版</button></section>{model.error&&<p role="alert">{model.error}</p>}
</section>;}
export function MasterEditBanner(){const model=useLayout();return <div id="master-edit-banner" hidden={!model.editing}><span id="master-edit-label">{model.label}</span><button id="publish-master-return" disabled={model.busy} onClick={()=>void model.run?.('publish-return')}>发布并返回页面</button><button id="leave-master" disabled={model.busy} onClick={()=>void model.run?.('leave')}>返回页面</button></div>;}
