'use client';
import { isComposingKey } from "../keyboard";

import {Fragment,useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore,type KeyboardEvent} from 'react';
import {createPortal} from 'react-dom';
import {computePosition,flip,shift,offset,size} from '@floating-ui/dom';
import {objectMenuState,type ObjectMenuItem,type FormatControl} from '../state/object-menu';
import {objectMenuIcons} from '../object-menu-icons';
function Icon({name}:{name?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={objectMenuIcons[name??'']??objectMenuIcons.format}/></svg>;}
export function ObjectMenu(){const model=useSyncExternalStore(objectMenuState.subscribe,objectMenuState.getSnapshot,objectMenuState.getServerSnapshot);return model.open?createPortal(<MenuSurface key={model.generation} model={model}/>,document.body):null;}
type Model=ReturnType<typeof objectMenuState.getSnapshot>;
function MenuSurface({model}:{model:Model}){
 const surface=useRef<HTMLDivElement>(null),menu=useRef<HTMLDivElement>(null),toolbar=useRef<HTMLDivElement>(null),sub=useRef<HTMLDivElement>(null);
 const [position,setPosition]=useState({left:model.x,top:model.y}),[maximum,setMaximum]=useState<number>(),[submenu,setSubmenu]=useState<{items:ObjectMenuItem[];anchor:HTMLButtonElement;focus:boolean}>(),[subPosition,setSubPosition]=useState({left:0,top:0});
 useLayoutEffect(()=>{let live=true;const anchor={getBoundingClientRect:()=>new DOMRect(model.x,model.y,0,0)};void computePosition(anchor,surface.current!,{strategy:'fixed',placement:'bottom-start',middleware:[offset(4),flip(),shift({padding:8}),size({padding:8,apply({availableHeight}){if(live)setMaximum(Math.max(100,availableHeight-(toolbar.current?.offsetHeight??0)-6));}})]}).then(value=>{if(live)setPosition({left:value.x,top:value.y});});menu.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus({preventScroll:true});return()=>{live=false;};},[model.generation,model.x,model.y]);
 useLayoutEffect(()=>{if(!submenu)return;let live=true;void computePosition(submenu.anchor,sub.current!,{strategy:'fixed',placement:'right-start',middleware:[offset(5),flip(),shift({padding:8})]}).then(value=>{if(live)setSubPosition({left:value.x,top:value.y});});if(submenu.focus)sub.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();return()=>{live=false;};},[submenu]);
 useEffect(()=>{const outside=(event:Event)=>{if(event.target instanceof Node&&!surface.current?.contains(event.target))model.close?.();};const resize=()=>model.close?.();document.addEventListener('pointerdown',outside,true);document.addEventListener('scroll',outside,true);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',outside,true);document.removeEventListener('scroll',outside,true);window.removeEventListener('resize',resize);};},[model.close]);
 function keyboard(event:KeyboardEvent){event.stopPropagation();if(isComposingKey(event.nativeEvent))return;if(event.key==='Escape'){event.preventDefault();if(submenu){submenu.anchor.focus();setSubmenu(undefined);}else model.close?.(true);return;}const target=event.target as HTMLElement;if(target instanceof HTMLInputElement||target instanceof HTMLSelectElement)return;const host=target.closest('[role="menu"],[role="toolbar"]');if(!host)return;if(event.key==='ArrowLeft'&&submenu&&host===sub.current){event.preventDefault();submenu.anchor.focus();setSubmenu(undefined);return;}const keys=host===toolbar.current?['ArrowLeft','ArrowRight']:['ArrowUp','ArrowDown','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();const items=[...host.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled)')],index=items.indexOf(document.activeElement as HTMLElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1)+items.length)%items.length]?.focus();}
 function items(values:ObjectMenuItem[],nested=false){return values.map((item,index)=><Fragment key={item.id??item.label+index}>{item.separator&&<div role="separator"/>}<button type="button" role="menuitem" disabled={item.disabled} title={item.reason??''} data-action={item.id??item.label} className={item.danger?'danger':undefined} aria-haspopup={item.children?'menu':undefined} aria-expanded={item.children?submenu?.items===item.children:undefined} aria-controls={item.children&&submenu?.items===item.children?'object-context-submenu':undefined} onPointerEnter={event=>{if(item.disabled)return;if(item.children)setSubmenu({items:item.children,anchor:event.currentTarget,focus:false});else if(!nested)setSubmenu(undefined);}} onClick={event=>{if(item.children)setSubmenu({items:item.children,anchor:event.currentTarget,focus:event.detail===0});else model.act?.(()=>item.run?.(),true);}} onKeyDown={event=>{if(isComposingKey(event.nativeEvent))return;if(event.key==='ArrowRight'&&item.children){event.preventDefault();event.stopPropagation();setSubmenu({items:item.children,anchor:event.currentTarget,focus:true});}}}><Icon name={item.icon}/><span className="menu-label">{item.label}</span>{(item.shortcut||item.children)&&<kbd>{item.children?'›':item.shortcut}</kbd>}</button></Fragment>);}
 return <div ref={surface} id="object-context-surface" style={position} onKeyDown={keyboard} onBlur={()=>{queueMicrotask(()=>{const node=surface.current;if(node&&!node.contains(document.activeElement)&&document.activeElement!==document.body)model.close?.();});}}><div ref={toolbar} className="object-mini-toolbar" role="toolbar" aria-label="快捷格式" hidden={!model.controls.length} onFocusCapture={()=>model.toolbarFocus?.(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))model.toolbarFocus?.(false);}}>{model.controls.map(control=><Control key={control.id} control={control} act={action=>model.act?.(action)}/>)}</div><div ref={menu} id="object-context-menu" role="menu" aria-label="对象快捷菜单" style={{maxHeight:maximum}}>{items(model.items)}</div>{submenu&&<div ref={sub} id="object-context-submenu" className="object-submenu" role="menu" style={subPosition}>{items(submenu.items,true)}</div>}</div>;
}
function Control({control:c,act}:{control:FormatControl;act:(action:()=>unknown)=>void}){
 const initial=c.kind==='color'?c.value??'#000000':c.mixed?'':c.value??'';const [value,setValue]=useState(initial),dirty=useRef(false);useEffect(()=>{if(!dirty.current)setValue(initial);},[initial]);
 const props={'data-format':c.id,title:c.mixed?`${c.label} · 多种值`:c.label,'aria-label':c.label,disabled:c.disabled};
 if(c.kind==='button')return <button {...props} type="button" aria-pressed={c.mixed?'mixed':!!c.checked} onMouseDown={event=>event.preventDefault()} onClick={()=>act(()=>c.run(''))}><Icon name={c.icon}/></button>;
 if(c.kind==='select')return <select {...props} value={value} onChange={event=>{setValue(event.target.value);act(()=>c.run(event.target.value));}}>{c.mixed&&<option value="">多种值</option>}{c.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>;
 return <input {...props} type={c.kind} min={c.min} max={c.max} value={value} placeholder={c.mixed?'—':''} onChange={event=>{const next=event.target.value;setValue(next);dirty.current=true;if(c.kind==='color'&&next)act(()=>c.run(next));}} onBlur={event=>{if(c.kind==='number'&&dirty.current&&event.currentTarget.reportValidity()&&value){dirty.current=false;act(()=>c.run(value));}}} onKeyDown={event=>{if(isComposingKey(event.nativeEvent))return;if(event.key==='Escape'&&c.kind==='number'&&dirty.current){event.preventDefault();event.stopPropagation();dirty.current=false;setValue(initial);}else if(event.key==='Enter'){event.preventDefault();if(event.currentTarget.reportValidity())event.currentTarget.blur();}}}/>;
}
