'use client';
import { isComposingKey } from "../keyboard";

import {useSyncExternalStore,type ReactNode} from 'react';
import {vectorInspectorState,vectorValue,vectorNumberBounds} from '../state/vector-inspector';
import {vectorActions,vectorGeometry} from '../vector-catalog';
function useVector(){return useSyncExternalStore(vectorInspectorState.subscribe,vectorInspectorState.getSnapshot,vectorInspectorState.getServerSnapshot);}
function Section({label,children}:{label:string;children:ReactNode}){return <details open={['图形外观','文字','图形操作','顶点'].includes(label)}><summary>{label}</summary>{children}</details>;}
function Field({label,property,numeric=false,attribute=false,options}:{label:string;property:string;numeric?:boolean;attribute?:boolean;options?:[string,string][]}){
 const model=useVector(),value=vectorValue(model.state,property,attribute),key=`${attribute?'attribute':'style'}:${property}`,mixed=value===undefined;
 const bounds=numeric?vectorNumberBounds(property,attribute):undefined;
 const displayed=model.drafts[key]??(mixed?'':numeric?String(parseFloat(value!)||0):value!);
 const disabled=!!model.state.processing||(model.state.items??[]).some(item=>item.locked||item.generated);
 return <label className="vector-field"><span>{label}</span>{options?<select aria-label={label} disabled={disabled} value={displayed} onChange={event=>{model.change?.(property,event.target.value,attribute);model.commit?.(property,numeric,attribute);}}>{(mixed||!options.some(([key])=>key===displayed))&&<option value="">{mixed?'混合':'默认'}</option>}{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input aria-label={label} type={numeric?'number':'text'} step={numeric?'any':undefined} min={bounds?.min} max={bounds?.max} placeholder={mixed?'混合':''} disabled={disabled} value={displayed} onChange={event=>model.change?.(property,event.target.value,attribute)} onBlur={()=>model.commit?.(property,numeric,attribute)} onKeyDown={event=>{if(isComposingKey(event.nativeEvent))return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();model.cancel?.(property,attribute);event.currentTarget.blur();}else if(event.key==='Enter'){event.preventDefault();event.stopPropagation();model.commit?.(property,numeric,attribute);}}}/>}</label>;
}
export function VectorInspector(){
 const model=useVector(),state=model.state,items=state.items??[],disabled=!!state.processing||items.some(item=>item.locked||item.generated),run=model.run;
 const button=(label:string,action:string,data:Record<string,unknown>={},blocked=disabled)=><button type="button" title={label} disabled={blocked} onClick={()=>run?.(action,data)}>{label}</button>;
 const shape=items.every(item=>['path','rect','circle','ellipse','line','polyline','polygon'].includes(item.tag));
 const invalid=(action:string)=>(action==='nodes'&&!shape)||(action==='text'&&!items.some(item=>['text','tspan','textPath'].includes(item.tag)))||(['union','subtract','intersect','exclude','clip','mask','group'].includes(action)&&items.length<2)||(action==='detach'&&items[0]?.tag!=='use')||(action==='clip-edit'&&!items[0]?.attributes['clip-path']&&!items[0]?.attributes.mask)||(action==='source'&&!items[0]?.attributes['data-notale-vector-operation'])||(action==='ungroup'&&items[0]?.tag!=='g')||(['split','offset','outline','flatten'].includes(action)&&!shape);
 return <section id="vector-properties" className="vector-properties" hidden={!state.active}>{state.active&&items.length>0&&<>
 {state.gradientEditing&&button('完成渐变编辑','exit',{},false)}
 {state.sourceEditing&&<>{(state.sourceItems??[]).map(item=><button key={item.id} type="button" title={item.name} disabled={!!state.processing} onClick={()=>run?.('source',{id:item.id})}>{item.name}</button>)}{button('完成源形状编辑','finish-source',{},false)}</>}
 {state.processing&&button('取消计算','cancel',{},false)}
 {items.some(item=>item.generated)&&<><p>此图形由互动组件生成，请通过组件参数编辑。</p>{button('创建可编辑副本','snapshot',{},false)}</>}
 {items.length===1&&vectorGeometry[items[0].tag]&&<Section label="形状">{vectorGeometry[items[0].tag].map(([property,label])=><Field key={property} label={label} property={property} numeric={property!=='startOffset'} attribute/>)}</Section>}
 <Section label="图形外观"><Field label="填充" property="fill"/><Field label="描边" property="stroke"/><Field label="描边宽度" property="stroke-width" numeric/><Field label="透明度" property="opacity" numeric/><Field label="虚线" property="stroke-dasharray"/>
 <Field label="端点" property="stroke-linecap" options={[["butt","平头"],["round","圆头"],["square","方头"]]}/><Field label="连接" property="stroke-linejoin" options={[["miter","尖角"],["round","圆角"],["bevel","斜角"]]}/><Field label="混合" property="mix-blend-mode" options={[["normal","正常"],["multiply","正片叠底"],["screen","滤色"],["overlay","叠加"],["darken","变暗"],["lighten","变亮"]]}/>
 {button('起点箭头','arrow',{end:'start'})}{button('终点箭头','arrow',{end:'end'})}<button type="button" title="清除箭头" disabled={disabled} onClick={()=>{run?.('style',{property:'marker-start',value:'none'});run?.('style',{property:'marker-end',value:'none'});}}>清除箭头</button></Section>
 {items.some(item=>['text','tspan','textPath'].includes(item.tag))&&<Section label="文字"><Field label="字体" property="font-family"/><Field label="字号" property="font-size" numeric/><Field label="字距" property="letter-spacing" numeric/><Field label="对齐" property="text-anchor" options={[["start","左"],["middle","中"],["end","右"]]}/>{button('粗体','style',{property:'font-weight',value:items[0].styles['font-weight']==='700'?'400':'700'})}{button('斜体','style',{property:'font-style',value:'italic'})}{button('横排','style',{property:'writing-mode',value:'horizontal-tb'})}{button('竖排','style',{property:'writing-mode',value:'vertical-rl'})}</Section>}
 {items.length===1&&items[0].tag==='text'&&<Section label="文字转轮廓"><p>选择文字实际使用的字体文件，转换后可编辑顶点。</p><input key={model.scope} type="file" accept=".ttf,.otf,.woff,.woff2" aria-label="选择此文字使用的字体文件" disabled={disabled} onChange={event=>{const file=event.target.files?.[0];if(file)void model.file?.(file,'font');event.target.value='';}}/></Section>}
 <Section label="图片填充"><input key={model.scope} type="file" accept="image/png,image/jpeg,image/webp" aria-label="选择填充图片" disabled={disabled} onChange={event=>{const file=event.target.files?.[0];if(file)void model.file?.(file,'image');event.target.value='';}}/></Section>
 <Section label="渐变"><div className="vector-row">{model.colors.map((color,index)=><input key={index} type="color" value={color} disabled={disabled} aria-label={index===0?'起始颜色':index===model.colors.length-1?'结束颜色':`渐变色标 ${index+1}`} onChange={event=>model.configure?.({colors:model.colors.map((value,i)=>i===index?event.target.value:value)})}/>)}</div><button type="button" title="添加色标" disabled={disabled} onClick={()=>model.configure?.({colors:[...model.colors.slice(0,-1),'#ffffff',model.colors.at(-1)!]})}>添加色标</button>{button('线性渐变','gradient',{kind:'linear',stops:model.colors.map((color,i)=>({offset:i/(model.colors.length-1),color}))})}{button('径向渐变','gradient',{kind:'radial',stops:model.colors.map((color,i)=>({offset:i/(model.colors.length-1),color}))})}{button('在画布上编辑渐变','gradient-handles',{},disabled||items.length!==1||!items[0].styles.fill?.includes('url('))}</Section>
 <Section label="效果">{button('阴影','effect',{kind:'shadow',value:5})}{button('模糊','effect',{kind:'blur',value:5})}{button('清除效果','style',{property:'filter',value:'none'})}</Section>
 <Section label={state.editing?'顶点':'图形操作'}>{state.editing?<>{[['corner','尖角'],['smooth','平滑'],['symmetric','对称'],['close','开合路径'],['reverse','反向'],['simplify','简化'],['break','断开'],['join','连接端点'],['delete','删除顶点']].map(([action,label])=><button key={action} type="button" title={label} disabled={disabled} onClick={()=>run?.('node',{action})}>{label}</button>)}<input type="number" aria-label="顶点旋转角度" value={model.angle} disabled={disabled} onChange={event=>model.configure?.({angle:event.target.value})}/>{button('旋转顶点','node',{action:'rotate',value:Number(model.angle)},disabled||!model.angle.trim()||!Number.isFinite(Number(model.angle)))}{button('放大顶点选区','node',{action:'scale',value:1.1})}{button('缩小顶点选区','node',{action:'scale',value:1/1.1})}{button('完成','exit',{},false)}</>:vectorActions.map(([action,label])=><button key={action} type="button" title={label} disabled={disabled||invalid(action)} onClick={()=>run?.(action,action==='offset'?{amount:10}:{})}>{label}</button>)}</Section>
 <Section label="在图中绘制">{[['rect','矩形'],['ellipse','椭圆'],['line','直线'],['polygon','多边形'],['star','星形'],['arrow','箭头'],['arc','圆弧'],['pen','钢笔'],['pencil','自由曲线']].map(([kind,label])=><button key={kind} type="button" title={label} disabled={disabled} onClick={()=>run?.('draw',{kind})}>{label}</button>)}</Section>
 {model.error&&<><p role="alert">{model.error}</p><button type="button" onClick={()=>model.reset?.()}>载入最新属性</button></>}
 </>}</section>;
}
