'use client';
import {PosterImage} from '../canvas/poster-image';
import { isComposingKey } from "../keyboard";
import {ResourceNotice} from '../components/resource-notice';
import {useCallback,useEffect,useRef,useState,useSyncExternalStore,type CSSProperties} from 'react';
import type {Drauu} from 'drauu';
import {stepLabel} from '@notale/editor/browser';
import {PresentationController,type Tool} from './controller';
import {FitStage,DrawingLayer} from './stage';
import {PresentationOverview} from './overview';
import {PresenterSplitter} from './splitter';
import {PresentationDisplayMenu} from './display-menu';
import {upcoming} from './upcoming';
import {Icon,ToolButton} from './icons';
import 'reveal.js/dist/reveal.css';
import './presentation.css';
function Clock({timer}:{timer:{elapsed:number;runningSince:number|null}}){const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[]);const seconds=Math.floor((timer.elapsed+(timer.runningSince===null?0:Math.max(0,now-timer.runningSince)))/1000);return <time id="timer">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</time>;}
function WallClock(){const [time,setTime]=useState('');useEffect(()=>{const tick=()=>setTime(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[]);return <time className="ps-wallclock">{time}</time>;}
export function Presentation(){const [controller,setController]=useState<PresentationController>();useEffect(()=>{const value=new PresentationController();setController(value);return()=>value.destroy();},[]);return controller?<PresentationShell controller={controller}/>:<main className="presentation-app"><div className="ps-boot">正在准备放映…</div></main>;}
function PresentationShell({controller}:{controller:PresentationController}){
 const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),state=view.state,slide=view.slides.find(s=>s.id===state?.slideId),index=view.slides.findIndex(s=>s.id===state?.slideId);
 const root=useRef<HTMLDivElement>(null),reveal=useRef<HTMLDivElement>(null),drawing=useRef<Drauu|undefined>(undefined),notes=useRef<HTMLDivElement>(null);
 const [ratio,setRatio]=useState(66),[fontSize,setFontSize]=useState(22),[visible,setVisible]=useState(true),[focused,setFocused]=useState(false);
 const bindDrawing=useCallback((value:Drauu|undefined)=>{drawing.current=value;},[]);
 useEffect(()=>{void controller.mount(reveal.current!);try{const settings=JSON.parse(localStorage.getItem('notale-presenter-layout')??'{}');if(settings.ratio>=48&&settings.ratio<=76)setRatio(settings.ratio);if(settings.fontSize>=18&&settings.fontSize<=32)setFontSize(settings.fontSize);}catch{}},[controller]);
 useEffect(()=>{const observer=new ResizeObserver(()=>controller.layout());if(root.current)observer.observe(root.current);return()=>observer.disconnect();},[controller]);
 useEffect(()=>{setVisible(true);const timer=setTimeout(()=>setVisible(false),2000);return()=>clearTimeout(timer);},[view.activity]);
 useEffect(()=>{if(notes.current)notes.current.scrollTop=0;},[state?.slideId,slide?.notes,slide?.steps?.[state?.step??0]?.notes]);
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(isComposingKey(event))return;const target=event.target as HTMLElement;if(['INPUT','TEXTAREA','SELECT'].includes(target.tagName))return;if((event.ctrlKey||event.metaKey)&&['z','y'].includes(event.key.toLowerCase())&&['pen','highlight','eraser'].includes(controller.getSnapshot().tool)){event.preventDefault();event.stopImmediatePropagation();if(event.key.toLowerCase()==='y'||event.shiftKey)drawing.current?.redo();else drawing.current?.undo();}};window.addEventListener('keydown',listener,true);return()=>window.removeEventListener('keydown',listener,true);},[controller]);
 const leader=view.control==='controlling',audience=controller.audience,speaker=view.speaker,width=view.snapshot?.document.width??1600,height=view.snapshot?.document.height??900;
 const automatic=!!slide&&((slide.advanceAfter??0)>0||slide.steps?.some(step=>(step.advanceAfter??0)>0));
 const next=upcoming(view)?.slide;
 function settings(nextRatio=ratio,nextFont=fontSize){try{localStorage.setItem('notale-presenter-layout',JSON.stringify({ratio:nextRatio,fontSize:nextFont}));}catch{}}

 const toolButtons=(compact=false)=><div className="ps-tools"><ToolButton label="指针 · 操作互动内容" icon="pointer" active={view.tool==='pointer'} disabled={!leader} onClick={()=>controller.tool('pointer')}/>{(['laser','pen','highlight','eraser'] as Tool[]).map(tool=><ToolButton key={tool} label={({laser:'激光笔 · L',pen:'画笔 · P',highlight:'荧光笔',eraser:'橡皮'} as Record<string,string>)[tool]} icon={tool} active={view.tool===tool} disabled={!leader} onClick={()=>controller.tool(tool)}/>)}<i className="ps-divider"/><ToolButton id="overview" label="查看所有页面 · O" icon="grid" active={view.overview} disabled={!leader} onClick={controller.overview}/><ToolButton label={state?.viewport.scale===1?'局部放大':'还原画面'} icon="zoom" active={view.tool==='zoom'||state?.viewport.scale!==1} disabled={!leader} onClick={()=>state?.viewport.scale!==1?controller.viewport({scale:1,x:0,y:0}):controller.tool('zoom')}/><ToolButton id="blank" label="黑屏 / 恢复 · B" icon="blank" active={state?.blank} disabled={!leader} onClick={controller.blank}/>{!compact&&<><i className="ps-divider"/><ToolButton label="撤销标注 · Ctrl Z" icon="undo" disabled={!leader} onClick={()=>drawing.current?.undo()}/><ToolButton label="重做标注 · Ctrl Shift Z" icon="redo" disabled={!leader} onClick={()=>drawing.current?.redo()}/><ToolButton label="清除本页标注" icon="trash" disabled={!leader} onClick={()=>drawing.current?.clear()}/></>}</div>;
 const navigation=<div className="ps-navigation"><ToolButton id="prev" label="上一步 · ←" icon="back" disabled={!leader||index===0&&state?.step===0&&!state?.ended} onClick={controller.prev}/><button className="ps-position" aria-label="选择页面" disabled={!leader} onClick={controller.overview}><strong>{index+1}</strong><span>/ {view.slides.length}</span></button><ToolButton id="next" label="下一步 · →" icon="next" disabled={!leader||!view.ready||state?.ended} onClick={controller.next}/>{state&&state.max>0&&<span className="ps-step-position">步骤 {state.step} / {state.max}</span>}</div>;
 return <main ref={root} className={'presentation-app '+(speaker?'ps-presenter':'ps-slideshow')+(audience?' ps-audience':'')} style={{'--presenter-left':ratio+'%','--notes-size':fontSize+'px'} as CSSProperties} onPointerMove={controller.activity}>
 {speaker&&<header className="ps-header"><div className="ps-title"><span className="ps-mark">N</span><strong>{view.snapshot?.document.title??'正在准备…'}</strong></div>{state&&<div className="ps-time"><span>已用时间</span><Clock timer={state.timer}/><ToolButton label={state.timer.runningSince===null?'继续计时':'暂停计时'} icon={state.timer.runningSince===null?'play':'pause'} disabled={!leader} onClick={controller.timerPause}/><ToolButton id="reset-timer" label="重新计时" icon="reset" disabled={!leader} onClick={controller.timerReset}/></div>}<WallClock/><PresentationDisplayMenu controller={controller}/><button className="ps-end-button" onClick={controller.end}>结束放映</button></header>}
 <div className="ps-workspace">
 <section className="ps-current"><div className="ps-current-heading"><span>当前画面</span><span>{state?.blank?'观众画面已黑屏':audience?'':view.audiences>0?'观众窗口已连接':speaker?'尚未打开观众窗口':''}</span></div><div className="ps-live-area"><FitStage width={width} height={height} viewport={state?.viewport}><div ref={reveal} className="reveal ps-reveal"><div className="slides"/></div>{state&&<DrawingLayer controller={controller} view={view} width={width} height={height} bind={bindDrawing}/>}</FitStage>{!view.ready&&!view.error&&<div className="ps-loading"><span className="ps-loading-dot"/>正在准备画面</div>}{state?.ended&&<div className="ps-finish"><span className="ps-finish-line"/><h1>本次放映已结束</h1>{!audience&&<><p>感谢聆听</p><div><button onClick={controller.prev}>返回最后一页</button><button className="ps-primary" onClick={controller.end}>结束放映</button></div></>}</div>}{state?.blank&&!speaker&&<div className="ps-blackout"/>}</div>{speaker&&<div className="ps-current-footer">{toolButtons()}<span className="ps-slide-name">{slide?.name}</span></div>}</section>
 {speaker&&<><PresenterSplitter value={ratio} onChange={setRatio} onCommit={value=>settings(value)}/><aside id="speaker-panel" className="ps-speaker-panel"><section className="ps-upcoming"><div className="ps-section-heading"><span>{state&&state.step<state.max?'下一步':'下一页'}</span><span>{next?(state&&state.step<state.max?stepLabel(next,state.step+1):next.name):'放映结束'}</span></div><div className="ps-upcoming-image" style={{aspectRatio:`${width}/${height}`}}>{next&&<PosterImage url={controller.posterUrl(next.id,state&&state.step<state.max?state.step+1:0)} title="下一步预览"/>}{!next&&<div className="ps-next-end"><Icon name="play"/><span>已到最后一页</span></div>}</div></section><section className="ps-notes-panel"><div className="ps-section-heading"><span><Icon name="notes" size={16}/>演讲者备注</span><div className="ps-notes-size"><button aria-label="减小备注字号" disabled={fontSize<=18} onClick={()=>{setFontSize(fontSize-2);settings(ratio,fontSize-2);}}>A−</button><button aria-label="增大备注字号" disabled={fontSize>=32} onClick={()=>{setFontSize(fontSize+2);settings(ratio,fontSize+2);}}>A＋</button></div></div><div id="notes" ref={notes} className="ps-notes"><h2 id="step-title">{slide&&state?stepLabel(slide,state.step):''}</h2>{slide?.steps?.[state?.step??0]?.notes&&<p className="ps-step-notes">{slide.steps[state!.step].notes}</p>}{slide?.notes?<p>{slide.notes}</p>:!slide?.steps?.[state?.step??0]?.notes&&<p className="ps-empty-notes">暂无备注</p>}</div>{state&&state.max>0&&<div className="ps-cue-picker"><label htmlFor="show-step">当前步骤</label><select id="show-step" value={state.step} disabled={!leader} onChange={e=>controller.seek(Number(e.target.value),false)}>{Array.from({length:state.max+1},(_,step)=><option key={step} value={step}>{step} · {stepLabel(slide!,step)}</option>)}</select></div>}</section></aside></>}
 </div>
 {speaker&&<footer className="ps-footer"><span className="ps-connection" role="status"><i data-connected={view.audiences>0}/>{view.control==='controlling'?(view.audiences?'正在讲授':'演讲者视图'):view.control==='following'?'跟随其他窗口':'正在连接…'}</span>{!leader&&view.control==='following'&&<button id="take-control" onClick={controller.takeover}>接管放映</button>}{automatic&&<button className="ps-auto" aria-pressed={!state?.autoPaused} onClick={controller.autoPause} disabled={!leader}><Icon name={state?.autoPaused?'play':'pause'} size={16}/>{state?.autoPaused?'继续自动推进':'暂停自动推进'}</button>}<span className="ps-footer-hint">空格 / → 下一步</span>{navigation}</footer>}
 {!speaker&&!audience&&<nav className={'ps-floating-controls '+(visible||focused?'is-visible':'')} aria-label="放映控制" onPointerEnter={()=>setFocused(true)} onPointerLeave={()=>setFocused(false)} onFocus={()=>setFocused(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false);}}>{navigation}<i className="ps-divider"/>{toolButtons(true)}<ToolButton id="speaker" label="演讲者视图" icon="monitor" onClick={controller.speaker}/><ToolButton id="fullscreen" label="全屏 · F" icon="fullscreen" onClick={controller.fullscreen}/><ToolButton label="结束放映" icon="close" onClick={controller.end}/></nav>}
 {!speaker&&!view.sound&&view.ready&&<div className="ps-output-enable"><button onClick={()=>{controller.enableSound();controller.fullscreen();}}><Icon name="fullscreen"/>全屏并启用声音</button><button aria-label="仅启用声音" onClick={controller.enableSound}><Icon name="sound"/></button></div>}
 {view.overview&&!audience&&<PresentationOverview controller={controller} slides={view.slides} currentId={state?.slideId} width={width} height={height}/>}
 {!audience&&(view.error||view.capabilities.length>0)&&<aside className="ps-notice" role="status"><span>{view.error||view.capabilities.join('；')}</span>{view.error&&<button aria-label="关闭提示" onClick={controller.clearError}><Icon name="close" size={16}/></button>}</aside>}
 <ResourceNotice scope="presentation"/>
 </main>;
}
