'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {createDrauu,type Drauu} from 'drauu';
import type {PresentationController,PresentationView} from './controller';
export function FitStage({width,height,children,viewport}:{width:number;height:number;children:ReactNode;viewport?:{scale:number;x:number;y:number}}){
 const host=useRef<HTMLDivElement>(null);const [scale,setScale]=useState(0);
 useEffect(()=>{const resize=new ResizeObserver(()=>{const node=host.current!;setScale(Math.min(node.clientWidth/width,node.clientHeight/height));});resize.observe(host.current!);return()=>resize.disconnect();},[width,height]);
 return <div ref={host} className="ps-fit"><div className="ps-fit-inner" style={{width,height,transform:`translate(-50%, -50%) scale(${scale})`}}><div className="ps-world" style={{transform:viewport?`scale(${viewport.scale})`:undefined,transformOrigin:viewport?`${viewport.x*100}% ${viewport.y*100}%`:undefined}}>{children}</div></div></div>;
}
function safeInk(value:string){const doc=new DOMParser().parseFromString('<svg xmlns="http://www.w3.org/2000/svg">'+value+'</svg>','image/svg+xml');if(doc.querySelector('parsererror'))return '';for(const node of [...doc.querySelectorAll('*')]){if(!['svg','g','path','line','rect','ellipse','circle','polyline','polygon'].includes(node.localName)){node.remove();continue;}for(const attr of [...node.attributes])if(!['xmlns','d','points','x','y','x1','x2','y1','y2','width','height','rx','ry','cx','cy','r','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','opacity','fill-opacity','stroke-opacity','transform','data-ink'].includes(attr.name)||/url\(|javascript:/i.test(attr.value))node.removeAttribute(attr.name);}return doc.documentElement.innerHTML;}
export function DrawingLayer({controller,view,width,height,bind}:{controller:PresentationController;view:PresentationView;width:number;height:number;bind:(drauu:Drauu|undefined)=>void}){
 const svg=useRef<SVGSVGElement>(null),laser=useRef<HTMLDivElement>(null),drauu=useRef<Drauu>(undefined),state=useRef(view),muted=useRef(false),page=useRef('');state.current=view;
 useEffect(()=>{const el=svg.current!,drawing=createDrauu({el,acceptsInputTypes:[],brush:{mode:'stylus',color:'#f24b60',size:4}});drauu.current=drawing;bind(drawing);drawing.on('committed',node=>{if(node&&state.current.tool==='highlight')node.setAttribute('opacity','.35');});let raf=0;
 const changed=()=>{if(muted.current||state.current.control!=='controlling')return;if(!raf)raf=requestAnimationFrame(()=>{raf=0;controller.annotate(drawing.dump());});};
 const observer=new MutationObserver(records=>{if(records.some(r=>r.target!==el||r.type==='childList'))changed();});observer.observe(el,{subtree:true,attributes:true,childList:true});const dispose=controller.onPointer(data=>{if(data.kind==='history'){if(data.redo)drawing.redo();else drawing.undo();return;}if(laser.current){laser.current.style.display=data.point?'block':'none';if(data.point){laser.current.style.left=data.point.x*width+'px';laser.current.style.top=data.point.y*height+'px';}}});
 return()=>{cancelAnimationFrame(raf);observer.disconnect();dispose();drawing.unmount();drauu.current=undefined;bind(undefined);};},[controller,width,height,bind]);
 useEffect(()=>{const drawing=drauu.current;if(!drawing)return;const value=view.state?.annotations[view.state.slideId]??'';const changedPage=page.current!==view.state?.slideId;
 if(changedPage||view.control!=='controlling'){muted.current=true;drawing.load(safeInk(value));page.current=view.state?.slideId??'';queueMicrotask(()=>{muted.current=false;});}
 },[view.state?.slideId,view.state?.annotations,view.control]);
 useEffect(()=>{const drawing=drauu.current;if(drawing){drawing.options.acceptsInputTypes=['pen','highlight','eraser'].includes(view.tool)?['mouse','touch','pen']:[];drawing.options.brush={mode:view.tool==='eraser'?'eraseLine':'stylus',color:view.tool==='highlight'?'#ffe45c':'#f24b60',size:view.tool==='highlight'?24:4};}if(view.tool!=='laser'){controller.pointer(null);if(laser.current)laser.current.style.display='none';}},[view.tool,controller]);
 function point(e:React.PointerEvent<SVGSVGElement>){const matrix=e.currentTarget.getScreenCTM();if(!matrix)return{x:0,y:0};const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return{x:Math.max(0,Math.min(1,point.x/width)),y:Math.max(0,Math.min(1,point.y/height))};}
 const active=view.control==='controlling'&&view.tool!=='pointer';
 return <><svg ref={svg} className={'ps-ink ps-tool-'+view.tool} width={width} height={height} viewBox={`0 0 ${width} ${height}`} style={{pointerEvents:active?'auto':'none'}} onPointerMove={e=>{controller.activity();if(view.tool==='laser'){const p=point(e);if(laser.current){laser.current.style.display='block';laser.current.style.left=p.x*width+'px';laser.current.style.top=p.y*height+'px';}controller.pointer(p);}}} onPointerLeave={()=>{if(view.tool==='laser'){controller.pointer(null);if(laser.current)laser.current.style.display='none';}}} onPointerDown={e=>{if(view.tool==='zoom'){const p=point(e);controller.viewport({scale:view.state?.viewport.scale===1?2:1,...p});controller.tool('pointer');}}}/><div ref={laser} className="ps-laser"/></>;
}
export function OverviewThumbnail({controller,id,width,height}:{controller:PresentationController;id:string;width:number;height:number}){
 const host=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(false);
 useEffect(()=>{const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting));observer.observe(host.current!);return()=>observer.disconnect();},[]);
 return <div ref={host} className="ps-thumbnail" style={{aspectRatio:`${width}/${height}`}}>{visible&&<FitStage width={width} height={height}><iframe title="页面缩略图" src={controller.url(id)} sandbox="allow-scripts allow-same-origin" tabIndex={-1} inert onLoad={e=>{const frame=e.currentTarget,url=new URL(frame.src),channel=url.pathname.split('/')[2];for(const [type,data] of [['presentation-config',{role:'preview',sound:false}],['seek',{step:0,animate:false,media:false}]] as const)frame.contentWindow?.postMessage({source:'notale-host',channel,type,data},url.origin);}}/></FitStage>}</div>;
}
