export const STYLE_PRESETS = Object.freeze({
  'handdrawn-technical': Object.freeze({
    name: '手绘技术解释风',
    seedreamBrief: '象牙白高级纸张上的手绘技术解释风，清晰墨线配少量粉笔蓝、鼠尾草绿、陶土橙和淡紫彩铅，像优秀技术作者亲手绘制但具有出版级精度，温暖、严谨、有作者感。',
    modelBrief: 'High-end hand-drawn technical explainer on refined ivory paper. Confident black ink lines, restrained colored-pencil fills, accurate diagrams, warm authored character, and publication-level finish.',
    visualDirection: '像优秀技术作者在高级纸张上亲手画出的教学图：逻辑严谨、笔触自然、层次丰富。',
    palette: '象牙白、墨黑、粉笔蓝、鼠尾草绿、陶土橙与少量淡紫。',
    typography: '标题具有清楚的手写黑体感，正文自然但高度可读。',
    graphicLanguage: '精确手绘节点、箭头、表格与关系图，彩铅淡涂，极淡自然边角装饰。',
    depth: '纸张肌理、铅笔线和淡彩叠色，不使用照片、3D 或数字界面。',
    density: '中等教学密度，一个连续解释图占主导。',
    recurringMotifs: ['彩铅下划线', '手绘箭头', '页底记忆句', '极淡山线或枝叶'],
    layoutUsageRule: '共享纸张、笔触和彩铅色；构图随知识角色变化，不套固定卡片。',
  }),
  'swiss-editorial': Object.freeze({
    name: '瑞士网格知识编辑风',
    seedreamBrief: '高端瑞士国际主义知识图解风，暖白纯色底，严格但灵活的非对称网格，超大中文黑体标题与极少量短标签形成强烈尺度对比，主色为黑与钴蓝，只用一处朱红强调，二维几何图形、细线和大片留白。只排版题面明确列出的中文，绝不添加说明段落、页脚、路牌、导视标签、装饰性正文或任何伪文字；所有未指定区域保持完全无字。',
    modelBrief: 'Premium Swiss International Style for educational publishing: warm white field, asymmetric modular grid, oversized Chinese sans-serif hierarchy, cobalt blue structure, one vermilion accent, precise flat geometry, and generous whitespace.',
    visualDirection: '用国际主义网格把复杂知识压缩成强秩序与大胆尺度对比。',
    palette: '暖白、黑、钴蓝与单一朱红强调。',
    typography: '超大现代黑体标题，只有必要的短标签与一句结论，严格左对齐，不设置小号正文。',
    graphicLanguage: '模块网格、粗细线、实心圆与几何色块；图形承担信息关系。',
    depth: '完全二维，无阴影无质感堆叠，依靠尺度和空间建立层级。',
    density: '低文字密度、强图形密度，信息沿隐形网格组织并保留大片无字留白。',
    recurringMotifs: ['钴蓝基线', '朱红编号', '裁切式大圆', '细线页脚'],
    layoutUsageRule: '共享网格、字体尺度与色彩纪律；每页可切换跨栏、对角、中心或边缘构图。',
    pageHints: {
      concept: '概念页必须保持整页连续暖白底，禁止黑色、钴蓝或任何深色块占据超过画布四分之一，不做左右黑白反相分屏。关系图直接置于暖白底上，用黑色细线、钴蓝结构和唯一一处朱红节点建立重点。',
    },
  }),
  'dark-data-editorial': Object.freeze({
    name: '深色数据科学编辑风',
    seedreamBrief: '深海军蓝全幅背景的高端数据科学编辑风，冷白中文标题，青蓝与珊瑚橙作为信息强调，细直线、空心小方块和清晰网络关系，纯二维无渐变，锐利、沉稳、未来感克制，像顶级技术发布会视觉而不是仪表盘。',
    modelBrief: 'Sophisticated dark data-science editorial design: deep navy field, crisp off-white type, cyan and coral accents, thin structural lines, hollow squares, clean network logic, flat two-dimensional finish, and restrained futurism.',
    visualDirection: '以深色场域、细线网络和鲜明小色块建立锐利技术叙事。',
    palette: '深海军蓝、冷白、青蓝与珊瑚橙。',
    typography: '强对比现代黑体，标题紧凑，标签短而清楚。',
    graphicLanguage: '细线、实心与空心方块、网络轨道和高对比数据符号。',
    depth: '纯二维、无渐变、几乎无阴影，不使用 HUD 或玻璃拟态。',
    density: '中高密度，信息紧凑但分区有明确呼吸。',
    recurringMotifs: ['细线轨道', '青蓝节点', '珊瑚判断点', '边角空心方块'],
    layoutUsageRule: '共享深色场域和几何语言；按内容切换中心主图、对比、路径或总结构图。',
  }),
  'retro-flat-learning': Object.freeze({
    name: '复古扁平学习插画风',
    seedreamBrief: '复古现代主义的扁平学习插画风，奶油色背景，深墨绿、芥末黄、砖红与湖蓝套色，圆润几何形、丝网印刷颗粒和聪明的视觉隐喻，亲切活泼但不幼稚，像高品质知识绘本与文化海报的结合。',
    modelBrief: 'Retro-modern flat educational illustration: cream background, deep forest green, mustard, brick red, and teal spot colors, rounded geometric forms, subtle screen-print grain, clever visual metaphors, lively but sophisticated.',
    visualDirection: '把抽象技术概念转译成聪明、亲切又具有文化海报气质的扁平隐喻。',
    palette: '奶油色、深墨绿、芥末黄、砖红与湖蓝。',
    typography: '圆润有力的现代中文黑体，短标题与标签结合。',
    graphicLanguage: '圆润几何、套色插画、丝网印刷颗粒、图形化箭头与象征物。',
    depth: '平面套色与轻微纸纹，不使用真实照片、玻璃或 3D。',
    density: '中等偏低，一个大型隐喻配少量信息标签。',
    recurringMotifs: ['太阳圆盘', '套色箭头', '几何植物', '圆角结论条'],
    layoutUsageRule: '共享套色、圆润形状与印刷颗粒；页面主视觉根据教学任务自由变化。',
  }),
  'ink-wash-systems': Object.freeze({
    name: '当代水墨系统图风',
    seedreamBrief: '当代东方水墨系统图风，整页暖白宣纸底，墨黑水痕与干笔线构成结构，少量矿物青蓝和唯一一处朱砂红标记关键节点，留白辽阔，克制而有力量。所有文字使用清晰现代中文黑体，水墨只用于图形；绝不生成题跋、印章、书法字、伪文字或古风装饰。',
    modelBrief: 'Contemporary East-Asian ink-wash systems diagram on warm white rice paper. Dry black brush structure, restrained mineral blue, one cinnabar focus, expansive negative space, and crisp modern Chinese typography separate from the ink artwork.',
    visualDirection: '用水墨的浓淡、断续和留白表达系统中的路径、阻力与关键转折。',
    palette: '暖白宣纸、墨黑、矿物青蓝与单一朱砂红。',
    typography: '现代中文黑体，字形清楚克制；不用书法字体或题跋。',
    graphicLanguage: '水墨路径、干笔节点、飞白连接与少量规则几何形成古今张力。',
    depth: '二维水墨渗化和纸纤维，不做古画卷轴、相框或拟真 3D。',
    density: '低密度，以一条主路径或一个系统主图统领大片留白。',
    recurringMotifs: ['朱砂关键点', '矿物蓝路径', '干笔转折', '淡墨留白'],
    layoutUsageRule: '共享纸张、水墨笔触和三色纪律；不同页面按过程、对照或收束改变墨迹走势。',
  }),
  'clay-isometric-learning': Object.freeze({
    name: '黏土等距教学模型风',
    seedreamBrief: '高端黏土等距教学模型风，暖灰白摄影棚背景，哑光软陶质感的简洁三维对象，珊瑚橙、湖蓝、芥末黄和深青绿形成克制配色，柔和方向光与短阴影建立空间关系，亲切但专业。标题和标签必须是清晰平面的中文黑体，绝不做成物体表面的浮雕字；不画色板样例，也不生成玩具包装、界面、说明书或伪文字。',
    modelBrief: 'Premium isometric clay educational models on a warm off-white studio field. Matte tactile objects, restrained coral, teal, mustard and deep green, soft directional light, short shadows, and crisp flat Chinese typography separate from the 3D objects.',
    visualDirection: '把抽象网络过程变成可以拿在手里观察的等距微缩教学模型。',
    palette: '暖灰白、珊瑚橙、湖蓝、芥末黄与深青绿。',
    typography: '平面现代中文黑体，标题大而清楚，标签短，不贴在三维物体表面。',
    graphicLanguage: '等距小模型、圆角管道、门、节点、托盘和方向性路径。',
    depth: '哑光黏土三维、柔光和短阴影，不使用真实照片、玻璃或金属炫光。',
    density: '中低密度，一个连续微缩场景承担主要解释。',
    recurringMotifs: ['等距圆台', '软陶管道', '彩色关卡', '短投影'],
    layoutUsageRule: '共享材质、光向和观察角度；每页按流程、分支或检查站重新搭建场景。',
    pageHints: {
      summary: '总结页的外围软陶对象数量必须与 copy plan 中除主标题和底部结论外的关键词数量完全一致。每个指定关键词各出现一次，并使用悬浮在对象附近的平面黑色印刷字；禁止把汉字塑造成软陶立体字或贴在物体表面。',
    },
    pageCompositions: {
      summary: '标题位于左上。主体是一个中央白色圆形诊断镜；把 copy plan 中除主标题和底部结论外的全部关键词逐一绑定到外围软陶圆盘，圆盘数量与关键词数量严格一致，并尽量遵守 copy plan 中的方位说明。各圆盘通过独立短线连接中心。不要阶梯、跑道、额外圆盘或色板样例。底部只放一句加粗结论。',
    },
  }),
  'neo-brutalist-signal': Object.freeze({
    name: '信号式新粗野主义风',
    seedreamBrief: '高质量信号式新粗野主义知识海报，脏白或纯黑底，大号紧凑中文黑体，粗黑边框、外露网格、硬直箭头与醒目信号色块，使用酸性黄、电蓝和警示红，强烈、直接、具有文化海报感但排版精确。只使用题面指定的短文字，绝不生成小号正文、随机数字、条形码、贴纸文字、网页组件或伪文字。',
    modelBrief: 'High-quality neo-brutalist signal poster for education: off-white or black field, oversized compressed Chinese sans serif, exposed grid, heavy rules, hard arrows, acid yellow, electric blue and warning red, raw energy with exact editorial control.',
    visualDirection: '用信号、撞色和粗线把判断顺序变成一眼可见的视觉命令。',
    palette: '脏白、纯黑、酸性黄、电蓝与警示红。',
    typography: '超大紧凑中文黑体与极少量粗标签，拒绝小字号装饰正文。',
    graphicLanguage: '粗边框、外露网格、硬直箭头、撞色色块与裁切式大字。',
    depth: '纯二维硬边，无柔和渐变、拟物阴影或玻璃效果。',
    density: '中等，图形占满但文字极少，视觉冲击优先。',
    recurringMotifs: ['酸性黄信号条', '警示红关键点', '电蓝粗箭头', '黑色外露网格'],
    layoutUsageRule: '共享粗线、信号色和大字尺度；按页面任务切换水平推进、左右冲突或四角信号站。',
    pageHints: {
      summary: '总结页的信号块数量必须与 copy plan 中除主标题和底部结论外的关键词数量完全一致，每个关键词各出现一次。不要黑色中央面板、线路板、阶梯、竖向堆叠、警告图标、随机数字或额外标签。',
    },
    pageCompositions: {
      summary: '使用整页连续脏白底，不做左右分屏。标题以超大黑字占据画布上方约四分之一。把 copy plan 中除主标题和底部结论外的全部关键词放入彼此分离的大号矩形信号块，沿画布外围分散排布并遵守 copy plan 的显式方位；信号块沿画布外缘由一条粗黑闭环顺序连接，中央保留巨大空白并只放一个警示红问号。不得排成阶梯或竖列，不要中央黑色面板和复杂线路。底部结论独占一条横贯全宽的酸性黄信号带。',
    },
  }),
});

export function resolveStylePreset(id) {
  if (!id) return null;
  const preset = STYLE_PRESETS[id];
  if (!preset) throw new Error(`未知 visualPlanning.stylePreset: ${id}`);
  return {
    ...preset,
    recurringMotifs: [...(preset.recurringMotifs || [])],
    pageHints: { ...(preset.pageHints || {}) },
    pageCompositions: { ...(preset.pageCompositions || {}) },
  };
}
